INSERT INTO help_categories (slug, title, icon, sort) VALUES
  ('konto-sicherheit', 'Konto & Sicherheit', 'shield-check', 10),
  ('ernaehrung', 'Lebensmittel & Rezepte', 'salad', 20),
  ('finanzen', 'Finanzen', 'wallet-cards', 30),
  ('notizen-cloud', 'Notizen & Cloud', 'notebook-tabs', 40),
  ('assistent', 'KI-Assistent', 'bot', 50)
ON DUPLICATE KEY UPDATE title=VALUES(title), icon=VALUES(icon), sort=VALUES(sort);

INSERT INTO help_articles (category_id, slug, title, body, keywords, is_faq, sort) VALUES
((SELECT id FROM help_categories WHERE slug='konto-sicherheit'), 'zwei-faktor-authentifizierung', 'Zwei-Faktor-Authentifizierung einrichten', 'Öffne Einstellungen → Datenschutz → Zwei-Faktor-Authentifizierung. Bestätige dein Passwort, scanne den QR-Code mit einer TOTP-kompatiblen Authenticator-App und gib den aktuellen sechsstelligen Code ein. Ab der nächsten Anmeldung fragt NutriDesk nach Passwort und Authenticator-Code.', '2fa totp authenticator qr code login sicherheit', 1, 10),
((SELECT id FROM help_categories WHERE slug='konto-sicherheit'), 'wetterstandort', 'Standort für Wetter verwalten', 'Unter Einstellungen → Datenschutz kannst du die Standortfreigabe aktivieren. Suche eine Adresse oder Stadt und wähle einen Treffer, oder verwende nach Browserfreigabe deinen aktuellen Standort. Beim Ausschalten werden der gespeicherte Ort und die Koordinaten gelöscht.', 'wetter standort adresse stadt browser freigabe löschen', 1, 20),
((SELECT id FROM help_categories WHERE slug='ernaehrung'), 'lebensmittel-openfoodfacts', 'Lebensmittel suchen und tracken', 'Die Lebensmittelsuche nutzt OpenFoodFacts und speichert benötigte Produkte mit Bild, Barcode, Kalorien und Makronährstoffen zwischen. Im Fitness-Tracker wählst du ein Lebensmittel, passt die Menge an und ordnest es einer Mahlzeit zu.', 'lebensmittel openfoodfacts kcal makros barcode bild tracker', 1, 10),
((SELECT id FROM help_categories WHERE slug='ernaehrung'), 'eigene-rezepte', 'Eigene Rezepte erstellen', 'Unter Meine Rezepte erstellst du persönliche Rezepte und verknüpfst Zutaten aus der Lebensmittel-Datenbank. Deine veröffentlichten Rezepte erscheinen zusätzlich in deinem Community-Profil.', 'eigene rezepte zutaten community profil', 1, 20),
((SELECT id FROM help_categories WHERE slug='finanzen'), 'finanzbuch-archiv', 'Wie funktioniert das Finanzbuch?', 'Das Finanzbuch ist ein eigenständiges Archiv für manuelle Buchungen sowie CSV- und Bankimporte. Einträge dort verändern bewusst nicht die Finanzübersicht, regulären Einnahmen oder monatlichen Verpflichtungen. Mit Monat analysieren erhältst du eine Auswertung des ausgewählten Archivmonats.', 'finanzbuch archiv csv bank import analysieren übersicht', 1, 10),
((SELECT id FROM help_categories WHERE slug='finanzen'), 'monatliche-uebersicht', 'Monatliche Kosten und verfügbarer Betrag', 'Die Finanzübersicht addiert laufende Verträge, Kreditraten und automatisch abgezogene Sparziele. Davon werden die aktiven monatlichen Einnahmen abgezogen, sodass du direkt siehst, welcher Betrag im Monat übrig bleibt.', 'übersicht einnahmen kosten kredite abos sparziele übrig', 1, 20),
((SELECT id FROM help_categories WHERE slug='notizen-cloud'), 'notizbilder-pdf', 'Notizen mit Bildern und PDF', 'Beim Bearbeiten einer Notiz kannst du mehrere Bilder anhängen. Uploads werden vor der Freigabe geprüft und auf Schadsoftware gescannt. Die PDF-Ausgabe enthält das NutriDesk-Design, das Logo, Notiztexte und alle zugehörigen Bilder.', 'notizen bilder anhang pdf logo export virenscan', 1, 10),
((SELECT id FROM help_categories WHERE slug='notizen-cloud'), 'cloud-upload-sicherheit', 'Wie werden Cloud-Dateien geschützt?', 'Neue Dateien landen zunächst in Quarantäne. NutriDesk prüft Dateityp und Dateisignatur und lässt ClamAV nach Schadsoftware suchen. Nur erfolgreich geprüfte Dateien werden in den persönlichen Cloud-Speicher übernommen.', 'cloud upload quarantäne antivirus clamav schadsoftware sicherheit', 1, 20),
((SELECT id FROM help_categories WHERE slug='assistent'), 'assistent-funktionen', 'Was kann Sophia oder Conrad?', 'Der Assistent hilft bei Lebensmitteln, Fitness-Tracking, eigenen Rezepten, Finanzen, Terminen, Notizen, Hilfeartikeln und Wetter. Der gewählte Name Sophia oder Conrad wird auch in der Begrüßung übernommen. Sprachausgabe erfolgt ausschließlich über ElevenLabs und nur nach deinen Datenschutzeinstellungen.', 'sophia conrad ki assistent befehle elevenlabs wetter finanzen notizen', 1, 10)
ON DUPLICATE KEY UPDATE category_id=VALUES(category_id), title=VALUES(title), body=VALUES(body), keywords=VALUES(keywords), is_faq=VALUES(is_faq), sort=VALUES(sort);
