// Zutaten-Nährwerttabelle für die NutriDesk-Rezeptbibliothek.
// Werte pro 100 g im verzehrfertigen Zustand (Reis/Nudeln/Hülsenfrüchte gekocht,
// Fleisch/Fisch gegart), soweit sinnvoll. Quelle: gängige Nährwerttabellen, gerundet.
//
// Felder: n = Anzeigename, kcal, c = Kohlenhydrate, p = Protein, f = Fett (je 100 g)
//   kind: 'meat' | 'fish' | 'egg' | 'dairy' | 'plant' | 'honey'
//   glu: enthält Gluten (1)   |   pri: teure Zutat (1)  -> blockt Tag "guenstig"
//   spice: Gewürz/Kraut (fließt nicht in die Einkaufslistenmenge groß ein)

const P = {
  // ---------- Fleisch & Geflügel ----------
  haehnchen:   { n: 'Hähnchenbrust',        kcal: 165, c: 0,   p: 31,  f: 3.6, kind: 'meat' },
  haehnchenkeule:{ n:'Hähnchenschenkel',    kcal: 209, c: 0,   p: 26,  f: 11,  kind: 'meat' },
  pute:        { n: 'Putenbrust',           kcal: 135, c: 0,   p: 29,  f: 1.5, kind: 'meat' },
  hackrind:    { n: 'Rinderhackfleisch',    kcal: 250, c: 0,   p: 26,  f: 17,  kind: 'meat' },
  hackgemischt:{ n: 'Hackfleisch gemischt', kcal: 246, c: 0,   p: 24,  f: 17,  kind: 'meat' },
  rindersteak: { n: 'Rindersteak',          kcal: 217, c: 0,   p: 26,  f: 12,  kind: 'meat', pri: 1 },
  schweinefilet:{ n:'Schweinefilet',        kcal: 143, c: 0,   p: 26,  f: 4,   kind: 'meat' },
  schweinebraten:{ n:'Schweinebraten',      kcal: 258, c: 0,   p: 26,  f: 17,  kind: 'meat' },
  kalbsschnitzel:{ n:'Kalbsschnitzel',      kcal: 145, c: 0,   p: 25,  f: 4,   kind: 'meat' },
  schweinekotelett:{ n:'Schweinekotelett',  kcal: 200, c: 0,   p: 26,  f: 11,  kind: 'meat' },
  sucuk:       { n: 'Sucuk',                kcal: 350, c: 1,   p: 22,  f: 28,  kind: 'meat' },
  tintenfisch: { n: 'Tintenfisch',          kcal: 92,  c: 3,   p: 16,  f: 1.4, kind: 'fish' },
  meerrettich: { n: 'Meerrettich',          kcal: 48,  c: 11,  p: 1.2, f: 0.7, kind: 'plant', spice: 1 },
  schweineschnitzel:{ n:'Schweineschnitzel',kcal: 172, c: 0,   p: 30,  f: 5,   kind: 'meat' },
  bacon:       { n: 'Bacon',                kcal: 400, c: 0,   p: 12,  f: 39,  kind: 'meat' },
  kochschinken:{ n: 'Kochschinken',         kcal: 107, c: 1,   p: 18,  f: 3,   kind: 'meat' },
  salami:      { n: 'Salami',               kcal: 378, c: 1,   p: 21,  f: 32,  kind: 'meat', pri: 1 },
  chorizo:     { n: 'Chorizo',              kcal: 455, c: 2,   p: 24,  f: 38,  kind: 'meat', pri: 1 },
  bratwurst:   { n: 'Bratwurst',            kcal: 330, c: 1,   p: 14,  f: 30,  kind: 'meat' },
  haehncheninnenfilet:{ n:'Hähnchen-Innenfilet', kcal:165, c:0, p:31, f:3.6, kind:'meat' },
  gyrosfleisch:{ n: 'Gyrosfleisch (Schwein)', kcal: 190, c: 2, p: 24, f: 9,  kind: 'meat' },

  // ---------- Fisch & Meeresfrüchte ----------
  lachs:       { n: 'Lachsfilet',           kcal: 208, c: 0,   p: 20,  f: 13,  kind: 'fish', pri: 1 },
  raeucherlachs:{ n:'Räucherlachs',         kcal: 180, c: 0,   p: 25,  f: 9,   kind: 'fish', pri: 1 },
  thunfisch:   { n: 'Thunfisch (Dose)',     kcal: 116, c: 0,   p: 26,  f: 1,   kind: 'fish' },
  kabeljau:    { n: 'Kabeljaufilet',        kcal: 82,  c: 0,   p: 18,  f: 0.7, kind: 'fish', pri: 1 },
  seelachs:    { n: 'Seelachsfilet',        kcal: 81,  c: 0,   p: 18,  f: 1,   kind: 'fish' },
  forelle:     { n: 'Forellenfilet',        kcal: 119, c: 0,   p: 20,  f: 4,   kind: 'fish', pri: 1 },
  garnelen:    { n: 'Garnelen',             kcal: 99,  c: 0,   p: 24,  f: 0.3, kind: 'fish', pri: 1 },
  pangasius:   { n: 'Pangasiusfilet',       kcal: 90,  c: 0,   p: 15,  f: 3,   kind: 'fish' },
  hering:      { n: 'Hering',               kcal: 158, c: 0,   p: 18,  f: 9,   kind: 'fish' },
  sardinen:    { n: 'Sardinen (Dose)',      kcal: 208, c: 0,   p: 25,  f: 11,  kind: 'fish' },

  // ---------- Eier & Milchprodukte ----------
  ei:          { n: 'Ei',                   kcal: 155, c: 1.1, p: 13,  f: 11,  kind: 'egg' },
  eiweiss:     { n: 'Eiweiß',               kcal: 52,  c: 0.7, p: 11,  f: 0.2, kind: 'egg' },
  milch:       { n: 'Milch (1,5%)',         kcal: 47,  c: 4.8, p: 3.4, f: 1.5, kind: 'dairy' },
  magerquark:  { n: 'Magerquark',           kcal: 67,  c: 4,   p: 12,  f: 0.2, kind: 'dairy' },
  quark40:     { n: 'Speisequark (40%)',    kcal: 145, c: 3,   p: 11,  f: 10,  kind: 'dairy' },
  skyr:        { n: 'Skyr',                 kcal: 63,  c: 4,   p: 11,  f: 0.2, kind: 'dairy' },
  naturjoghurt:{ n: 'Naturjoghurt',         kcal: 61,  c: 4.7, p: 3.5, f: 3.3, kind: 'dairy' },
  griechjoghurt:{ n:'Griechischer Joghurt', kcal: 97,  c: 3.6, p: 9,   f: 5,   kind: 'dairy' },
  huettenkaese:{ n: 'Hüttenkäse',           kcal: 98,  c: 3.4, p: 11,  f: 4.3, kind: 'dairy' },
  frischkaese: { n: 'Frischkäse',           kcal: 253, c: 3,   p: 6,   f: 24,  kind: 'dairy' },
  schmand:     { n: 'Schmand',              kcal: 236, c: 3.5, p: 2.8, f: 24,  kind: 'dairy' },
  mascarpone:  { n: 'Mascarpone',           kcal: 430, c: 4,   p: 4,   f: 44,  kind: 'dairy' },
  camembert:   { n: 'Camembert',            kcal: 300, c: 0.5, p: 20,  f: 24,  kind: 'dairy' },
  schmelzkaese:{ n: 'Schmelzkäse',          kcal: 290, c: 6,   p: 12,  f: 24,  kind: 'dairy' },
  creamefraiche:{ n:'Crème fraîche',        kcal: 292, c: 3,   p: 2.4, f: 30,  kind: 'dairy' },
  sahne:       { n: 'Schlagsahne',          kcal: 309, c: 3.3, p: 2.4, f: 32,  kind: 'dairy' },
  kochsahne:   { n: 'Kochsahne (15%)',      kcal: 165, c: 4,   p: 3,   f: 15,  kind: 'dairy' },
  gouda:       { n: 'Gouda',                kcal: 356, c: 0,   p: 25,  f: 28,  kind: 'dairy' },
  mozzarella:  { n: 'Mozzarella',           kcal: 254, c: 3,   p: 18,  f: 19,  kind: 'dairy' },
  feta:        { n: 'Feta',                 kcal: 264, c: 4,   p: 14,  f: 21,  kind: 'dairy', pri: 1 },
  parmesan:    { n: 'Parmesan',             kcal: 400, c: 1,   p: 28,  f: 30,  kind: 'dairy', pri: 1 },
  reibekaese:  { n: 'geriebener Käse',      kcal: 356, c: 1,   p: 25,  f: 28,  kind: 'dairy' },
  halloumi:    { n: 'Halloumi',             kcal: 321, c: 2,   p: 25,  f: 24,  kind: 'dairy', pri: 1 },
  butter:      { n: 'Butter',               kcal: 717, c: 0.7, p: 0.9, f: 81,  kind: 'dairy' },
  ricotta:     { n: 'Ricotta',              kcal: 174, c: 3,   p: 11,  f: 13,  kind: 'dairy' },

  // ---------- Pflanzliche Proteine ----------
  tofu:        { n: 'Tofu natur',           kcal: 144, c: 3,   p: 15,  f: 9,   kind: 'plant' },
  raeuchertofu:{ n: 'Räuchertofu',          kcal: 176, c: 1,   p: 18,  f: 11,  kind: 'plant' },
  tempeh:      { n: 'Tempeh',               kcal: 193, c: 9,   p: 19,  f: 11,  kind: 'plant' },
  seitan:      { n: 'Seitan',               kcal: 120, c: 4,   p: 21,  f: 2,   kind: 'plant', glu: 1 },
  kichererbsen:{ n: 'Kichererbsen (gekocht)', kcal: 164, c: 27, p: 9,  f: 2.6, kind: 'plant' },
  linsen:      { n: 'Linsen (gekocht)',     kcal: 116, c: 20,  p: 9,   f: 0.4, kind: 'plant' },
  rotelinsen:  { n: 'rote Linsen (gekocht)',kcal: 116, c: 20,  p: 9,   f: 0.4, kind: 'plant' },
  kidneybohnen:{ n: 'Kidneybohnen (gekocht)', kcal: 127, c: 23, p: 9,  f: 0.5, kind: 'plant' },
  schwarzebohnen:{ n:'schwarze Bohnen (gekocht)', kcal:132, c:24, p:9, f:0.5, kind:'plant' },
  weissebohnen:{ n: 'weiße Bohnen (gekocht)', kcal: 114, c: 20, p: 7,  f: 0.6, kind: 'plant' },
  erbsen:      { n: 'Erbsen',               kcal: 81,  c: 14,  p: 5,   f: 0.4, kind: 'plant' },
  sojaschnetzel:{ n:'Sojaschnetzel (zubereitet)', kcal:105, c:5, p:16, f:1, kind:'plant' },
  edamame:     { n: 'Edamame',              kcal: 121, c: 9,   p: 12,  f: 5,   kind: 'plant' },

  // ---------- Getreide, Sättigungsbeilagen ----------
  reis:        { n: 'Reis (gekocht)',       kcal: 130, c: 28,  p: 2.7, f: 0.3, kind: 'plant' },
  vollkornreis:{ n: 'Vollkornreis (gekocht)', kcal: 111, c: 23, p: 2.6, f: 0.9, kind: 'plant' },
  basmatireis: { n: 'Basmatireis (gekocht)',kcal: 130, c: 28,  p: 2.7, f: 0.3, kind: 'plant' },
  risottoreis: { n: 'Risottoreis (roh)',    kcal: 350, c: 77,  p: 7,   f: 1,   kind: 'plant' },
  nudeln:      { n: 'Nudeln (gekocht)',     kcal: 158, c: 31,  p: 6,   f: 1,   kind: 'plant', glu: 1 },
  vollkornnudeln:{ n:'Vollkornnudeln (gekocht)', kcal:124, c:25, p:5, f:1.5, kind:'plant', glu:1 },
  spaghetti:   { n: 'Spaghetti (gekocht)',  kcal: 158, c: 31,  p: 6,   f: 1,   kind: 'plant', glu: 1 },
  penne:       { n: 'Penne (gekocht)',      kcal: 158, c: 31,  p: 6,   f: 1,   kind: 'plant', glu: 1 },
  fusilli:     { n: 'Fusilli (gekocht)',    kcal: 158, c: 31,  p: 6,   f: 1,   kind: 'plant', glu: 1 },
  tagliatelle: { n: 'Tagliatelle (gekocht)',kcal: 158, c: 31,  p: 6,   f: 1,   kind: 'plant', glu: 1 },
  gnocchi:     { n: 'Gnocchi',              kcal: 148, c: 30,  p: 4,   f: 1,   kind: 'plant', glu: 1 },
  tortellini:  { n: 'Tortellini',           kcal: 260, c: 35,  p: 11,  f: 8,   kind: 'plant', glu: 1 },
  cannelloni:  { n: 'Cannelloni (roh)',     kcal: 360, c: 72,  p: 12,  f: 2,   kind: 'plant', glu: 1 },
  bandnudeln:  { n: 'Bandnudeln (gekocht)', kcal: 158, c: 31,  p: 6,   f: 1,   kind: 'plant', glu: 1 },
  baguette:    { n: 'Baguette',             kcal: 270, c: 55,  p: 9,   f: 2,   kind: 'plant', glu: 1 },
  ciabatta:    { n: 'Ciabatta',             kcal: 271, c: 52,  p: 9,   f: 3,   kind: 'plant', glu: 1 },
  mienudeln:   { n: 'Mie-Nudeln (gekocht)', kcal: 138, c: 25,  p: 4.5, f: 2.2, kind: 'plant', glu: 1 },
  kartoffeln:  { n: 'Kartoffeln (gekocht)', kcal: 87,  c: 20,  p: 2,   f: 0.1, kind: 'plant' },
  suesskartoffel:{ n:'Süßkartoffel',        kcal: 90,  c: 21,  p: 2,   f: 0.1, kind: 'plant' },
  kartoffelpueree:{ n:'Kartoffelpüree',     kcal: 83,  c: 12,  p: 2,   f: 3,   kind: 'plant' },
  pommes:      { n: 'Ofenpommes',           kcal: 150, c: 24,  p: 2.5, f: 5,   kind: 'plant' },
  quinoa:      { n: 'Quinoa (gekocht)',     kcal: 120, c: 21,  p: 4.4, f: 1.9, kind: 'plant' },
  couscous:    { n: 'Couscous (gekocht)',   kcal: 112, c: 23,  p: 3.8, f: 0.2, kind: 'plant', glu: 1 },
  bulgur:      { n: 'Bulgur (gekocht)',     kcal: 83,  c: 19,  p: 3,   f: 0.2, kind: 'plant', glu: 1 },
  haferflocken:{ n: 'Haferflocken',         kcal: 372, c: 60,  p: 13,  f: 7,   kind: 'plant', glu: 1 },
  vollkornbrot:{ n: 'Vollkornbrot',         kcal: 247, c: 41,  p: 8,   f: 4,   kind: 'plant', glu: 1 },
  toastbrot:   { n: 'Vollkorntoast',        kcal: 245, c: 43,  p: 9,   f: 3,   kind: 'plant', glu: 1 },
  broetchen:   { n: 'Vollkornbrötchen',     kcal: 250, c: 46,  p: 9,   f: 3,   kind: 'plant', glu: 1 },
  wrap:        { n: 'Weizentortilla',       kcal: 290, c: 49,  p: 8,   f: 6,   kind: 'plant', glu: 1 },
  fladenbrot:  { n: 'Fladenbrot',           kcal: 275, c: 52,  p: 9,   f: 2,   kind: 'plant', glu: 1 },
  reiswaffeln: { n: 'Reiswaffeln',          kcal: 387, c: 82,  p: 8,   f: 3,   kind: 'plant' },
  knaeckebrot: { n: 'Knäckebrot',           kcal: 350, c: 65,  p: 10,  f: 2,   kind: 'plant', glu: 1 },
  polenta:     { n: 'Polenta (gekocht)',    kcal: 85,  c: 18,  p: 2,   f: 0.5, kind: 'plant' },
  rote_beete:  { n: 'Rote Bete',            kcal: 43,  c: 8,   p: 1.6, f: 0.2, kind: 'plant' },

  // ---------- Gemüse ----------
  brokkoli:    { n: 'Brokkoli',             kcal: 34,  c: 7,   p: 2.8, f: 0.4, kind: 'plant' },
  blumenkohl:  { n: 'Blumenkohl',           kcal: 25,  c: 5,   p: 1.9, f: 0.3, kind: 'plant' },
  zucchini:    { n: 'Zucchini',             kcal: 17,  c: 3,   p: 1.2, f: 0.3, kind: 'plant' },
  paprika:     { n: 'Paprika',              kcal: 31,  c: 6,   p: 1,   f: 0.3, kind: 'plant' },
  tomaten:     { n: 'Tomaten',              kcal: 18,  c: 3.9, p: 0.9, f: 0.2, kind: 'plant' },
  cherrytomaten:{ n:'Cherrytomaten',        kcal: 18,  c: 3.9, p: 0.9, f: 0.2, kind: 'plant' },
  passata:     { n: 'passierte Tomaten',    kcal: 35,  c: 6,   p: 1.5, f: 0.3, kind: 'plant' },
  tomatenmark: { n: 'Tomatenmark',          kcal: 82,  c: 14,  p: 4,   f: 0.5, kind: 'plant' },
  moehren:     { n: 'Möhren',               kcal: 41,  c: 10,  p: 0.9, f: 0.2, kind: 'plant' },
  spinat:      { n: 'Blattspinat',          kcal: 23,  c: 3.6, p: 2.9, f: 0.4, kind: 'plant' },
  chicoree:    { n: 'Chicorée',             kcal: 17,  c: 3,   p: 1,   f: 0.2, kind: 'plant' },
  kresse:      { n: 'Kresse',               kcal: 33,  c: 5.5, p: 2.6, f: 0.7, kind: 'plant', spice: 1 },
  champignons: { n: 'Champignons',          kcal: 22,  c: 3.3, p: 3,   f: 0.3, kind: 'plant' },
  rosenkohl:   { n: 'Rosenkohl',            kcal: 43,  c: 9,   p: 3.4, f: 0.3, kind: 'plant' },
  gruenebohnen:{ n: 'grüne Bohnen',         kcal: 31,  c: 7,   p: 1.8, f: 0.1, kind: 'plant' },
  aubergine:   { n: 'Aubergine',            kcal: 25,  c: 6,   p: 1,   f: 0.2, kind: 'plant' },
  zwiebel:     { n: 'Zwiebel',              kcal: 40,  c: 9,   p: 1.1, f: 0.1, kind: 'plant' },
  rotezwiebel: { n: 'rote Zwiebel',         kcal: 40,  c: 9,   p: 1.1, f: 0.1, kind: 'plant' },
  knoblauch:   { n: 'Knoblauch',            kcal: 149, c: 33,  p: 6,   f: 0.5, kind: 'plant' },
  lauch:       { n: 'Lauch',                kcal: 61,  c: 14,  p: 1.5, f: 0.3, kind: 'plant' },
  fruehlingszwiebel:{ n:'Frühlingszwiebeln',kcal: 32,  c: 7,   p: 1.8, f: 0.2, kind: 'plant' },
  gurke:       { n: 'Gurke',                kcal: 15,  c: 3.6, p: 0.7, f: 0.1, kind: 'plant' },
  salat:       { n: 'Blattsalat',           kcal: 15,  c: 2.9, p: 1.4, f: 0.2, kind: 'plant' },
  eisbergsalat:{ n: 'Eisbergsalat',         kcal: 14,  c: 3,   p: 0.9, f: 0.1, kind: 'plant' },
  rucola:      { n: 'Rucola',               kcal: 25,  c: 3.7, p: 2.6, f: 0.7, kind: 'plant' },
  mais:        { n: 'Mais (Dose)',          kcal: 86,  c: 16,  p: 3,   f: 1.2, kind: 'plant' },
  kuerbis:     { n: 'Kürbis',               kcal: 26,  c: 7,   p: 1,   f: 0.1, kind: 'plant' },
  sellerie:    { n: 'Staudensellerie',      kcal: 16,  c: 3,   p: 0.7, f: 0.2, kind: 'plant' },
  fenchel:     { n: 'Fenchel',              kcal: 31,  c: 7,   p: 1.2, f: 0.2, kind: 'plant' },
  kohlrabi:    { n: 'Kohlrabi',             kcal: 27,  c: 6,   p: 1.7, f: 0.1, kind: 'plant' },
  weisskohl:   { n: 'Weißkohl',             kcal: 25,  c: 6,   p: 1.3, f: 0.1, kind: 'plant' },
  rotkohl:     { n: 'Rotkohl',              kcal: 29,  c: 7,   p: 1.4, f: 0.2, kind: 'plant' },
  spitzkohl:   { n: 'Spitzkohl',            kcal: 25,  c: 6,   p: 1.3, f: 0.1, kind: 'plant' },
  grünkohl:    { n: 'Grünkohl',             kcal: 49,  c: 9,   p: 4.3, f: 0.9, kind: 'plant' },
  spargel:     { n: 'grüner Spargel',       kcal: 20,  c: 4,   p: 2.2, f: 0.1, kind: 'plant', pri: 1 },
  erbsenschote:{ n: 'Zuckerschoten',        kcal: 42,  c: 7,   p: 3,   f: 0.2, kind: 'plant' },
  pilze_mix:   { n: 'gemischte Pilze',      kcal: 22,  c: 3.3, p: 3,   f: 0.3, kind: 'plant' },
  oliven:      { n: 'Oliven',               kcal: 145, c: 4,   p: 1,   f: 15,  kind: 'plant' },
  avocado:     { n: 'Avocado',              kcal: 160, c: 9,   p: 2,   f: 15,  kind: 'plant', pri: 1 },
  ingwer:      { n: 'Ingwer',               kcal: 80,  c: 18,  p: 1.8, f: 0.8, kind: 'plant' },
  chili:       { n: 'Chilischote',          kcal: 40,  c: 9,   p: 1.9, f: 0.4, kind: 'plant' },

  // ---------- Obst ----------
  banane:      { n: 'Banane',               kcal: 89,  c: 23,  p: 1.1, f: 0.3, kind: 'plant' },
  apfel:       { n: 'Apfel',                kcal: 52,  c: 14,  p: 0.3, f: 0.2, kind: 'plant' },
  birne:       { n: 'Birne',                kcal: 57,  c: 15,  p: 0.4, f: 0.1, kind: 'plant' },
  heidelbeeren:{ n: 'Heidelbeeren',         kcal: 57,  c: 14,  p: 0.7, f: 0.3, kind: 'plant', pri: 1 },
  erdbeeren:   { n: 'Erdbeeren',            kcal: 32,  c: 7.7, p: 0.7, f: 0.3, kind: 'plant' },
  himbeeren:   { n: 'Himbeeren',            kcal: 52,  c: 12,  p: 1.2, f: 0.7, kind: 'plant', pri: 1 },
  brombeeren:  { n: 'Brombeeren',           kcal: 43,  c: 10,  p: 1.4, f: 0.5, kind: 'plant' },
  mango:       { n: 'Mango',                kcal: 60,  c: 15,  p: 0.8, f: 0.4, kind: 'plant', pri: 1 },
  ananas:      { n: 'Ananas',               kcal: 50,  c: 13,  p: 0.5, f: 0.1, kind: 'plant' },
  orange:      { n: 'Orange',               kcal: 47,  c: 12,  p: 0.9, f: 0.1, kind: 'plant' },
  kirschen:    { n: 'Kirschen',             kcal: 63,  c: 16,  p: 1,   f: 0.2, kind: 'plant' },
  pfirsich:    { n: 'Pfirsich',             kcal: 39,  c: 10,  p: 0.9, f: 0.3, kind: 'plant' },
  weintrauben: { n: 'Weintrauben',          kcal: 69,  c: 17,  p: 0.7, f: 0.2, kind: 'plant' },
  kiwi:        { n: 'Kiwi',                  kcal: 61,  c: 15,  p: 1.1, f: 0.5, kind: 'plant' },
  datteln:     { n: 'Datteln',              kcal: 282, c: 75,  p: 2.5, f: 0.4, kind: 'plant' },
  rosinen:     { n: 'Rosinen',              kcal: 299, c: 79,  p: 3,   f: 0.5, kind: 'plant' },
  zitrone:     { n: 'Zitrone',              kcal: 29,  c: 9,   p: 1.1, f: 0.3, kind: 'plant' },
  limette:     { n: 'Limette',              kcal: 30,  c: 11,  p: 0.7, f: 0.2, kind: 'plant' },

  // ---------- Nüsse, Kerne, Fette, Süßes ----------
  olivenoel:   { n: 'Olivenöl',             kcal: 884, c: 0,   p: 0,   f: 100, kind: 'plant' },
  rapsoel:     { n: 'Rapsöl',               kcal: 884, c: 0,   p: 0,   f: 100, kind: 'plant' },
  sesamoel:    { n: 'Sesamöl',              kcal: 884, c: 0,   p: 0,   f: 100, kind: 'plant' },
  mandeln:     { n: 'Mandeln',              kcal: 579, c: 22,  p: 21,  f: 49,  kind: 'plant', pri: 1 },
  walnuesse:   { n: 'Walnüsse',             kcal: 654, c: 14,  p: 15,  f: 65,  kind: 'plant', pri: 1 },
  haselnuesse: { n: 'Haselnüsse',           kcal: 628, c: 17,  p: 15,  f: 61,  kind: 'plant', pri: 1 },
  cashews:     { n: 'Cashewkerne',          kcal: 553, c: 30,  p: 18,  f: 44,  kind: 'plant', pri: 1 },
  erdnuesse:   { n: 'Erdnüsse',             kcal: 567, c: 16,  p: 26,  f: 49,  kind: 'plant' },
  erdnussbutter:{ n:'Erdnussbutter',        kcal: 588, c: 20,  p: 25,  f: 50,  kind: 'plant' },
  mandelmus:   { n: 'Mandelmus',            kcal: 614, c: 19,  p: 21,  f: 56,  kind: 'plant', pri: 1 },
  chiasamen:   { n: 'Chiasamen',            kcal: 486, c: 42,  p: 17,  f: 31,  kind: 'plant' },
  leinsamen:   { n: 'Leinsamen',            kcal: 534, c: 29,  p: 18,  f: 42,  kind: 'plant' },
  sonnenblumenkerne:{ n:'Sonnenblumenkerne',kcal: 584, c: 20,  p: 21,  f: 51,  kind: 'plant' },
  kuerbiskerne:{ n: 'Kürbiskerne',          kcal: 559, c: 15,  p: 30,  f: 49,  kind: 'plant' },
  sesam:       { n: 'Sesam',                kcal: 573, c: 23,  p: 18,  f: 50,  kind: 'plant' },
  pinienkerne: { n: 'Pinienkerne',          kcal: 673, c: 13,  p: 14,  f: 68,  kind: 'plant', pri: 1 },
  kokosraspel: { n: 'Kokosraspel',          kcal: 660, c: 23,  p: 7,   f: 62,  kind: 'plant' },
  honig:       { n: 'Honig',                kcal: 304, c: 82,  p: 0.3, f: 0,   kind: 'honey' },
  ahornsirup:  { n: 'Ahornsirup',           kcal: 260, c: 67,  p: 0,   f: 0.1, kind: 'plant' },
  agavendicksaft:{ n:'Agavendicksaft',      kcal: 310, c: 76,  p: 0,   f: 0,   kind: 'plant' },
  zucker:      { n: 'Zucker',               kcal: 405, c: 100, p: 0,   f: 0,   kind: 'plant' },
  zartbitter:  { n: 'Zartbitterschokolade', kcal: 546, c: 46,  p: 7,   f: 31,  kind: 'plant' },
  kakao:       { n: 'Backkakao',            kcal: 343, c: 11,  p: 20,  f: 21,  kind: 'plant' },
  proteinpulver:{ n:'Proteinpulver (Whey)', kcal: 380, c: 8,   p: 75,  f: 5,   kind: 'dairy', pri: 1 },
  granola:     { n: 'Granola',              kcal: 471, c: 64,  p: 10,  f: 20,  kind: 'plant', glu: 1 },
  cornflakes:  { n: 'Cornflakes',           kcal: 357, c: 84,  p: 7,   f: 0.9, kind: 'plant' },
  muesli:      { n: 'Müsli',                kcal: 367, c: 60,  p: 10,  f: 8,   kind: 'plant', glu: 1 },

  // ---------- Saucen, Basics, Gewürze ----------
  kokosmilch:  { n: 'Kokosmilch',           kcal: 230, c: 6,   p: 2.3, f: 24,  kind: 'plant' },
  sojasauce:   { n: 'Sojasauce',            kcal: 60,  c: 5,   p: 8,   f: 0,   kind: 'plant', glu: 1 },
  currypaste:  { n: 'rote Currypaste',      kcal: 90,  c: 10,  p: 2,   f: 4,   kind: 'plant' },
  currypulver: { n: 'Currypulver',          kcal: 325, c: 56,  p: 14,  f: 14,  kind: 'plant', spice: 1 },
  pesto:       { n: 'Pesto',                kcal: 450, c: 6,   p: 5,   f: 44,  kind: 'dairy', pri: 1 },
  hummus:      { n: 'Hummus',               kcal: 177, c: 20,  p: 5,   f: 10,  kind: 'plant' },
  senf:        { n: 'Senf',                 kcal: 100, c: 6,   p: 6,   f: 6,   kind: 'plant' },
  ketchup:     { n: 'Ketchup',              kcal: 112, c: 26,  p: 1.2, f: 0.1, kind: 'plant' },
  mayo:        { n: 'Mayonnaise',           kcal: 680, c: 1,   p: 1,   f: 75,  kind: 'egg' },
  balsamico:   { n: 'Balsamico',            kcal: 88,  c: 17,  p: 0.5, f: 0,   kind: 'plant' },
  bruehe:      { n: 'Gemüsebrühe',          kcal: 4,   c: 0.6, p: 0.2, f: 0.1, kind: 'plant' },
  gemuesebruehe:{ n:'Gemüsebrühe',          kcal: 4,   c: 0.6, p: 0.2, f: 0.1, kind: 'plant' },
  mehl:        { n: 'Mehl',                 kcal: 348, c: 72,  p: 10,  f: 1,   kind: 'plant', glu: 1 },
  semmelbroesel:{ n:'Semmelbrösel',         kcal: 350, c: 70,  p: 11,  f: 4,   kind: 'plant', glu: 1 },
  backpulver:  { n: 'Backpulver',           kcal: 90,  c: 22,  p: 0,   f: 0,   kind: 'plant', spice: 1 },
  vanille:     { n: 'Vanille',              kcal: 288, c: 13,  p: 0.1, f: 0.1, kind: 'plant', spice: 1 },
  zimt:        { n: 'Zimt',                 kcal: 247, c: 81,  p: 4,   f: 1.2, kind: 'plant', spice: 1 },
  salz:        { n: 'Salz',                 kcal: 0,   c: 0,   p: 0,   f: 0,   kind: 'plant', spice: 1 },
  pfeffer:     { n: 'Pfeffer',              kcal: 251, c: 64,  p: 10,  f: 3,   kind: 'plant', spice: 1 },
  paprikapulver:{ n:'Paprikapulver',        kcal: 282, c: 54,  p: 14,  f: 13,  kind: 'plant', spice: 1 },
  fajitagewuerz:{ n:'Fajitagewürz',         kcal: 300, c: 50,  p: 11,  f: 10,  kind: 'plant', spice: 1 },
  kreuzkuemmel:{ n: 'Kreuzkümmel',          kcal: 375, c: 44,  p: 18,  f: 22,  kind: 'plant', spice: 1 },
  oregano:     { n: 'Oregano',              kcal: 265, c: 69,  p: 9,   f: 4,   kind: 'plant', spice: 1 },
  basilikum:   { n: 'Basilikum',            kcal: 23,  c: 2.7, p: 3.2, f: 0.6, kind: 'plant', spice: 1 },
  petersilie:  { n: 'Petersilie',           kcal: 36,  c: 6,   p: 3,   f: 0.8, kind: 'plant', spice: 1 },
  schnittlauch:{ n: 'Schnittlauch',         kcal: 30,  c: 4,   p: 3.3, f: 0.7, kind: 'plant', spice: 1 },
  dill:        { n: 'Dill',                 kcal: 43,  c: 7,   p: 3.5, f: 1.1, kind: 'plant', spice: 1 },
  koriander:   { n: 'Koriander',            kcal: 23,  c: 3.7, p: 2.1, f: 0.5, kind: 'plant', spice: 1 },
  thymian:     { n: 'Thymian',              kcal: 101, c: 24,  p: 6,   f: 1.7, kind: 'plant', spice: 1 },
  rosmarin:    { n: 'Rosmarin',             kcal: 131, c: 21,  p: 3.3, f: 6,   kind: 'plant', spice: 1 },
  currywurst_gewuerz:{ n:'Currygewürz',     kcal: 325, c: 56,  p: 14,  f: 14,  kind: 'plant', spice: 1 },
  kurkuma:     { n: 'Kurkuma',              kcal: 312, c: 67,  p: 10,  f: 3,   kind: 'plant', spice: 1 },
  griess:      { n: 'Weichweizengrieß',     kcal: 348, c: 73,  p: 10,  f: 1,   kind: 'plant', glu: 1 },
  garam_masala:{ n: 'Garam Masala',         kcal: 325, c: 45,  p: 14,  f: 15,  kind: 'plant', spice: 1 },
  currypul:    { n: 'Currypulver',          kcal: 325, c: 56,  p: 14,  f: 14,  kind: 'plant', spice: 1 },
  chiliflocken:{ n: 'Chiliflocken',         kcal: 282, c: 57,  p: 12,  f: 14,  kind: 'plant', spice: 1 },
  muskat:      { n: 'Muskatnuss',           kcal: 525, c: 49,  p: 6,   f: 36,  kind: 'plant', spice: 1 },
  lorbeer:     { n: 'Lorbeerblatt',         kcal: 313, c: 75,  p: 8,   f: 8,   kind: 'plant', spice: 1 },
  essig:       { n: 'Weißweinessig',        kcal: 19,  c: 0.6, p: 0,   f: 0,   kind: 'plant', spice: 1 },
  weisswein:   { n: 'Weißwein',             kcal: 82,  c: 2.6, p: 0.1, f: 0,   kind: 'plant' },
  worcester:   { n: 'Worcestersauce',       kcal: 78,  c: 19,  p: 0,   f: 0,   kind: 'plant', spice: 1 },
  ahorn:       { n: 'Ahornsirup',           kcal: 260, c: 67,  p: 0,   f: 0.1, kind: 'plant' },
  kokosjoghurt:{ n: 'Kokosjoghurt',         kcal: 97,  c: 3,   p: 1,   f: 9,   kind: 'plant' },
  sojajoghurt: { n: 'Sojajoghurt',          kcal: 50,  c: 2,   p: 4,   f: 2.5, kind: 'plant' },
  hafermilch:  { n: 'Hafermilch',           kcal: 45,  c: 7,   p: 0.8, f: 1.5, kind: 'plant' },
  sojamilch:   { n: 'Sojadrink',            kcal: 33,  c: 1,   p: 3.3, f: 1.8, kind: 'plant' },
  mandelmilch: { n: 'Mandeldrink',          kcal: 24,  c: 3,   p: 0.5, f: 1.1, kind: 'plant' },
  minze:       { n: 'Minze',                kcal: 44,  c: 8,   p: 3.3, f: 0.7, kind: 'plant', spice: 1 },
  kraeuter:    { n: 'Kräuter der Provence', kcal: 259, c: 64,  p: 11,  f: 7,   kind: 'plant', spice: 1 },
  kokosmilch_light:{ n:'Kokosmilch light',  kcal: 73,  c: 3,   p: 1,   f: 6,   kind: 'plant' },
  ajvar:       { n: 'Ajvar',                kcal: 90,  c: 10,  p: 1.5, f: 5,   kind: 'plant' },
  kapern:      { n: 'Kapern',               kcal: 23,  c: 5,   p: 2.4, f: 0.9, kind: 'plant', spice: 1 },
  gewuerzgurke:{ n: 'Gewürzgurke',          kcal: 11,  c: 2,   p: 0.5, f: 0.2, kind: 'plant' },
  schafskaese: { n: 'Schafskäse',           kcal: 264, c: 4,   p: 14,  f: 21,  kind: 'dairy', pri: 1 },
  cremecheese_light:{ n:'Frischkäse light', kcal: 145, c: 4,   p: 8,   f: 10,  kind: 'dairy' },
  roestzwiebel:{ n: 'Röstzwiebeln',         kcal: 480, c: 45,  p: 7,   f: 30,  kind: 'plant' },
  spaetzle:    { n: 'Spätzle',              kcal: 158, c: 27,  p: 6,   f: 3,   kind: 'plant', glu: 1 },
  lasagneplatten:{ n:'Lasagneplatten',      kcal: 352, c: 71,  p: 12,  f: 2,   kind: 'plant', glu: 1 },
  bechamel:    { n: 'Béchamelsauce',        kcal: 130, c: 9,   p: 3,   f: 9,   kind: 'dairy', glu: 1 },
  sauerkraut:  { n: 'Sauerkraut',           kcal: 19,  c: 4,   p: 1,   f: 0.1, kind: 'plant' },
  rotkohl_glas:{ n: 'Apfelrotkohl',         kcal: 65,  c: 14,  p: 0.8, f: 0.3, kind: 'plant' },
  kloesse:     { n: 'Kartoffelklöße',       kcal: 154, c: 34,  p: 2,   f: 0.5, kind: 'plant' },
  semmelknoedel:{ n:'Semmelknödel',         kcal: 180, c: 28,  p: 6,   f: 4,   kind: 'plant', glu: 1 },
  maultaschen: { n: 'Maultaschen',          kcal: 215, c: 24,  p: 10,  f: 8,   kind: 'plant', glu: 1 },
  hirse:       { n: 'Hirse (roh)',          kcal: 354, c: 69,  p: 11,  f: 4,   kind: 'plant' },
  backerbsen:  { n: 'Backerbsen',           kcal: 420, c: 60,  p: 10,  f: 15,  kind: 'plant', glu: 1 },
  reisnudeln:  { n: 'Reisnudeln (gekocht)', kcal: 108, c: 25,  p: 2,   f: 0.2, kind: 'plant' },
  glasnudeln:  { n: 'Glasnudeln (gekocht)', kcal: 90,  c: 22,  p: 0.1, f: 0,   kind: 'plant' },
  naanbrot:    { n: 'Naan',                 kcal: 310, c: 50,  p: 9,   f: 8,   kind: 'plant', glu: 1 },
  tortillachips:{ n:'Tortillachips',        kcal: 490, c: 62,  p: 7,   f: 24,  kind: 'plant' },
  guacamole:   { n: 'Guacamole',            kcal: 150, c: 8,   p: 2,   f: 13,  kind: 'plant' },
  kichererbsenmehl:{ n:'Kichererbsenmehl',  kcal: 387, c: 58,  p: 22,  f: 7,   kind: 'plant' },
  zuckerschoten:{ n:'Zuckerschoten',        kcal: 42,  c: 7,   p: 3,   f: 0.2, kind: 'plant' },
  kokoschips:  { n: 'Kokoschips',           kcal: 660, c: 23,  p: 7,   f: 62,  kind: 'plant' },
  tomatenpaprikasauce:{ n:'Paprika-Tomaten-Sauce', kcal:50, c:8, p:1.5, f:1.5, kind:'plant' },
  räuchertofu: { n: 'Räuchertofu',          kcal: 176, c: 1,   p: 18,  f: 11,  kind: 'plant' },
  bohnenkraut: { n: 'Bohnenkraut',          kcal: 272, c: 45,  p: 10,  f: 6,   kind: 'plant', spice: 1 },
  pak_choi:    { n: 'Pak Choi',             kcal: 13,  c: 2.2, p: 1.5, f: 0.2, kind: 'plant' },
  granatapfel: { n: 'Granatapfelkerne',     kcal: 83,  c: 19,  p: 1.7, f: 1.2, kind: 'plant', pri: 1 },
  schafsjoghurt:{ n:'Schafsjoghurt',        kcal: 92,  c: 5,   p: 5,   f: 6,   kind: 'dairy' },
  quinoaflocken:{ n:'Quinoaflocken',        kcal: 370, c: 62,  p: 13,  f: 6,   kind: 'plant' },
  dinkelmehl:  { n: 'Dinkelmehl',           kcal: 340, c: 70,  p: 12,  f: 2,   kind: 'plant', glu: 1 },
  brezel:      { n: 'Laugenbrezel',         kcal: 320, c: 62,  p: 10,  f: 3,   kind: 'plant', glu: 1 },
  leberkaese:  { n: 'Leberkäse',            kcal: 280, c: 1,   p: 13,  f: 25,  kind: 'meat' },
  wiener:      { n: 'Wiener Würstchen',     kcal: 270, c: 1,   p: 12,  f: 24,  kind: 'meat' },
  tahin:       { n: 'Tahin (Sesampaste)',   kcal: 595, c: 21,  p: 17,  f: 54,  kind: 'plant' },
  burgerbun:   { n: 'Burger-Bun',           kcal: 270, c: 47,  p: 9,   f: 5,   kind: 'plant', glu: 1 },
  pizzateig:   { n: 'Pizzateig',            kcal: 265, c: 49,  p: 8,   f: 4,   kind: 'plant', glu: 1 },
  bbqsauce:    { n: 'BBQ-Sauce',            kcal: 172, c: 40,  p: 0.8, f: 0.5, kind: 'plant' },
  cheddar:     { n: 'Cheddar',              kcal: 402, c: 1.3, p: 25,  f: 33,  kind: 'dairy' },
  jalapeno:    { n: 'Jalapeños',            kcal: 29,  c: 6,   p: 0.9, f: 0.4, kind: 'plant' },
  rindsteakhack:{ n:'Rinderpatty',          kcal: 250, c: 0,   p: 26,  f: 17,  kind: 'meat' },
  pommes_suess:{ n: 'Süßkartoffelpommes',   kcal: 150, c: 24,  p: 2,   f: 5,   kind: 'plant' },
  schafskaese2:{ n: 'Hirtenkäse',           kcal: 264, c: 4,   p: 14,  f: 21,  kind: 'dairy', pri: 1 },
  salbei:      { n: 'Salbei',               kcal: 315, c: 61,  p: 11,  f: 13,  kind: 'plant', spice: 1 },
  garnelen_gross:{ n:'Riesengarnelen',      kcal: 99,  c: 0,   p: 24,  f: 0.3, kind: 'fish', pri: 1 },
  muscheln:    { n: 'Miesmuscheln',         kcal: 86,  c: 4,   p: 12,  f: 2,   kind: 'fish', pri: 1 },
  surimi:      { n: 'Surimi',               kcal: 99,  c: 9,   p: 8,   f: 1,   kind: 'fish' },
  matjes:      { n: 'Matjes',               kcal: 200, c: 0,   p: 17,  f: 15,  kind: 'fish' },

  // ---------- Erweiterung: Weltküchen ----------
  // Fleisch & Geflügel
  lammfilet:   { n: 'Lammfilet',            kcal: 201, c: 0,   p: 25,  f: 11,  kind: 'meat', pri: 1 },
  lammhack:    { n: 'Lammhackfleisch',      kcal: 234, c: 0,   p: 25,  f: 15,  kind: 'meat', pri: 1 },
  ente:        { n: 'Entenbrust',           kcal: 201, c: 0,   p: 24,  f: 11,  kind: 'meat', pri: 1 },
  kalb:        { n: 'Kalbsschnitzel',       kcal: 172, c: 0,   p: 31,  f: 5,   kind: 'meat', pri: 1 },
  serrano:     { n: 'Serrano-Schinken',     kcal: 241, c: 0.3, p: 31,  f: 13,  kind: 'meat', pri: 1 },
  haehnchenschenkel2:{ n:'Hähnchenoberkeule', kcal: 209, c: 0, p: 26, f: 11, kind: 'meat' },
  // Fisch & Meeresfrüchte
  calamari:    { n: 'Calamari',             kcal: 92,  c: 3,   p: 16,  f: 1.4, kind: 'fish', pri: 1 },
  wolfsbarsch: { n: 'Wolfsbarsch',          kcal: 97,  c: 0,   p: 18,  f: 2.5, kind: 'fish', pri: 1 },
  makrele:     { n: 'Makrele',              kcal: 205, c: 0,   p: 19,  f: 14,  kind: 'fish' },
  jakobsmuscheln:{ n:'Jakobsmuscheln',      kcal: 88,  c: 2,   p: 17,  f: 0.8, kind: 'fish', pri: 1 },
  // Käse & Milch
  paneer:      { n: 'Paneer',               kcal: 265, c: 4,   p: 18,  f: 20,  kind: 'dairy' },
  manchego:    { n: 'Manchego',             kcal: 393, c: 0,   p: 25,  f: 32,  kind: 'dairy', pri: 1 },
  ziegenkaese: { n: 'Ziegenkäse',           kcal: 364, c: 2,   p: 22,  f: 30,  kind: 'dairy', pri: 1 },
  bergkaese:   { n: 'Bergkäse',             kcal: 400, c: 0,   p: 29,  f: 31,  kind: 'dairy' },
  burrata:     { n: 'Burrata',              kcal: 280, c: 3,   p: 15,  f: 24,  kind: 'dairy', pri: 1 },
  ghee:        { n: 'Ghee',                 kcal: 900, c: 0,   p: 0,   f: 100, kind: 'dairy' },
  // Pflanzlich & Hülsenfrüchte
  paneer_tofu: { n: 'fester Tofu',          kcal: 144, c: 3,   p: 15,  f: 9,   kind: 'plant' },
  belugalinsen:{ n: 'Belugalinsen (gekocht)', kcal: 116, c: 20, p: 9,  f: 0.4, kind: 'plant' },
  jackfruit:   { n: 'Jackfruit',            kcal: 95,  c: 23,  p: 1.7, f: 0.6, kind: 'plant' },
  kimchi:      { n: 'Kimchi',               kcal: 34,  c: 6,   p: 1.6, f: 0.5, kind: 'plant' },
  nori:        { n: 'Nori',                 kcal: 35,  c: 5,   p: 6,   f: 0.3, kind: 'plant' },
  // Getreide & Basis
  panko:       { n: 'Panko',                kcal: 380, c: 78,  p: 12,  f: 3,   kind: 'plant', glu: 1 },
  filoteig:    { n: 'Filoteig',             kcal: 290, c: 55,  p: 8,   f: 4,   kind: 'plant', glu: 1 },
  gyozateig:   { n: 'Gyoza-Teigblätter',    kcal: 280, c: 56,  p: 8,   f: 2,   kind: 'plant', glu: 1 },
  blaetterteig:{ n: 'Blätterteig',          kcal: 380, c: 36,  p: 6,   f: 24,  kind: 'plant', glu: 1 },
  weinblaetter:{ n: 'Weinblätter',          kcal: 69,  c: 9,   p: 4,   f: 1,   kind: 'plant' },
  reispapier:  { n: 'Reispapier',           kcal: 330, c: 82,  p: 1,   f: 0.2, kind: 'plant' },
  udon:        { n: 'Udon-Nudeln (gekocht)', kcal: 130, c: 27, p: 5,  f: 0.5, kind: 'plant', glu: 1 },
  sushireis:   { n: 'Sushireis (gekocht)',  kcal: 140, c: 30,  p: 2.7, f: 0.3, kind: 'plant' },
  tortilla_mais:{ n:'Maistortilla',         kcal: 218, c: 45,  p: 6,   f: 3,   kind: 'plant' },
  // Gemüse & Obst
  okra:        { n: 'Okra',                 kcal: 33,  c: 7,   p: 1.9, f: 0.2, kind: 'plant' },
  pak_choi2:   { n: 'Baby-Pak-Choi',        kcal: 13,  c: 2.2, p: 1.5, f: 0.2, kind: 'plant' },
  mangold:     { n: 'Mangold',              kcal: 19,  c: 3.7, p: 1.8, f: 0.2, kind: 'plant' },
  sellerieknolle:{ n:'Knollensellerie',     kcal: 42,  c: 9,   p: 1.5, f: 0.3, kind: 'plant' },
  pastinake:   { n: 'Pastinake',            kcal: 75,  c: 18,  p: 1.2, f: 0.3, kind: 'plant' },
  romanesco:   { n: 'Romanesco',            kcal: 25,  c: 5,   p: 1.9, f: 0.3, kind: 'plant' },
  radieschen:  { n: 'Radieschen',           kcal: 16,  c: 3.4, p: 0.7, f: 0.1, kind: 'plant' },
  koriandergruen:{ n:'frischer Koriander',  kcal: 23,  c: 3.7, p: 2.1, f: 0.5, kind: 'plant', spice: 1 },
  granatapfel2:{ n: 'Granatapfel',          kcal: 83,  c: 19,  p: 1.7, f: 1.2, kind: 'plant', pri: 1 },
  feige:       { n: 'Feige',                kcal: 74,  c: 19,  p: 0.8, f: 0.3, kind: 'plant', pri: 1 },
  aprikose:    { n: 'Aprikose',             kcal: 48,  c: 11,  p: 1.4, f: 0.4, kind: 'plant' },
  // Saucen, Pasten, Gewürze
  gochujang:   { n: 'Gochujang',            kcal: 210, c: 40,  p: 6,   f: 3,   kind: 'plant' },
  miso:        { n: 'Miso-Paste',           kcal: 199, c: 26,  p: 12,  f: 6,   kind: 'plant' },
  fischsauce:  { n: 'Fischsauce',           kcal: 35,  c: 4,   p: 5,   f: 0,   kind: 'fish' },
  hoisin:      { n: 'Hoisinsauce',          kcal: 220, c: 44,  p: 3,   f: 3,   kind: 'plant' },
  harissa:     { n: 'Harissa',              kcal: 70,  c: 9,   p: 3,   f: 3,   kind: 'plant' },
  tandoori:    { n: 'Tandoori-Paste',       kcal: 90,  c: 12,  p: 2,   f: 3,   kind: 'plant' },
  mangochutney:{ n: 'Mango-Chutney',        kcal: 190, c: 46,  p: 0.5, f: 0.2, kind: 'plant' },
  teriyakisauce:{ n:'Teriyakisauce',        kcal: 89,  c: 16,  p: 5,   f: 0,   kind: 'plant', glu: 1 },
  sriracha:    { n: 'Sriracha',             kcal: 93,  c: 19,  p: 2,   f: 1,   kind: 'plant' },
  ajvar2:      { n: 'Ajvar',                kcal: 90,  c: 10,  p: 1.5, f: 5,   kind: 'plant' },
  zatar:       { n: 'Za’atar',              kcal: 320, c: 40,  p: 11,  f: 13,  kind: 'plant', spice: 1 },
  sumach:      { n: 'Sumach',               kcal: 320, c: 60,  p: 10,  f: 10,  kind: 'plant', spice: 1 },
  raselhanout: { n: 'Ras el Hanout',        kcal: 330, c: 50,  p: 13,  f: 13,  kind: 'plant', spice: 1 },
  kardamom:    { n: 'Kardamom',             kcal: 311, c: 68,  p: 11,  f: 7,   kind: 'plant', spice: 1 },
  kurkuma2:    { n: 'Kurkuma',              kcal: 312, c: 67,  p: 10,  f: 3,   kind: 'plant', spice: 1 },
  safran:      { n: 'Safran',               kcal: 310, c: 65,  p: 11,  f: 6,   kind: 'plant', spice: 1, pri: 1 },
  wasabipaste: { n: 'Wasabi',               kcal: 292, c: 63,  p: 7,   f: 2,   kind: 'plant', spice: 1 },
  dukkah:      { n: 'Dukkah',               kcal: 560, c: 20,  p: 17,  f: 47,  kind: 'plant', spice: 1 },

  // ---------- Erweiterung 2: weitere Küchen ----------
  kochbanane:  { n: 'Kochbanane',           kcal: 122, c: 32,  p: 1.3, f: 0.4, kind: 'plant' },
  schwarzaugenbohnen:{ n:'Schwarzaugenbohnen (gekocht)', kcal:116, c:20, p:8, f:0.5, kind:'plant' },
  berberitzen: { n: 'Berberitzen',          kcal: 290, c: 64,  p: 4,   f: 1,   kind: 'plant', pri: 1 },
  kasseler:    { n: 'Kasseler',             kcal: 155, c: 0.5, p: 21,  f: 8,   kind: 'meat' },
  raeucherspeck:{ n:'Räucherspeck',         kcal: 400, c: 0,   p: 12,  f: 39,  kind: 'meat' },
  mettwurst:   { n: 'Mettwurst',            kcal: 350, c: 1,   p: 15,  f: 32,  kind: 'meat' },
  pecorino:    { n: 'Pecorino',             kcal: 387, c: 0,   p: 26,  f: 32,  kind: 'dairy', pri: 1 },
  buttermilch: { n: 'Buttermilch',          kcal: 37,  c: 4,   p: 3.5, f: 0.5, kind: 'dairy' },
  jerkgewuerz: { n: 'Jerk-Gewürz',          kcal: 320, c: 55,  p: 11,  f: 8,   kind: 'plant', spice: 1 },
  berbere:     { n: 'Berbere-Gewürz',       kcal: 320, c: 50,  p: 13,  f: 12,  kind: 'plant', spice: 1 },
  piment:      { n: 'Piment',               kcal: 263, c: 72,  p: 6,   f: 9,   kind: 'plant', spice: 1 },
  pilipili:    { n: 'Piri-Piri-Sauce',      kcal: 60,  c: 8,   p: 1,   f: 3,   kind: 'plant' },
  cornmeal:    { n: 'Maisgrieß',            kcal: 362, c: 76,  p: 8,   f: 3.5, kind: 'plant' },
  maniok:      { n: 'Maniok (gekocht)',     kcal: 130, c: 32,  p: 1,   f: 0.3, kind: 'plant' },
  kokoswasser: { n: 'Kokoswasser',          kcal: 19,  c: 4,   p: 0.7, f: 0.2, kind: 'plant' },
  dickmilch:   { n: 'Dickmilch',            kcal: 62,  c: 4,   p: 3.3, f: 3.5, kind: 'dairy' },
  raeucherforelle:{ n:'Räucherforelle',     kcal: 138, c: 0,   p: 21,  f: 6,   kind: 'fish', pri: 1 },
  lachsforelle:{ n: 'Lachsforelle',         kcal: 150, c: 0,   p: 20,  f: 8,   kind: 'fish', pri: 1 },
  preiselbeeren:{ n:'Preiselbeeren',        kcal: 200, c: 49,  p: 0.2, f: 0.2, kind: 'plant' },

  // ---------- Erweiterung 3: weitere Küchen ----------
  pancetta:    { n: 'Pancetta',             kcal: 458, c: 0,   p: 12,  f: 45,  kind: 'meat', pri: 1 },
  nduja:       { n: "'Nduja",               kcal: 450, c: 1,   p: 14,  f: 43,  kind: 'meat', pri: 1 },
  rinderbrust: { n: 'Rinderbrust',          kcal: 210, c: 0,   p: 24,  f: 13,  kind: 'meat' },
  haehnchenleber:{ n:'Hähnchenleber',       kcal: 119, c: 0.7, p: 17,  f: 5,   kind: 'meat' },
  sambal:      { n: 'Sambal Oelek',         kcal: 40,  c: 6,   p: 1.5, f: 1,   kind: 'plant', spice: 1 },
  kecapmanis:  { n: 'Kecap Manis',          kcal: 220, c: 50,  p: 4,   f: 0,   kind: 'plant' },
  tamarinde:   { n: 'Tamarindenpaste',      kcal: 239, c: 63,  p: 2.8, f: 0.6, kind: 'plant' },
  zitronengras:{ n: 'Zitronengras',         kcal: 99,  c: 25,  p: 1.8, f: 0.5, kind: 'plant', spice: 1 },
  buchweizen:  { n: 'Buchweizen (gekocht)', kcal: 92,  c: 20,  p: 3.4, f: 0.6, kind: 'plant' },
  aji:         { n: 'Aji-Amarillo-Paste',   kcal: 55,  c: 9,   p: 1.5, f: 1.5, kind: 'plant', spice: 1 },
  erdnussoel:  { n: 'Erdnussöl',            kcal: 884, c: 0,   p: 0,   f: 100, kind: 'plant' },
  leinoel:     { n: 'Leinöl',               kcal: 884, c: 0,   p: 0,   f: 100, kind: 'plant' },
  austernsauce:{ n: 'Austernsauce',         kcal: 51,  c: 11,  p: 1.4, f: 0.3, kind: 'plant', glu: 1 },
  kondensmilch:{ n: 'Kondensmilch',         kcal: 135, c: 10,  p: 7,   f: 8,   kind: 'dairy' },
  wachtelei:   { n: 'Wachtelei',            kcal: 158, c: 0.4, p: 13,  f: 11,  kind: 'egg' },
  austernpilze:{ n: 'Austernpilze',         kcal: 33,  c: 6,   p: 3.3, f: 0.4, kind: 'plant' },
  wirsing:     { n: 'Wirsing',              kcal: 27,  c: 6,   p: 2,   f: 0.4, kind: 'plant' },
  steckrübe:   { n: 'Steckrübe',            kcal: 38,  c: 9,   p: 1.1, f: 0.2, kind: 'plant' },
  physalis:    { n: 'Physalis',             kcal: 53,  c: 11,  p: 1.9, f: 0.7, kind: 'plant', pri: 1 },
  hefeflocken: { n: 'Hefeflocken',          kcal: 350, c: 35,  p: 45,  f: 5,   kind: 'plant' },

  // ---------- Erweiterung 4: weitere Küchen ----------
  curryblaetter:{ n:'Curryblätter',         kcal: 108, c: 19,  p: 6,   f: 1,   kind: 'plant', spice: 1 },
  senfsamen:   { n: 'Senfsamen',            kcal: 508, c: 28,  p: 26,  f: 36,  kind: 'plant', spice: 1 },
  cajungewuerz:{ n: 'Cajun-Gewürz',         kcal: 300, c: 50,  p: 12,  f: 8,   kind: 'plant', spice: 1 },
  kaffir:      { n: 'Kaffirlimettenblatt',  kcal: 90,  c: 20,  p: 3,   f: 1,   kind: 'plant', spice: 1 },
  bockshornklee:{ n:'Bockshornklee',        kcal: 323, c: 58,  p: 23,  f: 6,   kind: 'plant', spice: 1 },
  pistazien:   { n: 'Pistazien',            kcal: 562, c: 28,  p: 20,  f: 45,  kind: 'plant', pri: 1 },
  palmoel:     { n: 'Palmöl',               kcal: 884, c: 0,   p: 0,   f: 100, kind: 'plant' },
  urad:        { n: 'Urad Dal (gekocht)',   kcal: 120, c: 21,  p: 9,   f: 0.5, kind: 'plant' },
  yamswurzel:  { n: 'Yamswurzel (gekocht)', kcal: 118, c: 28,  p: 1.5, f: 0.2, kind: 'plant' },
  wassermelone:{ n: 'Wassermelone',         kcal: 30,  c: 8,   p: 0.6, f: 0.2, kind: 'plant' },
  granatapfelsirup:{ n:'Granatapfelsirup',  kcal: 265, c: 65,  p: 0.5, f: 0,   kind: 'plant' },
  rosinen2:    { n: 'Sultaninen',           kcal: 299, c: 79,  p: 3,   f: 0.5, kind: 'plant' },

  // ---------- Erweiterung 5: Fisch, Fleisch, Sonstiges ----------
  scholle:     { n: 'Scholle',              kcal: 86,  c: 0,   p: 17,  f: 1.5, kind: 'fish', pri: 1 },
  zander:      { n: 'Zander',               kcal: 84,  c: 0,   p: 19,  f: 0.7, kind: 'fish', pri: 1 },
  rotbarsch:   { n: 'Rotbarsch',            kcal: 105, c: 0,   p: 18,  f: 3.6, kind: 'fish' },
  dorade:      { n: 'Dorade',               kcal: 96,  c: 0,   p: 20,  f: 1.8, kind: 'fish', pri: 1 },
  spareribs:   { n: 'Spareribs',            kcal: 277, c: 0,   p: 20,  f: 22,  kind: 'meat' },
  haehnchenfluegel:{ n:'Hähnchenflügel',    kcal: 203, c: 0,   p: 19,  f: 14,  kind: 'meat' },
  lachswuerfel:{ n: 'Lachswürfel',          kcal: 208, c: 0,   p: 20,  f: 13,  kind: 'fish', pri: 1 },
  hering_matjes:{ n:'Brathering',           kcal: 190, c: 3,   p: 15,  f: 12,  kind: 'fish' },
  tofu_seiden: { n: 'Seidentofu',           kcal: 55,  c: 2,   p: 6,   f: 3,   kind: 'plant' },
  kokosjoghurt2:{ n:'Kokosjoghurt',         kcal: 97,  c: 3,   p: 1,   f: 9,   kind: 'plant' },
  apfelmus:    { n: 'Apfelmus',             kcal: 62,  c: 15,  p: 0.2, f: 0.1, kind: 'plant' },
  senfsauce:   { n: 'Dijon-Senf',           kcal: 100, c: 6,   p: 6,   f: 6,   kind: 'plant' },

  // ---------- Erweiterung 6: Wok, Gemüse, Sonstiges ----------
  bambus:      { n: 'Bambussprossen',       kcal: 18,  c: 3,   p: 1.8, f: 0.2, kind: 'plant' },
  sojasprossen:{ n: 'Sojasprossen',         kcal: 31,  c: 6,   p: 3,   f: 0.2, kind: 'plant' },
  babymais:    { n: 'Babymais',             kcal: 26,  c: 5,   p: 2,   f: 0.2, kind: 'plant' },
  wasserkastanie:{ n:'Wasserkastanien',     kcal: 97,  c: 24,  p: 1.4, f: 0.1, kind: 'plant' },
  mangold2:    { n: 'Mangold',              kcal: 19,  c: 3.7, p: 1.8, f: 0.2, kind: 'plant' },
  chinakohl:   { n: 'Chinakohl',            kcal: 16,  c: 3.2, p: 1.2, f: 0.2, kind: 'plant' },
  salamipiz:   { n: 'Salami',               kcal: 378, c: 1,   p: 21,  f: 32,  kind: 'meat', pri: 1 },
  schinkenwuerfel:{ n:'Schinkenwürfel',     kcal: 210, c: 1,   p: 18,  f: 15,  kind: 'meat' },
  artischocke: { n: 'Artischockenherzen',   kcal: 47,  c: 6,   p: 3,   f: 0.2, kind: 'plant' },
  rucola2:     { n: 'Rucola',               kcal: 25,  c: 3.7, p: 2.6, f: 0.7, kind: 'plant' },

  // ---------- Erweiterung 7: Schmoren & Gemüse ----------
  lammkeule:   { n: 'Lammkeule',            kcal: 217, c: 0,   p: 25,  f: 13,  kind: 'meat', pri: 1 },
  kaninchen:   { n: 'Kaninchen',            kcal: 173, c: 0,   p: 22,  f: 9,   kind: 'meat', pri: 1 },
  rinderroulade:{ n:'Rinderroulade',        kcal: 210, c: 0,   p: 24,  f: 13,  kind: 'meat' },
  schwarzwurzel:{ n:'Schwarzwurzel',        kcal: 82,  c: 17,  p: 1.4, f: 0.4, kind: 'plant' },
  topinambur:  { n: 'Topinambur',           kcal: 73,  c: 17,  p: 2,   f: 0.4, kind: 'plant' },
  mairuebchen: { n: 'Mairübchen',           kcal: 28,  c: 6,   p: 1,   f: 0.1, kind: 'plant' },
  cranberries: { n: 'Cranberries',          kcal: 308, c: 76,  p: 0.1, f: 1.4, kind: 'plant' },
  wildpilze:   { n: 'Waldpilze',            kcal: 26,  c: 3,   p: 3,   f: 0.4, kind: 'plant' },
  rotwein:     { n: 'Rotwein',              kcal: 85,  c: 2.6, p: 0.1, f: 0,   kind: 'plant' },
  kuemmel:     { n: 'Kümmel',               kcal: 375, c: 44,  p: 20,  f: 22,  kind: 'plant', spice: 1 },
  bier:        { n: 'Bier',                 kcal: 43,  c: 3.6, p: 0.5, f: 0,   kind: 'plant' },
  nachokaese:  { n: 'Nacho-Käsesauce',      kcal: 250, c: 8,   p: 6,   f: 21,  kind: 'dairy' },
};

module.exports = { P };
