// Snacks. Von Hand geschriebene echte Rezepte.
module.exports = [
{ n:'Apfel mit Erdnussbutter', m:'snack', t:3, ing:[['apfel',150],['erdnussbutter',20]], s:['Apfel in Spalten schneiden.','Erdnussbutter als Dip dazu reichen.'] },
{ n:'Banane mit Mandelmus', m:'snack', t:3, ing:[['banane',120],['mandelmus',20]], s:['Banane schälen und längs aufschneiden.','Mandelmus daraufstreichen.'] },
{ n:'Skyr mit Heidelbeeren', m:'snack', t:3, ing:[['skyr',150],['heidelbeeren',60],['honig',6]], s:['Skyr in eine Schale geben.','Mit Heidelbeeren und Honig toppen.'] },
{ n:'Magerquark mit Beeren', m:'snack', t:4, ing:[['magerquark',150],['erdbeeren',80],['honig',8]], s:['Quark cremig rühren.','Beeren unterheben und mit Honig süßen.'] },
{ n:'Handvoll Mandeln', m:'snack', t:1, ing:[['mandeln',30]], s:['Mandeln abwiegen und genießen.'] },
{ n:'Studentenfutter', m:'snack', t:1, ing:[['mandeln',15],['cashews',15],['rosinen',20]], s:['Nüsse und Rosinen mischen.'] },
{ n:'Griechischer Joghurt mit Walnüssen', m:'snack', t:3, ing:[['griechjoghurt',150],['walnuesse',15],['honig',8]], s:['Joghurt in eine Schale geben.','Mit gehackten Walnüssen und Honig toppen.'] },
{ n:'Gemüsesticks mit Hummus', m:'snack', t:6, ing:[['moehren',80],['gurke',80],['paprika',60],['hummus',50]], s:['Gemüse in Sticks schneiden.','Hummus als Dip dazu reichen.'] },
{ n:'Reiswaffeln mit Frischkäse', m:'snack', t:4, ing:[['reiswaffeln',20],['frischkaese',30],['gurke',40]], s:['Reiswaffeln mit Frischkäse bestreichen.','Mit Gurkenscheiben belegen.'] },
{ n:'Reiswaffeln mit Erdnussbutter und Banane', m:'snack', t:4, ing:[['reiswaffeln',20],['erdnussbutter',20],['banane',60]], s:['Reiswaffeln mit Erdnussbutter bestreichen.','Bananenscheiben darauflegen.'] },
{ n:'Hüttenkäse mit Tomaten', m:'snack', t:4, ing:[['huettenkaese',150],['cherrytomaten',80],['schnittlauch',4]], s:['Hüttenkäse in eine Schale geben.','Tomaten halbieren und untermischen, mit Schnittlauch bestreuen.'] },
{ n:'Proteinriegel-Quark', m:'snack', t:4, ing:[['magerquark',200],['proteinpulver',15],['himbeeren',60]], s:['Quark mit Proteinpulver cremig rühren.','Mit Himbeeren toppen.'] },
{ n:'Vollkornbrot mit Avocado', m:'snack', t:6, ing:[['vollkornbrot',50],['avocado',60],['zitrone',4],['salz',1]], s:['Avocado mit Zitrone und Salz zerdrücken.','Auf das Brot streichen.'] },
{ n:'Knäckebrot mit Käse', m:'snack', t:3, ing:[['knaeckebrot',30],['gouda',30]], s:['Knäckebrot mit Käsescheiben belegen.'] },
{ n:'Obstsalat', m:'snack', t:8, ing:[['apfel',80],['banane',80],['orange',80],['kiwi',60]], s:['Obst schälen und klein schneiden.','In einer Schale mischen.'] },
{ n:'Beeren-Nuss-Bowl', m:'snack', t:3, ing:[['heidelbeeren',80],['himbeeren',60],['mandeln',15]], s:['Beeren in eine Schale geben.','Mit gehackten Mandeln bestreuen.'] },
{ n:'Edamame mit Meersalz', m:'snack', t:8, ing:[['edamame',120],['salz',2]], s:['Edamame in Salzwasser 5 Minuten kochen.','Abgießen und mit Salz bestreuen.'] },
{ n:'Gekochtes Ei mit Salz', m:'snack', t:10, ing:[['ei',120],['salz',1]], s:['Eier 8 Minuten hart kochen.','Pellen und salzen.'] },
{ n:'Käsewürfel mit Weintrauben', m:'snack', t:4, ing:[['gouda',40],['weintrauben',100]], s:['Käse in Würfel schneiden.','Mit Weintrauben anrichten.'] },
{ n:'Datteln mit Mandeln', m:'snack', t:4, ing:[['datteln',40],['mandeln',20]], s:['Datteln entkernen.','Je eine Mandel hineinlegen.'] },
{ n:'Schoko-Bananen-Snack', m:'snack', t:3, ing:[['banane',120],['zartbitter',15]], s:['Banane in Scheiben schneiden.','Schokolade schmelzen und darüber träufeln.'] },
{ n:'Kürbiskerne geröstet', m:'snack', t:8, ing:[['kuerbiskerne',30],['salz',1]], s:['Kürbiskerne in einer Pfanne ohne Fett rösten, bis sie duften.','Leicht salzen.'] },
{ n:'Naturjoghurt mit Granola', m:'snack', t:3, ing:[['naturjoghurt',150],['granola',30]], s:['Joghurt in eine Schale geben.','Mit Granola bestreuen.'] },
{ n:'Möhren-Sticks mit Kräuterquark', m:'snack', t:6, ing:[['moehren',120],['magerquark',80],['schnittlauch',5],['salz',1]], s:['Quark mit Schnittlauch und Salz verrühren.','Möhren in Sticks schneiden und dippen.'] },
{ n:'Vollkorncracker mit Hummus', m:'snack', t:4, ing:[['knaeckebrot',30],['hummus',40],['paprika',40]], s:['Knäckebrot mit Hummus bestreichen.','Mit Paprikastreifen belegen.'] },
{ n:'Mozzarella-Tomaten-Spieße', m:'snack', t:6, ing:[['mozzarella',60],['cherrytomaten',80],['basilikum',3],['olivenoel',4]], s:['Mozzarella und Tomaten auf Spieße stecken.','Mit Basilikum und Öl beträufeln.'] },
{ n:'Apfel-Zimt-Quark', m:'snack', t:4, ing:[['magerquark',150],['apfel',100],['zimt',1]], s:['Apfel raspeln und unter den Quark rühren.','Mit Zimt bestreuen.'] },
{ n:'Trauben mit Nüssen', m:'snack', t:2, ing:[['weintrauben',120],['walnuesse',15]], s:['Weintrauben waschen.','Mit Walnüssen anrichten.'] },
{ n:'Reiswaffeln mit Hüttenkäse', m:'snack', t:4, ing:[['reiswaffeln',20],['huettenkaese',60],['cherrytomaten',40]], s:['Reiswaffeln mit Hüttenkäse bestreichen.','Mit Tomaten belegen.'] },
{ n:'Beeren-Smoothie', m:'snack', t:4, ing:[['heidelbeeren',80],['banane',80],['milch',150]], s:['Alle Zutaten pürieren.','In ein Glas füllen.'] },
{ n:'Grüner Protein-Shake', m:'snack', t:4, ing:[['proteinpulver',25],['banane',80],['spinat',30],['milch',200]], s:['Alle Zutaten in den Mixer geben.','Cremig pürieren.'] },
{ n:'Birne mit Käse', m:'snack', t:4, ing:[['birne',120],['gouda',30]], s:['Birne in Spalten schneiden.','Mit Käsewürfeln anrichten.'] },
{ n:'Selbstgemachtes Popcorn', m:'snack', t:8, ing:[['mais',40],['rapsoel',6],['salz',1]], s:['Öl im Topf erhitzen, Maiskörner zugeben und Deckel schließen.','Poppen lassen, bis es leiser wird.','Salzen.'] },
{ n:'Skyr mit Mango', m:'snack', t:3, ing:[['skyr',150],['mango',80]], s:['Skyr in eine Schale geben.','Mit Mangowürfeln toppen.'] },
{ n:'Erdnüsse geröstet', m:'snack', t:2, ing:[['erdnuesse',30]], s:['Erdnüsse abwiegen und genießen.'] },
{ n:'Vollkornbrot mit Frischkäse und Radieschen', m:'snack', t:5, ing:[['vollkornbrot',50],['frischkaese',25],['gurke',40]], s:['Frischkäse aufs Brot streichen.','Mit Gurkenscheiben belegen.'] },
{ n:'Joghurt-Beeren-Eis', m:'snack', t:5, mp:1, ing:[['naturjoghurt',150],['heidelbeeren',80],['honig',10]], s:['Joghurt, Beeren und Honig verrühren.','In eine Form geben und einfrieren.','Vor dem Servieren kurz antauen.'] },
{ n:'Gurken-Feta-Snack', m:'snack', t:5, ing:[['gurke',150],['feta',40],['olivenoel',5],['oregano',1]], s:['Gurke in Scheiben schneiden.','Feta zerbröseln und darüber geben.','Mit Öl und Oregano abschmecken.'] },
{ n:'Bananen-Erdnuss-Shake', m:'snack', t:4, ing:[['banane',120],['erdnussbutter',15],['milch',200]], s:['Alle Zutaten pürieren.','In ein Glas füllen.'] },
{ n:'Käse-Schinken-Röllchen', m:'snack', t:5, ing:[['gouda',40],['kochschinken',40]], s:['Käse- und Schinkenscheiben aufeinanderlegen.','Aufrollen und mit einem Zahnstocher fixieren.'] },
{ n:'Protein-Quark mit Kakao', m:'snack', t:4, ing:[['magerquark',200],['kakao',6],['honig',10]], s:['Quark mit Kakao und Honig cremig rühren.'] },
{ n:'Melonen-Feta-Salat', m:'snack', t:6, ing:[['mango',120],['feta',30],['minze',2]], s:['Mango würfeln.','Mit zerbröseltem Feta und Minze mischen.'] },
{ n:'Vollkornbrot mit Ei', m:'snack', t:8, ing:[['vollkornbrot',50],['ei',60],['salz',1]], s:['Ei kochen und in Scheiben schneiden.','Auf das Brot legen und salzen.'] },
{ n:'Nussmix mit dunkler Schokolade', m:'snack', t:2, ing:[['mandeln',15],['haselnuesse',15],['zartbitter',10]], s:['Nüsse und Schokoladenstückchen mischen.'] },
{ n:'Apfelscheiben mit Zimt', m:'snack', t:3, ing:[['apfel',150],['zimt',1]], s:['Apfel in Scheiben schneiden.','Mit Zimt bestreuen.'] },
{ n:'Rohkost mit Joghurt-Dip', m:'snack', t:6, ing:[['moehren',80],['kohlrabi',80],['naturjoghurt',80],['dill',3]], s:['Gemüse in Sticks schneiden.','Joghurt mit Dill verrühren und dazu reichen.'] },
{ n:'Overnight-Chia mit Kakao', m:'snack', t:4, mp:1, ing:[['chiasamen',25],['milch',150],['kakao',5],['honig',10]], s:['Chiasamen mit Milch, Kakao und Honig verrühren.','Über Nacht quellen lassen.'] },
{ n:'Gefüllte Datteln mit Frischkäse', m:'snack', t:6, ing:[['datteln',40],['frischkaese',20],['walnuesse',10]], s:['Datteln entkernen.','Mit Frischkäse füllen und je eine Walnuss hineinsetzen.'] },
{ n:'Tomate-Mozzarella', m:'snack', t:5, ing:[['tomaten',120],['mozzarella',60],['basilikum',3],['olivenoel',5],['balsamico',5]], s:['Tomate und Mozzarella in Scheiben schneiden und abwechselnd anrichten.','Mit Basilikum, Öl und Balsamico beträufeln.'] },
{ n:'Protein-Smoothie mit Beeren', m:'snack', t:4, ing:[['proteinpulver',25],['heidelbeeren',80],['milch',200]], s:['Alle Zutaten in den Mixer geben und pürieren.'] },
{ n:'Reiswaffeln mit Zartbitterschoko', m:'snack', t:5, ing:[['reiswaffeln',20],['zartbitter',15]], s:['Schokolade schmelzen.','Reiswaffeln damit bestreichen und fest werden lassen.'] },
{ n:'Kichererbsen geröstet', m:'snack', t:25, ing:[['kichererbsen',120],['olivenoel',6],['paprikapulver',2],['salz',1]], s:['Kichererbsen trocken tupfen, mit Öl und Gewürzen mischen.','Im Ofen bei 200 Grad 20 Minuten knusprig rösten.'] },
{ n:'Hüttenkäse mit Ananas', m:'snack', t:3, ing:[['huettenkaese',150],['ananas',80]], s:['Hüttenkäse in eine Schale geben.','Mit Ananasstücken toppen.'] },
{ n:'Sellerie mit Erdnussbutter', m:'snack', t:4, ing:[['sellerie',100],['erdnussbutter',20]], s:['Sellerie in Stangen schneiden.','Erdnussbutter in die Rille streichen.'] },
{ n:'Joghurt mit Apfel und Haferflocken', m:'snack', t:4, ing:[['naturjoghurt',150],['apfel',80],['haferflocken',20]], s:['Joghurt in eine Schale geben.','Apfel raspeln und mit Haferflocken untermischen.'] },
{ n:'Rote-Bete-Chips', m:'snack', t:30, ing:[['rote_beete',120],['olivenoel',6],['salz',1]], s:['Rote Bete hauchdünn hobeln.','Mit Öl und Salz mischen und im Ofen bei 150 Grad knusprig backen.'] },
{ n:'Mini-Caprese-Spieße', m:'snack', t:6, ing:[['cherrytomaten',80],['mozzarella',50],['basilikum',3]], s:['Tomaten, Mozzarella und Basilikum abwechselnd auf Spieße stecken.'] },
{ n:'Bananenbrot-Scheibe', m:'snack', t:5, ing:[['banane',60],['haferflocken',30],['ei',25],['walnuesse',10]], s:['Zutaten verrühren und portionsweise anbacken.','Als kleine Scheibe servieren.'] },
{ n:'Frozen Joghurt-Beeren-Bites', m:'snack', t:5, mp:1, ing:[['griechjoghurt',120],['heidelbeeren',60],['honig',8]], s:['Beeren in Joghurt tauchen.','Auf Backpapier legen und einfrieren.'] },
];
