// Portugiesische, belgische & niederländische Küche. Von Hand geschrieben.
module.exports = [
{ n:'Bacalhau com Natas', m:'abend', t:50, mp:1, ing:[['kabeljau',150],['kartoffeln',180],['zwiebel',60],['kochsahne',110],['reibekaese',40]], s:['Kabeljau und Kartoffeln vorgaren.','Mit Zwiebel und Sahne in eine Form schichten.','Mit Käse überbacken.'] },
{ n:'Frango Piri-Piri mit Reis', m:'abend', t:35, mp:1, ing:[['haehnchen',160],['pilipili',20],['reis',160],['paprika',70],['zitrone',8]], s:['Hähnchen in Piri-Piri marinieren und grillen.','Reis kochen.','Mit Paprika und Zitrone servieren.'] },
{ n:'Caldo Verde mit Chorizo', m:'mittag', t:32, mp:1, ing:[['kartoffeln',180],['grünkohl',100],['chorizo',50],['zwiebel',50],['bruehe',350],['olivenoel',10]], s:['Kartoffeln in Brühe weich kochen und pürieren.','Grünkohl fein schneiden und zugeben.','Mit Chorizoscheiben servieren.'] },
{ n:'Bifana-Sandwich portugiesisch', m:'mittag', t:22, ing:[['schweinefilet',140],['broetchen',90],['knoblauch',6],['paprikapulver',3],['senf',8]], s:['Dünne Schweineschnitzel würzen und braten.','Baguette aufschneiden.','Mit Fleisch füllen und mit Senf servieren.'] },
{ n:'Belgische Carbonade Flamande', m:'abend', t:90, mp:1, ing:[['rindersteak',150],['zwiebel',80],['bier',60],['pommes',180],['senf',10]], s:['Rind und Zwiebel anbraten.','Mit dunklem Bier und Senf lange schmoren.','Mit Pommes servieren.'] },
{ n:'Moules-Frites belgisch', m:'abend', t:32, mp:1, ing:[['muscheln',320],['weisswein',50],['zwiebel',50],['sellerie',40],['pommes',180],['petersilie',5]], s:['Zwiebel und Sellerie andünsten.','Muscheln mit Weißwein dämpfen.','Mit Pommes servieren.'] },
{ n:'Stoemp mit Bratwurst', m:'abend', t:35, ing:[['kartoffeln',200],['moehren',100],['bratwurst',120],['butter',12],['schnittlauch',4]], s:['Kartoffeln und Möhren kochen und grob stampfen.','Bratwurst braten.','Mit Butter und Schnittlauch servieren.'] },
{ n:'Niederländische Erwtensoep', m:'abend', t:50, mp:1, ing:[['erbsen',180],['kasseler',80],['moehren',70],['lauch',50],['kartoffeln',100],['bruehe',400]], s:['Erbsen mit Gemüse und Fleisch weich kochen.','Teilweise pürieren.','Deftig abschmecken.'] },
{ n:'Hutspot mit Rindfleisch', m:'abend', t:60, mp:1, ing:[['rinderbrust',150],['kartoffeln',180],['moehren',120],['zwiebel',60],['bruehe',300]], s:['Rind in Brühe garen.','Kartoffeln, Möhren und Zwiebel weich kochen und stampfen.','Mit dem Fleisch servieren.'] },
{ n:'Portugiesischer Oktopus-Reis (Style)', m:'abend', t:40, mp:1, ing:[['calamari',150],['reis',170],['passata',100],['paprika',60],['zwiebel',50],['koriandergruen',4]], s:['Zwiebel und Paprika anbraten, Passata zugeben.','Calamari kurz mitgaren.','Reis darin garen, mit Koriander servieren.'] },
{ n:'Belgische Chicorée-Schinken-Gratin', m:'abend', t:45, mp:1, ing:[['fenchel',150],['schinkenwuerfel',60],['bechamel',110],['bergkaese',50],['kartoffeln',150]], s:['Chicorée dünsten und mit Schinken umwickeln.','In eine Form legen, mit Béchamel bedecken.','Mit Käse überbacken, mit Kartoffeln servieren.'] },
{ n:'Piri-Piri-Garnelen mit Brot', m:'abend', t:22, mp:1, ing:[['garnelen',150],['pilipili',18],['knoblauch',8],['olivenoel',14],['broetchen',80],['petersilie',4]], s:['Knoblauch in Öl anbraten.','Garnelen mit Piri-Piri braten.','Mit Brot servieren.'] },
{ n:'Portugiesischer Kichererbsen-Kabeljau-Salat', m:'mittag', t:20, mp:1, ing:[['kabeljau',130],['kichererbsen',120],['ei',60],['rotezwiebel',30],['petersilie',5],['olivenoel',10]], s:['Kabeljau garen und zerpflücken.','Mit Kichererbsen, Ei und Zwiebel mischen.','Mit Öl und Petersilie abschmecken.'] },
{ n:'Niederländische Kroketten-Bowl', m:'mittag', t:25, ing:[['kartoffeln',200],['hackrind',100],['semmelbroesel',30],['salat',60],['senf',10]], s:['Kartoffel-Hack-Masse zu Kroketten formen und panieren.','Knusprig backen.','Mit Salat und Senf servieren.'] },
{ n:'Belgisches Waterzooi mit Hähnchen', m:'abend', t:45, mp:1, ing:[['haehnchen',140],['moehren',70],['lauch',60],['kochsahne',80],['kartoffeln',180],['bruehe',300]], s:['Hähnchen und Gemüse in Brühe garen.','Mit Sahne verfeinern.','Mit Kartoffeln servieren.'] },
{ n:'Bacalhau à Gomes de Sá', m:'abend', t:50, mp:1, ing:[['kabeljau',150],['kartoffeln',180],['zwiebel',60],['ei',60],['oliven',25],['olivenoel',14]], s:['Kabeljau und Kartoffeln vorgaren.','Mit Zwiebeln schichten und backen.','Mit Ei und Oliven servieren.'] },
];
