// Tex-Mex & mexikanisch, Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Chicken Fajita-Wrap mit Guacamole', m:'mittag', t:24, mp:1, ing:[['wrap',90],['haehnchen',130],['paprika',80],['zwiebel',50],['guacamole',40],['paprikapulver',2]], s:['Hähnchen und Gemüse würzig anbraten.','Wrap mit Guacamole bestreichen.','Füllen und einrollen.'] },
{ n:'Beef-Nachos überbacken', m:'abend', t:25, ing:[['tortillachips',80],['hackrind',120],['nachokaese',50],['kidneybohnen',70],['jalapeno',20]], s:['Hack würzig anbraten.','Chips mit Hack, Bohnen und Käsesauce belegen.','Mit Jalapeños überbacken.'] },
{ n:'Burrito mit Rindfleisch und Reis', m:'abend', t:28, mp:1, ing:[['wrap',100],['hackrind',120],['reis',100],['kidneybohnen',70],['reibekaese',40],['passata',50]], s:['Hack mit Passata anbraten.','Wrap mit Reis, Bohnen, Hack und Käse füllen.','Fest einrollen.'] },
{ n:'Quesadilla mit Hähnchen und Paprika', m:'mittag', t:20, ing:[['wrap',100],['haehnchen',110],['reibekaese',50],['paprika',50],['zwiebel',30]], s:['Hähnchen und Gemüse anbraten.','Wrap mit Hähnchen und Käse belegen.','Zusammenklappen und knusprig braten.'] },
{ n:'Chili con Carne mit Cornbread', m:'abend', t:45, mp:1, ing:[['hackrind',130],['kidneybohnen',120],['passata',140],['mais',60],['cornmeal',50],['kreuzkuemmel',2]], s:['Hack mit Bohnen, Mais und Passata köcheln.','Cornbread backen.','Zusammen servieren.'] },
{ n:'Loaded Sweet-Potato-Nachos', m:'abend', t:40, mp:1, ing:[['suesskartoffel',200],['schwarzebohnen',90],['nachokaese',40],['mais',50],['jalapeno',15]], s:['Süßkartoffelscheiben rösten.','Mit Bohnen, Mais und Käsesauce belegen.','Mit Jalapeños überbacken.'] },
{ n:'Enchilada-Auflauf mit Hähnchen und Bohnen', m:'abend', t:45, mp:1, ing:[['tortilla_mais',100],['haehnchen',120],['schwarzebohnen',80],['passata',130],['reibekaese',60]], s:['Tortillas mit Hähnchen und Bohnen füllen und rollen.','In eine Form legen, mit Passata übergießen.','Mit Käse überbacken.'] },
{ n:'Taco-Bowl mit Hackfleisch', m:'mittag', t:24, mp:1, ing:[['hackrind',120],['reis',150],['salat',50],['mais',50],['reibekaese',40],['guacamole',40]], s:['Hack würzig anbraten.','Reis kochen.','Mit Salat, Mais, Käse und Guacamole anrichten.'] },
{ n:'Fisch-Tacos mit Chipotle-Creme', m:'abend', t:28, mp:1, ing:[['seelachs',150],['tortilla_mais',80],['weisskohl',60],['naturjoghurt',40],['sriracha',10],['limette',8]], s:['Fisch würzen und braten.','Chipotle-Creme aus Joghurt und Sriracha rühren.','In Tortillas mit Krautsalat füllen.'] },
{ n:'Vegetarische Bohnen-Burrito-Bowl', m:'mittag', t:25, mp:1, ing:[['reis',160],['kidneybohnen',100],['mais',60],['paprika',60],['avocado',50],['limette',6]], s:['Reis kochen.','Bohnen, Mais und Paprika erwärmen.','Mit Avocado und Limette anrichten.'] },
{ n:'Pulled-Chicken-Enchiladas', m:'abend', t:40, mp:1, ing:[['haehnchen',140],['tortilla_mais',100],['passata',130],['mais',50],['reibekaese',60]], s:['Hähnchen garen und zerzupfen.','In Tortillas mit Mais füllen und rollen.','Mit Passata und Käse überbacken.'] },
{ n:'Huevos Rancheros mit Bohnen', m:'fruh', t:20, ing:[['ei',120],['tortilla_mais',80],['passata',100],['kidneybohnen',70],['reibekaese',30]], s:['Tortillas mit Bohnen belegen.','Spiegeleier braten.','Mit Tomatensalsa und Käse toppen.'] },
{ n:'Chorizo-Bohnen-Quesadilla', m:'mittag', t:20, ing:[['wrap',100],['chorizo',50],['kidneybohnen',70],['reibekaese',50],['paprika',40]], s:['Chorizo und Paprika anbraten.','Wrap mit Bohnen, Chorizo und Käse belegen.','Zusammenklappen und braten.'] },
{ n:'Tex-Mex-Reispfanne mit Hähnchen', m:'mittag', t:26, mp:1, ing:[['haehnchen',140],['reis',160],['kidneybohnen',80],['mais',60],['paprikapulver',2],['passata',60]], s:['Hähnchen anbraten.','Reis, Bohnen, Mais und Passata zugeben.','Würzig garen.'] },
{ n:'Carne-Asada-Tacos', m:'abend', t:30, mp:1, ing:[['rindersteak',150],['tortilla_mais',80],['zwiebel',40],['koriandergruen',5],['limette',8],['avocado',40]], s:['Steak marinieren und scharf braten, in Streifen schneiden.','Tortillas erwärmen.','Mit Zwiebel, Koriander und Avocado füllen.'] },
{ n:'Vegetarische Chili-Cheese-Fries', m:'abend', t:35, ing:[['pommes',200],['kidneybohnen',100],['passata',80],['nachokaese',40],['jalapeno',15]], s:['Pommes knusprig backen.','Chili aus Bohnen und Passata köcheln.','Über die Pommes geben, mit Käsesauce und Jalapeños.'] },
];
