// Indische Küche, Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Palak Chicken (Hähnchen im Spinat-Curry)', m:'abend', t:35, mp:1, ing:[['haehnchen',150],['spinat',130],['kokosmilch',80],['garam_masala',3],['zwiebel',50],['reis',150]], s:['Hähnchen mit Zwiebel und Gewürzen anbraten.','Spinat pürieren und mit Kokosmilch zugeben.','Köcheln, mit Reis servieren.'] },
{ n:'Paneer Bhurji', m:'mittag', t:22, mp:1, ing:[['paneer',160],['tomaten',70],['zwiebel',50],['garam_masala',3],['naanbrot',70],['erbsen',40]], s:['Zwiebel und Tomate anbraten.','Paneer zerbröseln und mit Gewürzen braten.','Mit Naan servieren.'] },
{ n:'Bombay Potatoes', m:'mittag', t:30, mp:1, ing:[['kartoffeln',220],['senfsamen',2],['kurkuma2',1],['zwiebel',50],['koriandergruen',5],['ghee',12]], s:['Senfsamen in Ghee anrösten.','Kartoffeln mit Zwiebel und Gewürzen braten.','Mit Koriander servieren.'] },
{ n:'Prawn Masala (Garnelen-Curry)', m:'abend', t:28, mp:1, ing:[['garnelen',150],['passata',110],['kokosmilch',70],['garam_masala',3],['zwiebel',50],['reis',150]], s:['Zwiebel mit Gewürzen anbraten.','Passata und Kokosmilch zugeben.','Garnelen kurz garen, mit Reis servieren.'] },
{ n:'Chole (Kichererbsen-Curry) mit Bhatura', m:'mittag', t:32, mp:1, ing:[['kichererbsen',180],['passata',120],['zwiebel',50],['garam_masala',3],['ingwer',6],['naanbrot',80]], s:['Zwiebel und Ingwer anbraten.','Kichererbsen und Passata mit Gewürzen köcheln.','Mit Fladenbrot servieren.'] },
{ n:'Egg Bhurji (indisches Rührei)', m:'fruh', t:15, ing:[['ei',150],['zwiebel',50],['tomaten',60],['garam_masala',2],['koriandergruen',4],['naanbrot',60]], s:['Zwiebel und Tomate anbraten.','Eier mit Gewürzen zugeben und stocken lassen.','Mit Naan servieren.'] },
{ n:'Lamm Saag (Lamm im Spinat)', m:'abend', t:60, mp:1, ing:[['lammfilet',150],['spinat',130],['zwiebel',50],['garam_masala',3],['reis',150],['ingwer',6]], s:['Lamm mit Zwiebel und Ingwer anbraten.','Spinat pürieren und zugeben.','Schmoren, mit Reis servieren.'] },
{ n:'Dum Aloo (Kartoffeln in Currysauce)', m:'mittag', t:35, mp:1, ing:[['kartoffeln',200],['passata',110],['naturjoghurt',60],['garam_masala',3],['zwiebel',40],['reis',140]], s:['Kartoffeln anbraten.','In würziger Joghurt-Tomaten-Sauce köcheln.','Mit Reis servieren.'] },
{ n:'Methi Chicken', m:'abend', t:35, mp:1, ing:[['haehnchen',150],['passata',110],['bockshornklee',2],['kochsahne',60],['zwiebel',50],['reis',150]], s:['Hähnchen mit Zwiebel anbraten.','Passata, Sahne und Bockshornklee zugeben.','Köcheln, mit Reis servieren.'] },
{ n:'Veg Pulao mit Cashews', m:'mittag', t:30, mp:1, ing:[['reis',180],['moehren',60],['erbsen',60],['blumenkohl',70],['cashews',20],['garam_masala',3]], s:['Gemüse mit Gewürzen anbraten.','Reis zugeben und in Brühe garen.','Mit Cashews servieren.'] },
{ n:'Chana Saag (Kichererbsen-Spinat)', m:'mittag', t:28, mp:1, ing:[['kichererbsen',170],['spinat',110],['passata',80],['garam_masala',3],['knoblauch',6],['reis',150]], s:['Knoblauch anbraten.','Kichererbsen, Spinat und Passata mit Gewürzen köcheln.','Mit Reis servieren.'] },
{ n:'Aloo Palak (Kartoffel-Spinat)', m:'mittag', t:30, mp:1, ing:[['kartoffeln',180],['spinat',130],['zwiebel',50],['garam_masala',3],['ghee',10],['reis',140]], s:['Zwiebel in Ghee anbraten.','Kartoffeln und Spinat mit Gewürzen garen.','Mit Reis servieren.'] },
{ n:'Butter Prawns mit Naan', m:'abend', t:28, mp:1, ing:[['garnelen',150],['passata',110],['kochsahne',60],['butter',15],['garam_masala',3],['naanbrot',80]], s:['Garnelen kurz anbraten.','Buttrige Tomaten-Sahne-Sauce köcheln.','Garnelen zugeben, mit Naan servieren.'] },
{ n:'Gemüse-Jalfrezi', m:'mittag', t:28, mp:1, ing:[['paprika',80],['zucchini',70],['blumenkohl',80],['passata',100],['garam_masala',3],['reis',150]], s:['Gemüse scharf anbraten.','Passata und Gewürze zugeben.','Mit Reis servieren.'] },
{ n:'Chicken Chettinad', m:'abend', t:38, mp:1, ing:[['haehnchen',150],['kokosmilch',90],['passata',90],['currypul',4],['zwiebel',50],['reis',150]], s:['Hähnchen mit Zwiebel und Gewürzen anbraten.','Kokosmilch und Passata zugeben.','Scharf köcheln, mit Reis servieren.'] },
{ n:'Pav Bhaji', m:'mittag', t:35, mp:1, ing:[['kartoffeln',150],['erbsen',60],['paprika',60],['passata',110],['butter',15],['broetchen',90]], s:['Gemüse weich kochen und zerdrücken.','Mit Passata, Butter und Gewürzen köcheln.','Mit gebutterten Brötchen servieren.'] },
];
