// Streetfood & Herzhaftes aus aller Welt. Von Hand geschrieben.
module.exports = [
{ n:'Poutine mit Bratensauce und Käse', m:'abend', t:35, ing:[['pommes',220],['bergkaese',60],['passata',60],['kochsahne',40],['zwiebel',40]], s:['Pommes (220 g) im Ofen bei 220 Grad etwa 20 Minuten knusprig backen, dabei einmal wenden.','Zwiebel (40 g) fein würfeln und in einem kleinen Topf glasig andünsten.','Passata (60 g) und Sahne (40 g) zugeben und 5 Minuten zu einer sämigen braunen Sauce einkochen, mit Salz und Pfeffer abschmecken.','Bergkäse (60 g) grob reiben.','Die heißen Pommes auf einen Teller geben, mit Käse bestreuen und die heiße Sauce darübergießen.'] },
{ n:'Currywurst mit Brötchen und Zwiebeln', m:'mittag', t:20, ing:[['bratwurst',150],['broetchen',80],['ketchup',30],['currypul',3],['zwiebel',40]], s:['Bratwurst (150 g) in einer Pfanne bei mittlerer Hitze rundum 6-8 Minuten goldbraun braten, dann in Scheiben schneiden.','Zwiebel (40 g) fein würfeln und in derselben Pfanne kurz glasig dünsten.','Ketchup (30 g) mit dem Currypulver (3 g) verrühren und leicht erwärmen.','Wurstscheiben mit der Currysauce übergießen und die Zwiebeln darauf verteilen.','Mit dem Brötchen (80 g) servieren.'] },
{ n:'Bunny Chow (Curry im Brot)', m:'abend', t:35, mp:1, ing:[['broetchen',120],['haehnchen',130],['kartoffeln',100],['currypul',4],['passata',90],['zwiebel',50]], s:['Zwiebel (50 g) würfeln und mit dem Currypulver (4 g) in etwas Öl 2 Minuten anrösten.','Hähnchen (130 g) und Kartoffeln (100 g) in Würfel schneiden, zugeben und kurz mitbraten.','Passata (90 g) und einen Schuss Wasser angießen und zugedeckt 18-20 Minuten weich köcheln, bis die Kartoffeln gar sind.','Das Brötchen (120 g) oben aufschneiden und aushöhlen.','Das heiße Curry in das Brot füllen und mit der herausgenommenen Krume servieren.'] },
{ n:'Arepa mit Hähnchen und Avocado', m:'mittag', t:28, mp:1, ing:[['cornmeal',80],['haehnchen',110],['avocado',60],['mayo',15],['zwiebel',30]], s:['Maismehl (80 g) mit Salz und lauwarmem Wasser zu einem geschmeidigen Teig kneten, kurz ruhen lassen.','Zu 2 Fladen formen und in einer Pfanne je Seite 4-5 Minuten backen, bis sie fest und leicht gebräunt sind.','Hähnchen (110 g) würzen, braten und mit zwei Gabeln zerzupfen.','Avocado (60 g) mit Mayo (15 g) und gewürfelter Zwiebel (30 g) zu einem Salat mischen.','Arepas aufschneiden und mit Hähnchen und Avocadocreme füllen.'] },
{ n:'Döner-Teller mit Reis und Salat', m:'abend', t:30, mp:1, ing:[['gyrosfleisch',150],['reis',160],['salat',40],['tomaten',50],['naturjoghurt',50],['knoblauch',4]], s:['Reis (160 g) nach Packung garen.','Gyrosfleisch (150 g) in einer heißen Pfanne 6-8 Minuten kräftig anbraten, bis es Röststellen bekommt.','Joghurt (50 g) mit gepresstem Knoblauch (4 g), Salz und Pfeffer zu einer Sauce rühren.','Salat (40 g) und Tomaten (50 g) in mundgerechte Stücke schneiden.','Reis, Fleisch und Salat auf einem Teller anrichten und mit der Knoblauchsauce beträufeln.'] },
{ n:'Bao-Bun mit Pulled Pork', m:'abend', t:35, mp:1, ing:[['burgerbun',90],['schweinefilet',130],['hoisin',20],['gurke',50],['fruehlingszwiebel',15]], s:['Schweinefilet (130 g) würzen und in einer Pfanne rundum anbraten, dann zugedeckt bei kleiner Hitze 15 Minuten weich garen.','Das Fleisch mit zwei Gabeln zerzupfen und mit Hoisin (20 g) vermengen.','Bao-Buns bzw. Buns (90 g) 6-8 Minuten im Dämpfeinsatz weich dämpfen.','Gurke (50 g) in feine Streifen und Frühlingszwiebel (15 g) in Ringe schneiden.','Buns öffnen, mit Pulled Pork, Gurke und Frühlingszwiebeln füllen.'] },
{ n:'Falafel im Fladenbrot mit Tahin', m:'mittag', t:28, mp:1, ing:[['kichererbsen',140],['fladenbrot',90],['tahin',18],['salat',30],['tomaten',50],['gurke',40]], s:['Kichererbsen (140 g) mit Zwiebel, Knoblauch und Gewürzen im Mixer grob zerkleinern und zu kleinen Bällchen formen.','Falafel in heißem Öl rundum 4-5 Minuten goldbraun braten und auf Küchenpapier abtropfen lassen.','Tahin (18 g) mit etwas Wasser und Zitrone zu einer cremigen Sauce verrühren.','Salat (30 g), Tomaten (50 g) und Gurke (40 g) klein schneiden.','Fladenbrot (90 g) aufklappen, mit Tahin bestreichen und mit Falafel und Gemüse füllen.'] },
{ n:'Hot Dog mit Röstzwiebeln und Senf', m:'mittag', t:15, ing:[['broetchen',80],['wiener',80],['ketchup',15],['senf',10],['roestzwiebel',15]], s:['Wiener Würstchen (80 g) in heißem, nicht kochendem Wasser 5 Minuten ziehen lassen.','Brötchen (80 g) längs einschneiden und kurz aufbacken oder toasten.','Die Wurst in das Brötchen legen.','Mit Ketchup (15 g) und Senf (10 g) beträufeln.','Mit Röstzwiebeln (15 g) bestreuen.'] },
{ n:'Souvlaki-Pita mit Zaziki', m:'mittag', t:28, mp:1, ing:[['schweinefilet',150],['fladenbrot',80],['naturjoghurt',60],['gurke',50],['tomaten',50]], s:['Schweinefilet (150 g) würfeln, mit Öl, Oregano, Salz und Pfeffer marinieren und kurz ziehen lassen.','Die Würfel in einer heißen Pfanne 6-8 Minuten rundum braun braten.','Gurke (50 g) fein raspeln, ausdrücken und mit Joghurt (60 g) und Knoblauch zu Zaziki verrühren.','Fladenbrot (80 g) kurz erwärmen.','Pita mit Fleisch, Tomatenscheiben (50 g) und Zaziki füllen.'] },
{ n:'Fish and Chips im Bierteig', m:'abend', t:35, ing:[['kabeljau',160],['mehl',30],['bier',30],['pommes',180],['erbsen',80]], s:['Pommes (180 g) im Ofen bei 220 Grad etwa 20 Minuten knusprig backen.','Mehl (30 g) mit Bier (30 g) und einer Prise Salz zu einem glatten Teig verrühren.','Kabeljau (160 g) trockentupfen, durch den Bierteig ziehen und in heißem Öl 4-5 Minuten goldbraun ausbacken.','Erbsen (80 g) garen und grob zu einem Püree zerstampfen, mit Salz abschmecken.','Fisch, Pommes und Erbsenpüree zusammen anrichten.'] },
{ n:'Kumpir mit Mais, Oliven und Krautsalat', m:'mittag', t:50, ing:[['kartoffeln',280],['bergkaese',40],['mais',50],['oliven',25],['weisskohl',50],['butter',12]], s:['Große Kartoffel (280 g) im Ofen bei 200 Grad 40-45 Minuten weich backen.','Weißkohl (50 g) fein hobeln, salzen und mit etwas Essig zu einem kleinen Krautsalat kneten.','Die heiße Kartoffel längs aufschneiden, das Innere mit Butter (12 g) und geriebenem Käse (40 g) cremig zerdrücken.','Mit Mais (50 g), Oliven (25 g) und Krautsalat füllen.'] },
{ n:'Banh Mi mit Hähnchen und Möhre', m:'mittag', t:22, ing:[['broetchen',90],['haehnchen',110],['moehren',50],['gurke',40],['koriandergruen',5],['sriracha',8]], s:['Hähnchen (110 g) würzen und in der Pfanne 6-8 Minuten goldbraun braten, dann in Streifen schneiden.','Möhre (50 g) in feine Stifte schneiden und mit etwas Zucker und Essig 5 Minuten ziehen lassen.','Baguette bzw. Brötchen (90 g) längs aufschneiden und leicht rösten.','Mit Hähnchen, Möhre, Gurkenstreifen (40 g) und Koriander (5 g) füllen.','Mit Sriracha (8 g) abschmecken.'] },
{ n:'Quesadilla mit Käse, Bohnen und Mais', m:'mittag', t:18, ing:[['wrap',100],['reibekaese',50],['kidneybohnen',70],['mais',40],['paprika',40]], s:['Kidneybohnen (70 g) abspülen und Paprika (40 g) fein würfeln.','Eine Hälfte des Wraps (100 g) mit Käse (50 g), Bohnen, Mais (40 g) und Paprika belegen.','Den Wrap zusammenklappen.','In einer trockenen Pfanne je Seite 2-3 Minuten braten, bis er knusprig ist und der Käse schmilzt.','In Ecken schneiden und servieren.'] },
{ n:'Gyros-Fladen mit Pommes', m:'abend', t:30, mp:1, ing:[['gyrosfleisch',150],['fladenbrot',80],['pommes',120],['naturjoghurt',50],['salat',30]], s:['Pommes (120 g) im Ofen knusprig backen.','Gyrosfleisch (150 g) in einer heißen Pfanne 6-8 Minuten kräftig anbraten.','Joghurt (50 g) mit Knoblauch und Salz zu Zaziki rühren.','Fladenbrot (80 g) erwärmen, mit Zaziki bestreichen und mit Gyros und Salat (30 g) füllen.','Mit den Pommes servieren.'] },
{ n:'Chicken-Wrap mexikanisch mit Reis', m:'mittag', t:24, mp:1, ing:[['wrap',100],['haehnchen',120],['reis',90],['kidneybohnen',60],['reibekaese',40],['guacamole',30]], s:['Reis (90 g) garen und Kidneybohnen (60 g) abspülen.','Hähnchen (120 g) mit Paprikapulver und Kreuzkümmel würzen und in der Pfanne 6-8 Minuten braten, dann in Streifen schneiden.','Wrap (100 g) kurz erwärmen und mit Reis, Bohnen, Hähnchen und Käse (40 g) belegen.','Guacamole (30 g) daraufgeben.','Fest einrollen und in der Mitte durchschneiden.'] },
{ n:'Leberkäse-Semmel mit süßem Senf', m:'mittag', t:20, ing:[['leberkaese',150],['broetchen',80],['senf',12],['gewuerzgurke',30]], s:['Leberkäse (150 g) in eine dicke Scheibe schneiden und in der Pfanne je Seite 3-4 Minuten knusprig braten.','Brötchen bzw. Semmel (80 g) aufschneiden und mit süßem Senf (12 g) bestreichen.','Gewürzgurke (30 g) in Scheiben schneiden.','Leberkäse einlegen und mit Gurke belegen.'] },
];
