// Eintöpfe & Schmorgerichte, regional. Von Hand geschrieben.
module.exports = [
{ n:'Pichelsteiner Eintopf', m:'abend', t:60, mp:1, ing:[['rindersteak',130],['kartoffeln',150],['moehren',80],['lauch',60],['sellerie',50],['bruehe',400]], s:['Rindfleisch (130 g) würfeln und in einem Topf in etwas Öl rundum kräftig anbraten.','Kartoffeln (150 g), Möhren (80 g), Lauch (60 g) und Sellerie (50 g) in Stücke schneiden und über das Fleisch schichten.','Mit der Brühe (400 ml) aufgießen, salzen und pfeffern.','Zugedeckt bei kleiner Hitze 45 Minuten schmoren, bis Fleisch und Gemüse weich sind.'] },
{ n:'Westfälischer Blindhuhn-Eintopf', m:'abend', t:45, mp:1, ing:[['weissebohnen',150],['gruenebohnen',80],['moehren',70],['apfel',80],['bacon',40],['kartoffeln',120]], s:['Bacon (40 g) würfeln und im Topf auslassen, bis er leicht knusprig ist.','Grüne Bohnen (80 g), Möhre (70 g), Apfel (80 g) und Kartoffeln (120 g) würfeln und zugeben.','Weiße Bohnen (150 g) und etwas Brühe angießen.','Zugedeckt 25-30 Minuten weich kochen und mit Salz, Pfeffer und einem Spritzer Essig abschmecken.'] },
{ n:'Serbischer Bohneneintopf (Pasulj)', m:'abend', t:50, mp:1, ing:[['weissebohnen',180],['mettwurst',60],['moehren',60],['zwiebel',50],['paprikapulver',3],['bruehe',300]], s:['Zwiebel (50 g) würfeln und mit der in Scheiben geschnittenen Mettwurst (60 g) anbraten.','Vom Herd ziehen, Paprikapulver (3 g) einrühren, damit es nicht bitter wird.','Weiße Bohnen (180 g) und Möhre (60 g) zugeben und mit Brühe (300 ml) aufgießen.','30-35 Minuten sämig köcheln lassen, bis die Bohnen weich sind.'] },
{ n:'Irish Stew mit Lamm', m:'abend', t:80, mp:1, ing:[['lammfilet',150],['kartoffeln',180],['moehren',80],['lauch',60],['zwiebel',50],['bruehe',350]], s:['Lamm (150 g) würfeln und mit der Zwiebel (50 g) in etwas Öl rundum anbraten.','Kartoffeln (180 g), Möhre (80 g) und Lauch (60 g) grob schneiden und zugeben.','Mit Brühe (350 ml) aufgießen, salzen, pfeffern und einen Lorbeer zugeben.','Zugedeckt bei kleiner Hitze 60 Minuten schmoren, bis das Lamm zart zerfällt.'] },
{ n:'Ungarisches Letscho mit Wurst', m:'abend', t:30, mp:1, ing:[['paprika',150],['tomaten',90],['mettwurst',60],['zwiebel',50],['paprikapulver',3],['reis',150]], s:['Reis (150 g) nach Packung garen.','Zwiebel (50 g) und Paprika (150 g) in Streifen schneiden und in etwas Öl 5 Minuten schmoren.','Vom Herd Paprikapulver (3 g) einrühren, dann Tomaten (90 g) und die geschnittene Mettwurst (60 g) zugeben.','10 Minuten sämig köcheln und mit dem Reis servieren.'] },
{ n:'Bohnen-Gemüse-Eintopf mit Speck', m:'abend', t:40, mp:1, ing:[['weissebohnen',160],['moehren',70],['kartoffeln',120],['bacon',40],['zwiebel',50],['bruehe',350]], s:['Bacon (40 g) und Zwiebel (50 g) würfeln und im Topf anbraten.','Möhre (70 g) und Kartoffeln (120 g) würfeln, zugeben und kurz mitbraten.','Weiße Bohnen (160 g) und Brühe (350 ml) angießen.','Zugedeckt 25 Minuten weich kochen und abschmecken.'] },
{ n:'Kartoffel-Möhren-Eintopf mit Würstchen', m:'mittag', t:35, mp:1, ing:[['kartoffeln',180],['moehren',100],['wiener',80],['lauch',50],['bruehe',400]], s:['Kartoffeln (180 g), Möhren (100 g) und Lauch (50 g) würfeln und in etwas Öl 3 Minuten andünsten.','Mit Brühe (400 ml) aufgießen und 20 Minuten weich kochen.','Einen Teil der Kartoffeln am Topfrand zerdrücken, damit der Eintopf sämig wird.','Wiener (80 g) in Scheiben zugeben und 5 Minuten ziehen lassen.'] },
{ n:'Marokkanischer Gemüse-Kichererbsen-Eintopf', m:'abend', t:40, mp:1, ing:[['kichererbsen',150],['suesskartoffel',120],['moehren',60],['passata',110],['raselhanout',3],['couscous',120]], s:['Süßkartoffel (120 g) und Möhre (60 g) würfeln und in etwas Öl anbraten.','Ras el Hanout (3 g) zugeben und kurz mitrösten.','Kichererbsen (150 g) und Passata (110 g) angießen und 20 Minuten weich schmoren.','Couscous (120 g) mit kochendem Wasser übergießen, 5 Minuten quellen lassen und zum Eintopf servieren.'] },
{ n:'Berglinsen-Eintopf mit Sellerie und Speck', m:'abend', t:40, mp:1, ing:[['linsen',160],['kartoffeln',120],['sellerieknolle',70],['lauch',50],['bacon',40],['bruehe',380]], s:['Bacon (40 g) würfeln und mit Sellerie (70 g), Lauch (50 g) und Kartoffeln (120 g) im Topf anbraten.','Linsen (160 g) zugeben und mit Brühe (380 ml) aufgießen.','25-30 Minuten köcheln, bis die Linsen weich sind.','Mit Salz, Pfeffer und einem Schuss Essig abschmecken.'] },
{ n:'Kohleintopf mit Hackfleisch', m:'abend', t:45, mp:1, ing:[['weisskohl',150],['hackrind',120],['kartoffeln',120],['passata',100],['zwiebel',50],['bruehe',300]], s:['Hackfleisch (120 g) mit der Zwiebel (50 g) krümelig anbraten.','Weißkohl (150 g) in Streifen und Kartoffeln (120 g) würfeln, zugeben und kurz mitbraten.','Passata (100 g) und Brühe (300 ml) angießen.','Zugedeckt 25-30 Minuten weich schmoren und würzen.'] },
{ n:'Grünkohl-Eintopf mit Kasseler', m:'abend', t:50, mp:1, ing:[['grünkohl',140],['kasseler',80],['kartoffeln',150],['zwiebel',50],['bruehe',380]], s:['Zwiebel (50 g) in etwas Öl glasig dünsten, Grünkohl (140 g) zugeben und zusammenfallen lassen.','Mit Brühe (380 ml) aufgießen und 20 Minuten köcheln.','Kasseler (80 g) und gewürfelte Kartoffeln (150 g) zugeben.','Weitere 20 Minuten schmoren, bis alles weich ist.'] },
{ n:'Weiße-Bohnen-Eintopf toskanisch', m:'abend', t:40, mp:1, ing:[['weissebohnen',170],['zucchini',70],['moehren',60],['passata',120],['rosmarin',2],['olivenoel',10]], s:['Möhre (60 g) und Zucchini (70 g) würfeln und in Olivenöl (10 g) andünsten.','Weiße Bohnen (170 g) und Passata (120 g) zugeben.','Mit Rosmarin (2 g), Salz und Pfeffer würzen.','20 Minuten sämig köcheln lassen.'] },
{ n:'Rindfleisch-Gemüse-Eintopf', m:'abend', t:70, mp:1, ing:[['rindersteak',140],['kartoffeln',150],['moehren',80],['erbsen',60],['zwiebel',50],['bruehe',380]], s:['Rindfleisch (140 g) würfeln und mit der Zwiebel (50 g) rundum kräftig anbraten.','Mit Brühe (380 ml) aufgießen und zugedeckt 40 Minuten schmoren.','Kartoffeln (150 g) und Möhre (80 g) würfeln, zugeben und 20 Minuten mitgaren.','Erbsen (60 g) zufügen und 5 Minuten fertig garen.'] },
{ n:'Kürbis-Linsen-Eintopf mit Kokos', m:'abend', t:35, mp:1, ing:[['kuerbis',180],['rotelinsen',120],['kokosmilch',90],['moehren',60],['currypul',3],['bruehe',280]], s:['Kürbis (180 g) und Möhre (60 g) würfeln und in etwas Öl anbraten, Curry (3 g) mitrösten.','Rote Linsen (120 g), Kokosmilch (90 g) und Brühe (280 ml) angießen.','15-18 Minuten köcheln, bis Linsen und Kürbis weich sind.','Leicht cremig zerdrücken und abschmecken.'] },
{ n:'Erbsen-Möhren-Eintopf mit Kartoffeln', m:'mittag', t:35, mp:1, ing:[['erbsen',150],['moehren',100],['kartoffeln',150],['zwiebel',50],['bruehe',400],['petersilie',4]], s:['Zwiebel (50 g) glasig dünsten, Möhre (100 g) und Kartoffeln (150 g) würfeln und zugeben.','Mit Brühe (400 ml) aufgießen und 15 Minuten kochen.','Erbsen (150 g) zufügen und 5 Minuten mitgaren.','Mit Petersilie (4 g) bestreut servieren.'] },
{ n:'Chorizo-Kichererbsen-Eintopf spanisch', m:'abend', t:35, mp:1, ing:[['kichererbsen',170],['chorizo',60],['spinat',70],['passata',100],['zwiebel',50],['bruehe',250]], s:['Chorizo (60 g) in Scheiben und Zwiebel (50 g) anbraten, bis die Wurst ihr rotes Öl abgibt.','Kichererbsen (170 g) und Passata (100 g) zugeben und mit Brühe (250 ml) aufgießen.','15 Minuten köcheln lassen.','Spinat (70 g) unterrühren, bis er zusammenfällt, dann abschmecken.'] },
];
