// Sättigende Salate, Teil 4. Von Hand geschrieben.
module.exports = [
{ n:'Nizza-Salat mit Thunfisch und Ei', m:'mittag', t:22, ing:[['thunfisch',100],['ei',100],['kartoffeln',120],['gruenebohnen',70],['oliven',25],['olivenoel',12]], s:['Kartoffeln (120 g) in Salzwasser 15 Minuten garen, die grünen Bohnen (70 g) die letzten 6 Minuten mitkochen.','Eier (100 g) 8 Minuten hart kochen, abschrecken, pellen und vierteln.','Kartoffeln und Bohnen abkühlen lassen und mit Thunfisch (100 g) und Oliven (25 g) auf dem Teller anrichten.','Olivenöl (12 g) mit etwas Essig, Salz und Pfeffer verrühren und über den Salat träufeln.'] },
{ n:'Caesar-Salat mit Hähnchen und Croutons', m:'mittag', t:20, ing:[['haehnchen',130],['salat',90],['parmesan',25],['broetchen',40],['naturjoghurt',50],['knoblauch',4]], s:['Hähnchen (130 g) würzen und in der Pfanne 6-8 Minuten goldbraun braten, dann in Streifen schneiden.','Brötchen (40 g) würfeln und in etwas Öl zu knusprigen Croutons rösten.','Joghurt (50 g) mit gepresstem Knoblauch (4 g), etwas Parmesan, Salz und Pfeffer zu einem Dressing verrühren.','Salat (90 g) in mundgerechte Stücke zupfen, mit Hähnchen, Croutons und Dressing mischen und mit dem restlichen Parmesan (25 g) bestreuen.'] },
{ n:'Bulgur-Salat mit Granatapfel und Minze', m:'mittag', t:22, mp:1, ing:[['bulgur',160],['granatapfel2',40],['gurke',60],['minze',4],['zitrone',10],['olivenoel',10]], s:['Bulgur (160 g) mit kochendem Wasser übergießen und zugedeckt 12 Minuten quellen lassen, dann mit einer Gabel auflockern.','Gurke (60 g) fein würfeln, Granatapfelkerne (40 g) und gehackte Minze (4 g) untermischen.','Zitronensaft (10 g) und Olivenöl (10 g) mit Salz und Pfeffer verrühren.','Alles vermengen und 5 Minuten durchziehen lassen.'] },
{ n:'Quinoa-Salat mit Feta und Kräutern', m:'mittag', t:25, mp:1, ing:[['quinoa',160],['feta',50],['tomaten',60],['gurke',60],['petersilie',6],['olivenoel',10]], s:['Quinoa (160 g) gründlich abspülen und in der doppelten Menge Wasser 15 Minuten weich garen, dann abkühlen lassen.','Tomaten (60 g) und Gurke (60 g) würfeln.','Mit dem Quinoa, gehackter Petersilie (6 g) und Olivenöl (10 g) mischen.','Feta (50 g) zerbröseln, unterheben und mit Salz und Pfeffer abschmecken.'] },
{ n:'Wurstsalat mit Käse und Gurke', m:'abend', t:15, ing:[['gyrosfleisch',100],['bergkaese',50],['gewuerzgurke',40],['rotezwiebel',30],['essig',8],['olivenoel',10]], s:['Fleisch bzw. Wurst (100 g) und Bergkäse (50 g) in feine Streifen schneiden.','Gewürzgurke (40 g) in Scheiben und rote Zwiebel (30 g) in dünne Ringe schneiden.','Alles in einer Schüssel mischen.','Essig (8 g) und Öl (10 g) mit Salz und Pfeffer verrühren, untermengen und 10 Minuten ziehen lassen.'] },
{ n:'Rote-Bete-Feta-Salat mit Walnuss', m:'mittag', t:18, ing:[['rote_beete',130],['feta',50],['salat',60],['walnuesse',20],['balsamico',8],['olivenoel',8]], s:['Vorgegarte Rote Bete (130 g) in Würfel schneiden.','Salat (60 g) auf einem Teller verteilen und die Rote Bete darauf anrichten.','Feta (50 g) zerbröseln und Walnüsse (20 g) grob hacken, beides darüberstreuen.','Balsamico (8 g) und Olivenöl (8 g) verrühren und darüberträufeln.'] },
{ n:'Couscous-Salat mit Hähnchen, Paprika und Rosinen', m:'mittag', t:22, mp:1, ing:[['couscous',160],['haehnchen',120],['paprika',60],['rosinen2',20],['zitrone',10],['olivenoel',8]], s:['Couscous (160 g) mit kochendem Wasser übergießen, zugedeckt 5 Minuten quellen lassen und auflockern.','Hähnchen (120 g) in der Pfanne 6-8 Minuten braten und würfeln.','Paprika (60 g) fein würfeln und mit Rosinen (20 g) unter den Couscous mischen.','Mit Hähnchen, Zitronensaft (10 g) und Olivenöl (8 g) vermengen und abschmecken.'] },
{ n:'Griechischer Bauernsalat mit Fladenbrot', m:'mittag', t:15, ing:[['tomaten',120],['gurke',100],['feta',60],['oliven',30],['rotezwiebel',30],['fladenbrot',60]], s:['Tomaten (120 g) und Gurke (100 g) in grobe Stücke, rote Zwiebel (30 g) in dünne Ringe schneiden.','Mit Oliven (30 g) in eine Schüssel geben.','Feta (60 g) am Stück darauflegen, mit Olivenöl, Oregano und Pfeffer würzen.','Fladenbrot (60 g) kurz aufbacken und dazu reichen.'] },
{ n:'Linsen-Feta-Salat mit Paprika', m:'mittag', t:25, mp:1, ing:[['linsen',160],['paprika',60],['rotezwiebel',30],['feta',50],['petersilie',5],['olivenoel',10]], s:['Linsen (160 g) in Wasser 20 Minuten bissfest garen und abkühlen lassen.','Paprika (60 g) und rote Zwiebel (30 g) fein würfeln und untermischen.','Olivenöl (10 g) mit etwas Essig, Salz und Pfeffer verrühren und untermengen.','Feta (50 g) zerbröseln und mit der Petersilie (5 g) darüberstreuen.'] },
{ n:'Thunfisch-Bohnen-Salat mit Mais', m:'mittag', t:15, mp:1, ing:[['thunfisch',100],['kidneybohnen',100],['mais',60],['rotezwiebel',30],['zitrone',8],['olivenoel',10]], s:['Kidneybohnen (100 g) und Mais (60 g) in einem Sieb abspülen und abtropfen lassen.','Rote Zwiebel (30 g) fein würfeln.','Mit dem abgetropften Thunfisch (100 g) mischen.','Zitronensaft (8 g) und Olivenöl (10 g) mit Salz und Pfeffer verrühren und untermengen.'] },
{ n:'Halloumi-Salat mit Wassermelone und Minze', m:'mittag', t:18, ing:[['halloumi',110],['wassermelone',120],['salat',60],['minze',3],['olivenoel',10],['zitrone',6]], s:['Halloumi (110 g) in Scheiben schneiden und in der Pfanne je Seite 2-3 Minuten goldbraun braten.','Wassermelone (120 g) würfeln und mit dem Salat (60 g) anrichten.','Warmen Halloumi darauf verteilen.','Mit gehackter Minze (3 g), Olivenöl (10 g) und Zitrone (6 g) beträufeln.'] },
{ n:'Spinat-Erdbeer-Salat mit Ziegenkäse', m:'mittag', t:15, ing:[['spinat',90],['erdbeeren',80],['ziegenkaese',40],['walnuesse',15],['balsamico',8],['olivenoel',8]], s:['Babyspinat (90 g) waschen und mit halbierten Erdbeeren (80 g) auf einem Teller anrichten.','Ziegenkäse (40 g) zerbröckeln und darauf verteilen.','Walnüsse (15 g) grob hacken und darüberstreuen.','Balsamico (8 g) und Olivenöl (8 g) verrühren und darüberträufeln.'] },
{ n:'Kartoffelsalat mit Gurke und Ei', m:'mittag', t:30, mp:1, ing:[['kartoffeln',220],['ei',100],['gewuerzgurke',40],['naturjoghurt',60],['senf',8],['schnittlauch',4]], s:['Kartoffeln (220 g) in Salzwasser 18-20 Minuten garen, etwas abkühlen lassen und würfeln.','Eier (100 g) 8 Minuten hart kochen, pellen und würfeln.','Gewürzgurke (40 g) klein würfeln und mit Kartoffeln und Ei mischen.','Joghurt (60 g) mit Senf (8 g), Salz und Pfeffer verrühren, unterheben und mit Schnittlauch (4 g) bestreuen.'] },
{ n:'Asiatischer Glasnudelsalat mit Hähnchen', m:'mittag', t:24, mp:1, ing:[['glasnudeln',150],['haehnchen',120],['moehren',60],['gurke',60],['sojasauce',12],['limette',6]], s:['Glasnudeln (150 g) mit kochendem Wasser übergießen, 5 Minuten ziehen lassen und kalt abschrecken.','Hähnchen (120 g) in der Pfanne 6-8 Minuten braten und in Streifen schneiden.','Möhre (60 g) und Gurke (60 g) in feine Stifte schneiden.','Sojasauce (12 g) und Limettensaft (6 g) verrühren, alles vermengen und durchziehen lassen.'] },
{ n:'Bunter Bohnensalat mit Feta', m:'mittag', t:18, mp:1, ing:[['kidneybohnen',100],['weissebohnen',100],['paprika',60],['feta',50],['rotezwiebel',30],['olivenoel',10]], s:['Kidney- (100 g) und weiße Bohnen (100 g) abspülen und abtropfen lassen.','Paprika (60 g) und rote Zwiebel (30 g) fein würfeln und untermischen.','Olivenöl (10 g) mit Essig, Salz und Pfeffer verrühren und untermengen.','Feta (50 g) zerbröseln und darüberstreuen.'] },
{ n:'Fitness-Salat mit Ei, Avocado und Kichererbsen', m:'mittag', t:20, ing:[['ei',100],['avocado',60],['kichererbsen',100],['salat',80],['cherrytomaten',60],['olivenoel',8]], s:['Eier (100 g) 8 Minuten hart kochen, pellen und halbieren.','Kichererbsen (100 g) abspülen und in der Pfanne mit etwas Öl und Paprikapulver knusprig rösten.','Salat (80 g), halbierte Cherrytomaten (60 g) und Avocadospalten (60 g) anrichten.','Mit Kichererbsen und Ei belegen und mit Olivenöl (8 g), Salz und Pfeffer abschmecken.'] },
];
