// Frühstück, Teil 10. Von Hand geschrieben.
module.exports = [
{ n:'Porridge mit Birne, Haselnuss und Zimt', m:'fruh', t:10, ing:[['haferflocken',60],['milch',240],['birne',100],['haselnuesse',15],['zimt',2]], s:['Haferflocken (60 g) mit Milch (240 ml) in einen Topf geben und unter Rühren aufkochen.','Bei kleiner Hitze 3-4 Minuten cremig köcheln lassen.','Birne (100 g) würfeln und die Hälfte unterrühren.','In eine Schale füllen, mit der restlichen Birne, gehackten Haselnüssen (15 g) und Zimt (2 g) toppen.'] },
{ n:'Overnight Oats mit Brombeeren und Chia', m:'fruh', t:5, mp:1, ing:[['haferflocken',60],['milch',180],['brombeeren',70],['chiasamen',12],['honig',10]], s:['Haferflocken (60 g), Milch (180 ml), Chiasamen (12 g) und Honig (10 g) in ein Glas geben und gut verrühren.','Zugedeckt über Nacht in den Kühlschrank stellen.','Am Morgen umrühren und mit Brombeeren (70 g) toppen.'] },
{ n:'Skyr-Bowl mit Kirschen und Mandeln', m:'fruh', t:5, ing:[['skyr',200],['kirschen',80],['mandeln',15],['granola',30],['honig',8]], s:['Skyr (200 g) in eine Schale geben und glatt rühren.','Kirschen (80 g) entsteinen und mit den Mandeln (15 g) daraufgeben.','Mit Granola (30 g) bestreuen und mit Honig (8 g) beträufeln.'] },
{ n:'Rührei mit Räucherlachs und Schnittlauch', m:'fruh', t:12, ing:[['ei',150],['raeucherlachs',50],['schnittlauch',4],['vollkornbrot',60],['butter',8]], s:['Eier (150 g) verquirlen, mit Salz und Pfeffer würzen.','Butter (8 g) in der Pfanne schmelzen, Eimasse hineingeben und bei mittlerer Hitze langsam cremig stocken lassen.','Räucherlachs (50 g) in Stücke zupfen und mit dem Schnittlauch (4 g) unterheben.','Mit dem Vollkornbrot (60 g) servieren.'] },
{ n:'Chia-Pudding mit Kaki und Kokos', m:'fruh', t:5, mp:1, ing:[['chiasamen',30],['kokosmilch',110],['milch',90],['physalis',60],['kokosraspel',6]], s:['Chiasamen (30 g) mit Kokosmilch (110 g) und Milch (90 ml) verrühren, 10 Minuten warten und erneut rühren.','Zugedeckt über Nacht quellen lassen, bis eine puddingartige Konsistenz entsteht.','Mit Physalis (60 g) und Kokosraspeln (6 g) toppen.'] },
{ n:'Herzhaftes Frühstücksbrot mit Hüttenkäse und Radieschen', m:'fruh', t:6, ing:[['vollkornbrot',80],['huettenkaese',80],['radieschen',40],['schnittlauch',4]], s:['Hüttenkäse (80 g) auf das Vollkornbrot (80 g) streichen.','Radieschen (40 g) in dünne Scheiben schneiden und auflegen.','Mit Schnittlauch (4 g), Salz und Pfeffer bestreuen.'] },
{ n:'Protein-Pancakes mit Quark und Beeren', m:'fruh', t:18, ing:[['haferflocken',50],['ei',100],['magerquark',80],['proteinpulver',20],['heidelbeeren',60]], s:['Haferflocken (50 g), Eier (100 g), Magerquark (80 g) und Proteinpulver (20 g) zu einem glatten Teig verrühren, kurz quellen lassen.','Portionsweise in einer beschichteten Pfanne bei mittlerer Hitze je Seite 2-3 Minuten backen.','Mit Heidelbeeren (60 g) servieren.'] },
{ n:'Bircher Müsli mit Apfel und Haselnuss', m:'fruh', t:5, mp:1, ing:[['haferflocken',50],['milch',150],['naturjoghurt',80],['apfel',90],['haselnuesse',15]], s:['Haferflocken (50 g) mit Milch (150 ml) und Joghurt (80 g) verrühren.','Apfel (90 g) fein raspeln und unterheben.','Zugedeckt über Nacht ziehen lassen und morgens mit gehackten Haselnüssen (15 g) toppen.'] },
{ n:'Avocado-Ei-Toast mit Chiliflocken', m:'fruh', t:12, ing:[['vollkornbrot',80],['avocado',70],['ei',60],['chiliflocken',1],['zitrone',6]], s:['Avocado (70 g) mit Zitronensaft (6 g), Salz und Pfeffer zerdrücken und auf das getoastete Brot (80 g) streichen.','Ei (60 g) als Spiegelei in etwas Öl braten.','Auf den Toast setzen und mit Chiliflocken (1 g) bestreuen.'] },
{ n:'Quinoa-Porridge mit Apfel und Mandeln', m:'fruh', t:20, ing:[['quinoaflocken',50],['milch',230],['apfel',90],['mandeln',12],['zimt',1]], s:['Quinoaflocken (50 g) mit Milch (230 ml) aufkochen und bei kleiner Hitze 5 Minuten cremig köcheln.','Apfel (90 g) würfeln und unterheben.','Mit gehackten Mandeln (12 g) und Zimt (1 g) toppen.'] },
{ n:'Griechischer Joghurt mit Feige, Honig und Walnuss', m:'fruh', t:6, ing:[['griechjoghurt',200],['feige',60],['walnuesse',15],['honig',10]], s:['Griechischen Joghurt (200 g) in eine Schale geben.','Feige (60 g) in Spalten schneiden und mit gehackten Walnüssen (15 g) daraufgeben.','Mit Honig (10 g) beträufeln.'] },
{ n:'Beeren-Smoothie mit Skyr und Hafer', m:'fruh', t:5, ing:[['skyr',150],['heidelbeeren',80],['himbeeren',50],['milch',150],['haferflocken',20]], s:['Skyr (150 g), Heidelbeeren (80 g), Himbeeren (50 g), Milch (150 ml) und Haferflocken (20 g) in den Mixer geben.','Cremig pürieren.','In ein Glas füllen und sofort trinken.'] },
{ n:'Süßkartoffel-Rösti mit Spiegelei', m:'fruh', t:22, ing:[['suesskartoffel',180],['ei',60],['olivenoel',10],['schnittlauch',4]], s:['Süßkartoffel (180 g) grob raspeln, salzen und kurz ausdrücken.','In Olivenöl (10 g) als flache Rösti bei mittlerer Hitze je Seite 5-6 Minuten goldbraun braten.','Ei (60 g) als Spiegelei braten, daraufsetzen und mit Schnittlauch (4 g) bestreuen.'] },
{ n:'Overnight Oats mit Apfel, Zimt und Walnuss', m:'fruh', t:5, mp:1, ing:[['haferflocken',60],['milch',180],['apfel',90],['walnuesse',15],['zimt',2]], s:['Haferflocken (60 g), Milch (180 ml), geraspelten Apfel (90 g) und Zimt (2 g) in ein Glas geben und verrühren.','Zugedeckt über Nacht kühlen.','Am Morgen umrühren und mit gehackten Walnüssen (15 g) toppen.'] },
{ n:'Rührei mit Tomaten, Feta und Kräutern', m:'fruh', t:14, ing:[['ei',150],['tomaten',80],['feta',40],['petersilie',3],['vollkornbrot',60]], s:['Tomaten (80 g) würfeln und in etwas Öl kurz anbraten.','Verquirlte Eier (150 g) zugeben und bei mittlerer Hitze stocken lassen, dabei Feta (40 g) unterbröseln.','Mit Petersilie (3 g) bestreuen und mit dem Brot (60 g) servieren.'] },
{ n:'Warmer Milchreis mit Beeren und Zimt', m:'fruh', t:35, ing:[['reis',75],['milch',300],['heidelbeeren',70],['zimt',2],['honig',10]], s:['Reis (75 g) mit Milch (300 ml) aufkochen und bei kleiner Hitze unter gelegentlichem Rühren 25-30 Minuten weich und cremig kochen.','Mit Honig (10 g) süßen.','In eine Schale füllen und mit Heidelbeeren (70 g) und Zimt (2 g) servieren.'] },
];
