// Nudelgerichte, Teil 5. Von Hand geschrieben.
module.exports = [
{ n:'Spaghetti mit Rindfleisch-Ragù und Rotwein', m:'abend', t:60, mp:1, ing:[['spaghetti',180],['hackrind',130],['passata',150],['rotwein',40],['moehren',50],['parmesan',20]], s:['Möhre (50 g) fein würfeln und mit dem Hackfleisch (130 g) in etwas Öl krümelig anbraten.','Mit Rotwein (40 g) ablöschen und kurz einkochen lassen.','Passata (150 g) zugeben und bei kleiner Hitze 35-40 Minuten sämig schmoren.','Spaghetti (180 g) nach Packung bissfest kochen, unter das Ragù heben und mit Parmesan (20 g) servieren.'] },
{ n:'Penne mit Lachs, Erbsen und Zitrone', m:'mittag', t:24, mp:1, ing:[['penne',180],['lachs',120],['erbsen',60],['zitrone',10],['kochsahne',80],['dill',3]], s:['Penne (180 g) nach Packung bissfest kochen.','Lachs (120 g) würfeln und in etwas Öl 3-4 Minuten anbraten.','Erbsen (60 g) und Sahne (80 g) zugeben und 3 Minuten köcheln lassen.','Mit den Penne, Zitronensaft (10 g) und Dill (3 g) mischen und abschmecken.'] },
{ n:'Tagliatelle mit Steinpilzen und Parmesan', m:'abend', t:28, ing:[['tagliatelle',180],['wildpilze',120],['kochsahne',100],['zwiebel',40],['parmesan',25],['petersilie',4]], s:['Zwiebel (40 g) würfeln und mit den Pilzen (120 g) in etwas Öl 5-6 Minuten kräftig anbraten.','Mit Sahne (100 g) ablöschen und 3 Minuten cremig köcheln.','Tagliatelle (180 g) bissfest kochen und untermischen.','Mit Parmesan (25 g) und Petersilie (4 g) servieren.'] },
{ n:'Spaghetti Aglio e Olio mit Garnelen', m:'mittag', t:22, ing:[['spaghetti',180],['garnelen',120],['knoblauch',12],['olivenoel',18],['chili',5],['petersilie',4]], s:['Spaghetti (180 g) bissfest kochen und etwas Nudelwasser aufheben.','Knoblauch (12 g) in Scheiben und Chili (5 g) in Olivenöl (18 g) bei mittlerer Hitze goldgelb anbraten.','Garnelen (120 g) zugeben und 2-3 Minuten braten, bis sie rosa sind.','Spaghetti mit etwas Nudelwasser untermengen und mit Petersilie (4 g) servieren.'] },
{ n:'Nudelpfanne mit Hähnchen, Brokkoli und Sahne', m:'abend', t:26, mp:1, ing:[['fusilli',180],['haehnchen',130],['brokkoli',90],['kochsahne',90],['parmesan',20],['knoblauch',6]], s:['Fusilli (180 g) bissfest kochen.','Hähnchen (130 g) würfeln und in etwas Öl 6 Minuten goldbraun braten, Knoblauch (6 g) mitbraten.','Brokkoli (90 g) in Röschen zugeben und 4 Minuten mitbraten.','Sahne (90 g) angießen, kurz köcheln, Nudeln untermengen und mit Parmesan (20 g) servieren.'] },
{ n:'Penne mit Tomaten, Aubergine und Ricotta', m:'mittag', t:28, mp:1, ing:[['penne',180],['aubergine',110],['passata',130],['ricotta',80],['basilikum',5],['parmesan',20]], s:['Aubergine (110 g) würfeln und in etwas Öl 6-8 Minuten goldbraun anbraten.','Passata (130 g) zugeben und 8 Minuten köcheln, dann Ricotta (80 g) unterrühren.','Penne (180 g) bissfest kochen und untermengen.','Mit Basilikum (5 g) und Parmesan (20 g) servieren.'] },
{ n:'Spaghetti Carbonara mit Guanciale', m:'mittag', t:22, ing:[['spaghetti',180],['pancetta',50],['ei',50],['pecorino',30],['pfeffer',3]], s:['Spaghetti (180 g) bissfest kochen und etwas Nudelwasser aufheben.','Pancetta (50 g) in Würfeln knusprig auslassen.','Ei (50 g) mit geriebenem Pecorino (30 g) und Pfeffer (3 g) verquirlen.','Die heißen Spaghetti mit Pancetta mischen, vom Herd nehmen, Eimasse und etwas Nudelwasser cremig unterrühren.'] },
{ n:'Nudelauflauf mit Hackfleisch und Mozzarella', m:'abend', t:45, mp:1, ing:[['penne',160],['hackrind',130],['passata',140],['mozzarella',70],['zwiebel',40]], s:['Penne (160 g) etwas fester als bissfest vorkochen.','Hackfleisch (130 g) mit gewürfelter Zwiebel (40 g) anbraten, Passata (140 g) zugeben und 5 Minuten köcheln.','Nudeln mit der Sauce mischen und in eine Auflaufform geben.','Mozzarella (70 g) darüber verteilen und im Ofen bei 200 Grad 20 Minuten goldbraun überbacken.'] },
{ n:'Gnocchi mit Salbeibutter und Parmesan', m:'abend', t:20, ing:[['gnocchi',220],['butter',18],['salbei',2],['parmesan',30],['cherrytomaten',60]], s:['Gnocchi (220 g) in kochendem Salzwasser garen, bis sie oben schwimmen, dann abgießen.','Butter (18 g) mit Salbei (2 g) in der Pfanne aufschäumen lassen.','Gnocchi und halbierte Cherrytomaten (60 g) zugeben und 3-4 Minuten anbraten.','Mit Parmesan (30 g) bestreut servieren.'] },
{ n:'Spaghetti mit Thunfisch, Kapern und Zitrone', m:'mittag', t:20, mp:1, ing:[['spaghetti',180],['thunfisch',100],['kapern',12],['zitrone',10],['olivenoel',12],['petersilie',4]], s:['Spaghetti (180 g) bissfest kochen.','Thunfisch (100 g) mit Kapern (12 g) und Olivenöl (12 g) in der Pfanne kurz erwärmen.','Mit Zitronensaft (10 g), Salz und Pfeffer abschmecken.','Spaghetti untermengen und mit Petersilie (4 g) servieren.'] },
{ n:'Cremige Nudeln mit Champignons und Spinat', m:'mittag', t:24, ing:[['penne',180],['champignons',100],['spinat',60],['frischkaese',50],['zwiebel',40],['parmesan',15]], s:['Penne (180 g) bissfest kochen.','Champignons (100 g) und Zwiebel (40 g) in etwas Öl 5 Minuten anbraten.','Spinat (60 g) zugeben, zusammenfallen lassen, dann Frischkäse (50 g) und einen Schuss Nudelwasser cremig einrühren.','Nudeln untermengen und mit Parmesan (15 g) servieren.'] },
{ n:'Vollkornnudeln mit Kichererbsen-Tomatensauce', m:'mittag', t:26, mp:1, ing:[['vollkornnudeln',180],['kichererbsen',110],['passata',150],['knoblauch',6],['zwiebel',40],['olivenoel',8]], s:['Zwiebel (40 g) und Knoblauch (6 g) in Olivenöl (8 g) glasig andünsten.','Kichererbsen (110 g) und Passata (150 g) zugeben und 10 Minuten sämig köcheln.','Vollkornnudeln (180 g) bissfest kochen.','Mit der Sauce vermengen und abschmecken.'] },
{ n:'Spaghetti mit Muscheln und Weißwein', m:'abend', t:28, mp:1, ing:[['spaghetti',180],['muscheln',220],['weisswein',50],['knoblauch',8],['petersilie',5],['olivenoel',12]], s:['Spaghetti (180 g) bissfest kochen.','Knoblauch (8 g) in Olivenöl (12 g) anbraten.','Muscheln (220 g) zugeben, mit Weißwein (50 g) ablöschen und zugedeckt 4-5 Minuten dämpfen, bis sich die Schalen öffnen (geschlossene aussortieren).','Spaghetti und Petersilie (5 g) untermengen.'] },
{ n:'Penne all’Arrabbiata scharf', m:'mittag', t:22, mp:1, ing:[['penne',180],['passata',160],['knoblauch',8],['chili',6],['olivenoel',12],['pecorino',20]], s:['Knoblauch (8 g) und Chili (6 g) in Olivenöl (12 g) bei mittlerer Hitze anbraten.','Passata (160 g) zugeben und 10 Minuten einkochen, mit Salz abschmecken.','Penne (180 g) bissfest kochen und untermengen.','Mit Pecorino (20 g) servieren.'] },
{ n:'Nudeln mit Gorgonzola-Sahne und Walnuss', m:'abend', t:22, ing:[['penne',180],['bergkaese',50],['kochsahne',90],['walnuesse',15],['petersilie',3]], s:['Penne (180 g) bissfest kochen.','Bergkäse (50 g) mit Sahne (90 g) bei kleiner Hitze cremig schmelzen.','Nudeln untermengen und mit etwas Nudelwasser sämig abschmecken.','Mit gehackten Walnüssen (15 g) und Petersilie (3 g) servieren.'] },
{ n:'Lachs-Spinat-Nudeln in Zitronensahne', m:'mittag', t:24, mp:1, ing:[['tagliatelle',180],['lachs',120],['spinat',80],['zitrone',8],['kochsahne',80],['dill',3]], s:['Tagliatelle (180 g) bissfest kochen.','Lachs (120 g) würfeln und 3-4 Minuten anbraten.','Spinat (80 g) zugeben, zusammenfallen lassen, dann Sahne (80 g) und Zitronensaft (8 g) angießen und kurz köcheln.','Nudeln und Dill (3 g) untermengen.'] },
];
