// Vegetarische Hauptgerichte, Teil 7. Von Hand geschrieben.
module.exports = [
{ n:'Ofengemüse mit Halloumi und Kräuterjoghurt', m:'abend', t:35, mp:1, ing:[['zucchini',90],['paprika',80],['kartoffeln',150],['halloumi',110],['naturjoghurt',60],['olivenoel',12]], s:['Kartoffeln (150 g), Zucchini (90 g) und Paprika (80 g) in Stücke schneiden, mit Olivenöl (12 g), Salz und Pfeffer mischen und bei 200 Grad 25 Minuten rösten.','Halloumi (110 g) in Scheiben schneiden und in der Pfanne je Seite 2-3 Minuten goldbraun braten.','Joghurt (60 g) mit gehackten Kräutern, Salz und Pfeffer verrühren.','Ofengemüse mit Halloumi anrichten und den Kräuterjoghurt dazu reichen.'] },
{ n:'Gefüllte Paprika mit Reis und Feta', m:'abend', t:45, mp:1, ing:[['paprika',180],['reis',120],['feta',60],['tomaten',70],['zwiebel',40],['olivenoel',10]], s:['Reis (120 g) garen. Zwiebel (40 g) und Tomaten (70 g) würfeln und in Olivenöl (10 g) andünsten, mit dem Reis mischen.','Paprika (180 g) oben aufschneiden, entkernen und mit der Reismischung füllen.','Feta (60 g) darüberbröseln.','In einer Form bei 190 Grad 25 Minuten backen, bis die Paprika weich ist.'] },
{ n:'Kürbisrisotto mit Salbei und Parmesan', m:'abend', t:35, ing:[['risottoreis',150],['kuerbis',150],['bruehe',400],['parmesan',30],['zwiebel',40],['butter',12]], s:['Zwiebel (40 g) in der Butter (12 g) glasig andünsten, Risottoreis (150 g) zugeben und kurz anschwitzen.','Kürbis (150 g) fein würfeln, zugeben und die heiße Brühe (400 ml) nach und nach kellenweise angießen, dabei rühren.','Nach etwa 18 Minuten ist der Reis cremig und schlotzig.','Parmesan (30 g) und Salbei unterrühren und abschmecken.'] },
{ n:'Cannelloni mit Spinat, Ricotta und Pinienkernen', m:'abend', t:50, mp:1, ing:[['cannelloni',120],['spinat',120],['ricotta',120],['passata',150],['pinienkerne',15],['parmesan',25]], s:['Spinat (120 g) kurz andünsten, ausdrücken und hacken, mit Ricotta (120 g) und gerösteten Pinienkernen (15 g) verrühren, salzen und pfeffern.','Die Cannelloni (120 g) mit der Masse füllen.','In eine Form mit etwas Passata legen, restliche Passata (150 g) darübergeben.','Mit Parmesan (25 g) bestreuen und bei 190 Grad 30 Minuten überbacken.'] },
{ n:'Süßkartoffel-Kichererbsen-Curry', m:'abend', t:35, mp:1, ing:[['suesskartoffel',180],['kichererbsen',130],['kokosmilch',120],['passata',80],['currypul',4],['reis',150]], s:['Reis (150 g) garen.','Süßkartoffel (180 g) würfeln und in etwas Öl 5 Minuten anbraten, Currypulver (4 g) mitrösten.','Kichererbsen (130 g), Kokosmilch (120 g) und Passata (80 g) zugeben.','Zugedeckt 15-18 Minuten köcheln, bis die Süßkartoffel weich ist, und mit Reis servieren.'] },
{ n:'Gemüse-Lasagne mit Zucchini und Aubergine', m:'abend', t:60, mp:1, ing:[['lasagneplatten',120],['zucchini',90],['aubergine',90],['passata',180],['mozzarella',80],['parmesan',25]], s:['Zucchini (90 g) und Aubergine (90 g) würfeln und in etwas Öl kräftig anbraten, Passata (180 g) zugeben und 5 Minuten köcheln.','In einer Form abwechselnd Gemüsesauce und Lasagneplatten (120 g) schichten.','Mit Mozzarella (80 g) und Parmesan (25 g) abschließen.','Bei 190 Grad 35 Minuten backen, bis die Oberfläche goldbraun ist.'] },
{ n:'Shakshuka mit Feta und Paprika', m:'mittag', t:28, ing:[['ei',150],['passata',150],['paprika',90],['zwiebel',40],['feta',50],['fladenbrot',60]], s:['Zwiebel (40 g) und Paprika (90 g) in etwas Öl 5 Minuten andünsten.','Passata (150 g) zugeben, mit Kreuzkümmel, Salz und Pfeffer würzen und 5 Minuten köcheln.','Mulden in die Sauce drücken, die Eier (150 g) hineingleiten lassen und bei kleiner Hitze zugedeckt 6-8 Minuten stocken lassen.','Mit Feta (50 g) bestreuen und mit Fladenbrot (60 g) servieren.'] },
{ n:'Linsen-Dal mit Spinat und Naan', m:'abend', t:35, mp:1, ing:[['rotelinsen',150],['spinat',80],['kokosmilch',90],['tomaten',80],['currypul',4],['naanbrot',90]], s:['Zwiebel und Currypulver (4 g) in etwas Öl anrösten, rote Linsen (150 g) und gewürfelte Tomaten (80 g) zugeben.','Mit Wasser bedeckt 15 Minuten weich kochen, dabei gelegentlich rühren.','Spinat (80 g) und Kokosmilch (90 g) unterrühren und 3 Minuten köcheln.','Naan (90 g) kurz erwärmen und dazu servieren.'] },
{ n:'Gnocchi-Pfanne mit Tomaten und Mozzarella', m:'abend', t:25, ing:[['gnocchi',220],['cherrytomaten',100],['mozzarella',70],['basilikum',5],['knoblauch',6],['olivenoel',10]], s:['Gnocchi (220 g) in Olivenöl (10 g) bei mittlerer Hitze 6-8 Minuten goldbraun anbraten.','Knoblauch (6 g) und halbierte Cherrytomaten (100 g) zugeben und 4 Minuten mitbraten.','Mozzarella (70 g) in Stücken darauf verteilen und zugedeckt schmelzen lassen.','Mit Basilikum (5 g) servieren.'] },
{ n:'Blumenkohl-Kichererbsen-Curry mit Spinat', m:'abend', t:34, mp:1, ing:[['blumenkohl',160],['kichererbsen',90],['spinat',60],['kokosmilch',110],['currypul',4],['reis',150]], s:['Reis (150 g) garen.','Blumenkohl (160 g) in Röschen teilen und in etwas Öl mit dem Currypulver (4 g) anbraten.','Kichererbsen (90 g) und Kokosmilch (110 g) zugeben und 12 Minuten köcheln, bis der Blumenkohl weich ist.','Spinat (60 g) unterrühren, zusammenfallen lassen und mit Reis servieren.'] },
{ n:'Käsespätzle mit Röstzwiebeln', m:'abend', t:30, ing:[['spaetzle',200],['bergkaese',70],['zwiebel',60],['butter',15],['schnittlauch',4]], s:['Zwiebel (60 g) in Ringe schneiden und in der Butter (15 g) langsam goldbraun rösten.','Spätzle (200 g) heiß mit dem geriebenen Bergkäse (70 g) abwechselnd in eine Schüssel schichten, damit der Käse schmilzt.','Kurz durchziehen lassen.','Mit Röstzwiebeln und Schnittlauch (4 g) toppen.'] },
{ n:'Ratatouille mit Kräuterbaguette', m:'abend', t:40, mp:1, ing:[['zucchini',90],['aubergine',90],['paprika',80],['passata',150],['knoblauch',6],['baguette',80]], s:['Zucchini (90 g), Aubergine (90 g) und Paprika (80 g) würfeln und in etwas Öl mit Knoblauch (6 g) anbraten.','Passata (150 g) zugeben, mit Kräutern der Provence würzen und 20 Minuten sanft schmoren.','Baguette (80 g) aufschneiden und kurz aufbacken.','Ratatouille abschmecken und mit dem Baguette servieren.'] },
{ n:'Pilz-Stroganoff mit Bandnudeln', m:'abend', t:30, ing:[['champignons',160],['bandnudeln',180],['kochsahne',100],['zwiebel',40],['senf',6],['petersilie',4]], s:['Bandnudeln (180 g) bissfest kochen.','Champignons (160 g) und Zwiebel (40 g) in etwas Öl 6 Minuten kräftig anbraten.','Sahne (100 g) und Senf (6 g) zugeben und 3 Minuten cremig köcheln, salzen und pfeffern.','Mit den Nudeln und Petersilie (4 g) servieren.'] },
{ n:'Ofen-Feta mit Paprika, Oliven und Fusilli', m:'abend', t:35, mp:1, ing:[['feta',120],['cherrytomaten',110],['paprika',60],['oliven',25],['fusilli',180],['olivenoel',15]], s:['Feta (120 g) in eine Form legen, mit Cherrytomaten (110 g), Paprika (60 g), Oliven (25 g) und Olivenöl (15 g) umgeben und bei 200 Grad 25 Minuten backen.','Fusilli (180 g) bissfest kochen.','Den weichen Feta mit dem Gemüse zu einer cremigen Sauce zerdrücken.','Nudeln untermengen und abschmecken.'] },
{ n:'Linsen-Bratlinge mit Möhre und Kartoffelpüree', m:'abend', t:38, mp:1, ing:[['linsen',130],['moehren',70],['haferflocken',30],['ei',50],['kartoffeln',180],['milch',60]], s:['Linsen (130 g) weich kochen und abtropfen lassen.','Mit geraspelter Möhre (70 g), Haferflocken (30 g) und Ei (50 g) zu einer Masse verkneten, würzen und zu Bratlingen formen.','In etwas Öl je Seite 3-4 Minuten goldbraun braten.','Kartoffeln (180 g) kochen und mit Milch (60 ml) zu Püree stampfen, dazu servieren.'] },
{ n:'Halloumi-Zucchini-Spieße mit Zitronen-Bulgur', m:'abend', t:30, mp:1, ing:[['halloumi',110],['zucchini',80],['cherrytomaten',60],['bulgur',150],['olivenoel',12],['zitrone',8]], s:['Bulgur (150 g) mit kochendem Wasser übergießen, 12 Minuten quellen lassen und mit Zitrone (8 g) und Öl abschmecken.','Halloumi (110 g), Zucchini (80 g) und Cherrytomaten (60 g) abwechselnd auf Spieße stecken.','Mit Olivenöl (12 g) bestreichen und in der Grillpfanne rundum 6-8 Minuten braten.','Mit dem Zitronen-Bulgur servieren.'] },
];
