// Reis- und Bowl-Gerichte, Teil 3. Von Hand geschrieben.
module.exports = [
{ n:'Teriyaki-Hähnchen-Bowl mit Edamame', m:'mittag', t:28, mp:1, ing:[['haehnchen',140],['reis',160],['edamame',60],['moehren',50],['teriyakisauce',20],['sesam',4]], s:['Reis (160 g) garen und Edamame (60 g) in Salzwasser 4 Minuten kochen.','Hähnchen (140 g) würfeln und in der Pfanne 6-8 Minuten goldbraun braten, mit Teriyakisauce (20 g) glasieren.','Möhre (50 g) in feine Stifte schneiden.','Reis in eine Schale geben, mit Hähnchen, Edamame und Möhre anrichten und mit Sesam (4 g) bestreuen.'] },
{ n:'Lachs-Poke-Bowl mit Avocado', m:'mittag', t:22, ing:[['lachs',120],['reis',160],['avocado',60],['gurke',50],['sojasauce',12],['sesam',4]], s:['Reis (160 g) garen und lauwarm abkühlen lassen.','Lachs (120 g, sehr frisch) in Würfel schneiden und mit Sojasauce (12 g) marinieren.','Avocado (60 g) und Gurke (50 g) in Scheiben bzw. Würfel schneiden.','Reis in eine Schale geben und mit Lachs, Avocado, Gurke und Sesam (4 g) anrichten.'] },
{ n:'Falafel-Bowl mit Hummus und Bulgur', m:'mittag', t:28, mp:1, ing:[['kichererbsen',140],['bulgur',150],['hummus',50],['tomaten',60],['gurke',50],['petersilie',5]], s:['Bulgur (150 g) mit kochendem Wasser übergießen und 12 Minuten quellen lassen.','Kichererbsen (140 g) mit Gewürzen zu Falafel formen und in heißem Öl rundum goldbraun braten.','Tomaten (60 g) und Gurke (50 g) würfeln.','Bulgur in eine Schale geben, mit Falafel, Gemüse und Hummus (50 g) anrichten und mit Petersilie (5 g) bestreuen.'] },
{ n:'Burrito-Bowl mit Hähnchen und Bohnen', m:'mittag', t:26, mp:1, ing:[['haehnchen',130],['reis',150],['kidneybohnen',70],['mais',50],['guacamole',40],['reibekaese',30]], s:['Reis (150 g) garen und Kidneybohnen (70 g) mit Mais (50 g) abspülen und erwärmen.','Hähnchen (130 g) mit Paprikapulver und Kreuzkümmel würzen und 6-8 Minuten braten.','Reis in eine Schale geben und mit Hähnchen, Bohnen und Mais anrichten.','Mit Guacamole (40 g) und geriebenem Käse (30 g) toppen.'] },
{ n:'Tofu-Gemüse-Bowl mit Erdnusssauce', m:'mittag', t:28, mp:1, ing:[['tofu',140],['reis',150],['brokkoli',80],['moehren',50],['erdnussbutter',20],['sojasauce',10]], s:['Reis (150 g) garen. Tofu (140 g) würfeln und in etwas Öl rundum knusprig braten.','Brokkoli (80 g) und Möhre (50 g) 5 Minuten dämpfen.','Erdnussbutter (20 g) mit Sojasauce (10 g) und etwas warmem Wasser zu einer Sauce verrühren.','Reis, Tofu und Gemüse anrichten und mit der Erdnusssauce beträufeln.'] },
{ n:'Rindfleisch-Bulgogi-Bowl', m:'abend', t:28, mp:1, ing:[['rindersteak',140],['reis',160],['moehren',50],['spinat',50],['sojasauce',14],['sesam',4]], s:['Rindfleisch (140 g) in feine Streifen schneiden und mit Sojasauce (14 g), etwas Zucker und Knoblauch 10 Minuten marinieren.','Reis (160 g) garen.','Das Fleisch in einer sehr heißen Pfanne 3-4 Minuten scharf anbraten, Spinat (50 g) kurz zusammenfallen lassen.','Reis mit Fleisch, Spinat und geraspelter Möhre (50 g) anrichten und mit Sesam (4 g) bestreuen.'] },
{ n:'Mittelmeer-Bowl mit Halloumi und Couscous', m:'mittag', t:26, mp:1, ing:[['halloumi',110],['couscous',150],['tomaten',60],['gurke',50],['oliven',25],['olivenoel',10]], s:['Couscous (150 g) mit kochendem Wasser übergießen, 5 Minuten quellen lassen und mit Olivenöl (10 g) auflockern.','Halloumi (110 g) in Scheiben je Seite 2-3 Minuten goldbraun braten.','Tomaten (60 g) und Gurke (50 g) würfeln.','Couscous in eine Schale geben und mit Halloumi, Gemüse und Oliven (25 g) anrichten.'] },
{ n:'Thai-Curry-Bowl mit Garnelen', m:'mittag', t:26, mp:1, ing:[['garnelen',120],['reis',150],['kokosmilch',110],['paprika',60],['currypaste',15],['koriandergruen',4]], s:['Reis (150 g) garen.','Currypaste (15 g) in etwas Öl anrösten, bis sie duftet.','Garnelen (120 g) und Paprikastreifen (60 g) zugeben und 2 Minuten mitbraten, dann Kokosmilch (110 g) angießen und 4 Minuten köcheln.','Mit Reis in einer Schale anrichten und mit Koriander (4 g) bestreuen.'] },
{ n:'Hähnchen-Quinoa-Bowl mit Avocado', m:'mittag', t:28, mp:1, ing:[['haehnchen',130],['quinoa',150],['avocado',60],['cherrytomaten',60],['mais',40],['limette',6]], s:['Quinoa (150 g) abspülen und in der doppelten Menge Wasser 15 Minuten garen.','Hähnchen (130 g) würzen und in der Pfanne 6-8 Minuten goldbraun braten, dann in Streifen schneiden.','Avocado (60 g) in Spalten und Cherrytomaten (60 g) halbieren.','Quinoa mit Hähnchen, Avocado, Tomaten und Mais (40 g) anrichten und mit Limette (6 g) beträufeln.'] },
{ n:'Vegane Buddha-Bowl mit Kichererbsen', m:'mittag', t:30, mp:1, ing:[['kichererbsen',130],['suesskartoffel',150],['quinoa',140],['rotkohl',50],['tahin',18],['spinat',40]], s:['Süßkartoffel (150 g) würfeln, mit Kichererbsen (130 g) und etwas Öl mischen und bei 200 Grad 22 Minuten rösten.','Quinoa (140 g) 15 Minuten garen.','Rotkohl (50 g) fein hobeln und Spinat (40 g) waschen.','Alles in einer Schale anrichten und mit Tahin (18 g), etwas Wasser und Zitrone verrührt beträufeln.'] },
{ n:'Sushi-Bowl mit Thunfisch und Gurke', m:'mittag', t:22, ing:[['thunfisch',120],['reis',160],['gurke',50],['avocado',50],['sojasauce',12],['nori',3]], s:['Sushireis bzw. Reis (160 g) garen, mit etwas Reisessig mischen und abkühlen lassen.','Thunfisch (120 g, sehr frisch) würfeln und mit Sojasauce (12 g) marinieren.','Gurke (50 g) und Avocado (50 g) in Scheiben schneiden.','Reis in eine Schale geben, mit Thunfisch, Gurke, Avocado und in Streifen geschnittenem Nori (3 g) anrichten.'] },
{ n:'Chili-sin-Carne-Bowl mit Reis', m:'mittag', t:30, mp:1, ing:[['kidneybohnen',130],['mais',60],['passata',120],['reis',150],['paprika',60],['reibekaese',30]], s:['Reis (150 g) garen.','Paprika (60 g) würfeln und mit Kidneybohnen (130 g) und Mais (60 g) in etwas Öl anbraten.','Passata (120 g) zugeben, mit Kreuzkümmel und Paprikapulver würzen und 12 Minuten köcheln.','Mit Reis in einer Schale anrichten und mit Käse (30 g) bestreuen.'] },
{ n:'Hähnchen-Reis-Bowl süß-sauer', m:'mittag', t:26, mp:1, ing:[['haehnchen',140],['reis',160],['paprika',60],['ananas',60],['sojasauce',12],['tomatenmark',15]], s:['Reis (160 g) garen.','Hähnchen (140 g) würfeln und in der Pfanne 6-8 Minuten braten.','Paprika (60 g) und Ananas (60 g) zugeben, kurz mitbraten.','Tomatenmark (15 g), Sojasauce (12 g), etwas Zucker und Essig zu einer süß-sauren Sauce verrühren, angießen und mit Reis servieren.'] },
{ n:'Falafel-Reis-Bowl mit Rotkohl', m:'mittag', t:28, mp:1, ing:[['kichererbsen',140],['reis',150],['rotkohl',60],['moehren',50],['tahin',18],['petersilie',4]], s:['Reis (150 g) garen.','Kichererbsen (140 g) zu Falafel formen und in heißem Öl rundum goldbraun braten.','Rotkohl (60 g) fein hobeln und Möhre (50 g) raspeln.','Reis mit Falafel, Rotkohl und Möhre anrichten und mit Tahin (18 g) und Petersilie (4 g) toppen.'] },
{ n:'Garnelen-Avocado-Bowl mit Quinoa', m:'mittag', t:24, ing:[['garnelen',120],['quinoa',150],['avocado',60],['cherrytomaten',60],['limette',6],['olivenoel',8]], s:['Quinoa (150 g) abspülen und 15 Minuten garen.','Garnelen (120 g) in Olivenöl (8 g) 2-3 Minuten braten, bis sie rosa sind.','Avocado (60 g) in Spalten und Cherrytomaten (60 g) halbieren.','Quinoa mit Garnelen, Avocado und Tomaten anrichten und mit Limette (6 g) beträufeln.'] },
{ n:'Gemüse-Reis-Bowl mit Spiegelei', m:'mittag', t:24, ing:[['reis',160],['brokkoli',80],['moehren',60],['erbsen',50],['ei',60],['sojasauce',10]], s:['Reis (160 g) garen.','Brokkoli (80 g), Möhre (60 g) und Erbsen (50 g) in etwas Öl in der Pfanne 5-6 Minuten braten, Reis untermengen.','Mit Sojasauce (10 g) würzen.','Ei (60 g) als Spiegelei braten und auf die Bowl setzen.'] },
];
