// Suppen & Eintöpfe, Teil 4. Von Hand geschrieben.
module.exports = [
{ n:'Cremige Tomatensuppe mit Basilikum', m:'mittag', t:25, mp:1, ing:[['passata',200],['moehren',50],['zwiebel',40],['kochsahne',60],['basilikum',5],['baguette',60]], s:['Zwiebel (40 g) und Möhre (50 g) fein würfeln und in etwas Öl 4 Minuten andünsten.','Passata (200 g) und einen Schuss Wasser zugeben und 8 Minuten köcheln, dann fein pürieren.','Sahne (60 g) und gehacktes Basilikum (5 g) einrühren, salzen und pfeffern.','Mit dem Baguette (60 g) servieren.'] },
{ n:'Kürbis-Ingwer-Suppe mit Kokos', m:'mittag', t:30, mp:1, ing:[['kuerbis',220],['kokosmilch',100],['zwiebel',40],['ingwer',6],['bruehe',300],['kuerbiskerne',10]], s:['Kürbis (220 g) und Zwiebel (40 g) würfeln und in etwas Öl 5 Minuten anbraten.','Mit Brühe (300 ml) aufgießen und 15 Minuten weich kochen, dann fein pürieren.','Kokosmilch (100 g) und geriebenen Ingwer (6 g) unterrühren und abschmecken.','Mit gerösteten Kürbiskernen (10 g) toppen.'] },
{ n:'Klare Gemüsebrühe mit Nudeln', m:'mittag', t:25, ing:[['bruehe',400],['nudeln',80],['moehren',60],['erbsen',40],['petersilie',4]], s:['Brühe (400 ml) erhitzen.','Möhre (60 g) in feine Scheiben schneiden und mit den Erbsen (40 g) 6 Minuten garen.','Nudeln (80 g) zugeben und bissfest kochen.','Mit Petersilie (4 g) bestreut servieren.'] },
{ n:'Brokkoli-Mandel-Cremesuppe mit Parmesan', m:'mittag', t:28, mp:1, ing:[['brokkoli',210],['kartoffeln',80],['zwiebel',40],['parmesan',25],['bruehe',330],['mandeln',15]], s:['Zwiebel (40 g) andünsten, Brokkoli (210 g) und Kartoffel (80 g) würfeln und zugeben.','Mit Brühe (330 ml) aufgießen und 15 Minuten weich kochen, dann fein pürieren.','Parmesan (25 g) einrühren und abschmecken.','Mit gehackten, gerösteten Mandeln (15 g) servieren.'] },
{ n:'Minestrone mit Kichererbsen und Pesto', m:'mittag', t:35, mp:1, ing:[['kichererbsen',110],['nudeln',60],['moehren',60],['sellerie',50],['passata',120],['pesto',15]], s:['Möhre (60 g) und Sellerie (50 g) würfeln und in etwas Öl andünsten.','Passata (120 g) und Wasser zugeben und 10 Minuten köcheln.','Kichererbsen (110 g) und Nudeln (60 g) zugeben und weitere 10 Minuten garen.','In Teller füllen und je einen Klecks Pesto (15 g) daraufgeben.'] },
{ n:'Linsensuppe mit Würstchen', m:'abend', t:40, mp:1, ing:[['linsen',150],['moehren',70],['kartoffeln',100],['wiener',80],['zwiebel',40],['bruehe',380]], s:['Zwiebel (40 g) und Möhre (70 g) würfeln und andünsten.','Linsen (150 g), gewürfelte Kartoffel (100 g) und Brühe (380 ml) zugeben und 25 Minuten weich kochen.','Mit Salz, Pfeffer und einem Spritzer Essig abschmecken.','Wiener (80 g) in Scheiben zugeben und 5 Minuten mitwärmen.'] },
{ n:'Möhren-Ingwer-Suppe mit Orange', m:'mittag', t:28, mp:1, ing:[['moehren',220],['orange',60],['zwiebel',40],['ingwer',6],['bruehe',320],['kochsahne',40]], s:['Möhre (220 g) und Zwiebel (40 g) würfeln und in etwas Öl andünsten.','Mit Brühe (320 ml) aufgießen und 15 Minuten weich kochen, dann fein pürieren.','Orangensaft (60 g), geriebenen Ingwer (6 g) und Sahne (40 g) einrühren.','Abschmecken und servieren.'] },
{ n:'Erbsensuppe mit Minze', m:'mittag', t:25, mp:1, ing:[['erbsen',200],['kartoffeln',70],['zwiebel',40],['minze',3],['bruehe',330],['kochsahne',40]], s:['Zwiebel (40 g) andünsten, gewürfelte Kartoffel (70 g) zugeben.','Mit Brühe (330 ml) aufgießen und 10 Minuten kochen, Erbsen (200 g) zugeben und 3 Minuten mitkochen.','Fein pürieren.','Mit Minze (3 g) und Sahne (40 g) abschmecken.'] },
{ n:'Gulaschsuppe mit Rindfleisch', m:'abend', t:70, mp:1, ing:[['rindersteak',140],['kartoffeln',120],['paprika',80],['zwiebel',50],['paprikapulver',4],['bruehe',350]], s:['Rindfleisch (140 g) würfeln und mit der Zwiebel (50 g) rundum kräftig anbraten.','Vom Herd Paprikapulver (4 g) einrühren, dann Paprika (80 g) und Brühe (350 ml) zugeben.','Zugedeckt 40 Minuten schmoren.','Gewürfelte Kartoffel (120 g) zugeben und weitere 20 Minuten weich kochen.'] },
{ n:'Blumenkohl-Curry-Cremesuppe mit Kokos', m:'mittag', t:28, mp:1, ing:[['blumenkohl',210],['kartoffeln',70],['zwiebel',40],['kokosmilch',70],['bruehe',300],['currypul',3]], s:['Zwiebel (40 g) mit Currypulver (3 g) andünsten, Blumenkohl (210 g) und Kartoffel (70 g) zugeben.','Mit Brühe (300 ml) aufgießen und 15 Minuten weich kochen, dann fein pürieren.','Kokosmilch (70 g) einrühren und abschmecken.','Heiß servieren.'] },
{ n:'Asiatische Hühnersuppe mit Nudeln', m:'mittag', t:35, mp:1, ing:[['haehnchen',120],['mienudeln',80],['moehren',50],['fruehlingszwiebel',20],['ingwer',6],['bruehe',380]], s:['Hähnchen (120 g) mit dem Ingwer (6 g) in der Brühe (380 ml) 15 Minuten gar ziehen lassen, dann herausnehmen und zerzupfen.','Möhre (50 g) in feine Stifte schneiden und in der Brühe 4 Minuten garen.','Mie-Nudeln (80 g) zugeben und 3 Minuten kochen.','Hähnchen zurückgeben und mit Frühlingszwiebeln (20 g) servieren.'] },
{ n:'Kartoffelsuppe mit Röstzwiebeln', m:'mittag', t:35, mp:1, ing:[['kartoffeln',220],['moehren',60],['lauch',50],['zwiebel',40],['bruehe',380],['roestzwiebel',15]], s:['Zwiebel (40 g), Möhre (60 g) und Lauch (50 g) würfeln und andünsten, Kartoffeln (220 g) zugeben.','Mit Brühe (380 ml) aufgießen und 20 Minuten weich kochen.','Etwa zur Hälfte pürieren, damit die Suppe sämig, aber noch stückig ist.','Mit Röstzwiebeln (15 g) servieren.'] },
{ n:'Scharfe Kokos-Linsensuppe', m:'mittag', t:30, mp:1, ing:[['rotelinsen',150],['kokosmilch',100],['moehren',60],['tomatenmark',15],['currypul',4],['bruehe',300]], s:['Möhre (60 g) würfeln und mit Tomatenmark (15 g) und Currypulver (4 g) kurz anrösten.','Rote Linsen (150 g), Kokosmilch (100 g) und Brühe (300 ml) zugeben.','15 Minuten weich köcheln lassen.','Leicht pürieren und scharf abschmecken.'] },
{ n:'Zucchini-Minz-Suppe mit Ziegenkäse', m:'mittag', t:26, mp:1, ing:[['zucchini',210],['kartoffeln',70],['zwiebel',40],['ziegenkaese',45],['bruehe',320],['minze',3]], s:['Zwiebel (40 g) andünsten, Zucchini (210 g) und Kartoffel (70 g) würfeln und zugeben.','Mit Brühe (320 ml) aufgießen und 12 Minuten weich kochen, dann fein pürieren.','Mit Minze (3 g) abschmecken.','Ziegenkäse (45 g) zerbröckeln und in die heiße Suppe geben.'] },
{ n:'Bohnensuppe mit Speck und Möhre', m:'abend', t:40, mp:1, ing:[['weissebohnen',170],['bacon',40],['moehren',70],['kartoffeln',100],['zwiebel',40],['bruehe',350]], s:['Bacon (40 g) und Zwiebel (40 g) würfeln und im Topf anbraten.','Möhre (70 g) und Kartoffel (100 g) würfeln, zugeben und kurz mitbraten.','Weiße Bohnen (170 g) und Brühe (350 ml) angießen und 20 Minuten weich kochen.','Einen Teil zerdrücken, damit die Suppe sämig wird, und abschmecken.'] },
{ n:'Champignon-Rahmsuppe', m:'mittag', t:28, ing:[['champignons',200],['zwiebel',40],['kochsahne',60],['bruehe',320],['petersilie',4],['butter',10]], s:['Champignons (200 g) und Zwiebel (40 g) in der Butter (10 g) 6 Minuten kräftig anbraten, ein paar Scheiben für die Deko beiseite legen.','Mit Brühe (320 ml) aufgießen und 8 Minuten köcheln, dann teilweise pürieren.','Sahne (60 g) einrühren und abschmecken.','Mit den Pilzscheiben und Petersilie (4 g) servieren.'] },
];
