// Aufläufe & Gratins, Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Kartoffelgratin mit Sahne und Muskat', m:'abend', t:60, mp:1, ing:[['kartoffeln',280],['kochsahne',120],['bergkaese',60],['knoblauch',6],['muskat',1]], s:['Kartoffeln (280 g) in dünne Scheiben hobeln und dachziegelartig in eine gefettete Form schichten.','Sahne (120 g) mit gepresstem Knoblauch (6 g), Muskat (1 g), Salz und Pfeffer verrühren und über die Kartoffeln gießen.','Mit geriebenem Bergkäse (60 g) bestreuen.','Bei 190 Grad 45 Minuten backen, bis die Kartoffeln weich und die Kruste goldbraun ist.'] },
{ n:'Nudelauflauf mit Schinken und Erbsen', m:'abend', t:45, mp:1, ing:[['nudeln',180],['kochschinken',70],['erbsen',60],['kochsahne',100],['reibekaese',60],['ei',50]], s:['Nudeln (180 g) etwas fester als bissfest kochen.','Mit gewürfeltem Schinken (70 g), Erbsen (60 g), Sahne (100 g) und verquirltem Ei (50 g) mischen, salzen und pfeffern.','In eine Auflaufform geben und mit Käse (60 g) bestreuen.','Bei 190 Grad 25 Minuten goldbraun überbacken.'] },
{ n:'Brokkoli-Hähnchen-Auflauf', m:'abend', t:45, mp:1, ing:[['haehnchen',150],['brokkoli',150],['reis',150],['kochsahne',100],['reibekaese',60],['zwiebel',40]], s:['Reis (150 g) garen. Hähnchen (150 g) würfeln und mit Zwiebel (40 g) 6 Minuten anbraten.','Brokkoli (150 g) in Röschen 4 Minuten blanchieren.','Reis, Hähnchen und Brokkoli in eine Form geben, mit Sahne (100 g) übergießen.','Mit Käse (60 g) bestreuen und bei 190 Grad 22 Minuten überbacken.'] },
{ n:'Lachs-Spinat-Auflauf mit Kartoffeln', m:'abend', t:50, mp:1, ing:[['lachs',150],['spinat',120],['kartoffeln',200],['kochsahne',100],['reibekaese',50],['dill',3]], s:['Kartoffeln (200 g) in Scheiben schneiden und 10 Minuten vorgaren.','Spinat (120 g) kurz andünsten und ausdrücken.','Kartoffeln, Spinat und gewürfelten Lachs (150 g) in eine Form schichten, mit Sahne (100 g) und Dill (3 g) übergießen.','Mit Käse (50 g) bestreuen und bei 190 Grad 25 Minuten backen.'] },
{ n:'Überbackene Gnocchi mit Tomaten', m:'abend', t:35, mp:1, ing:[['gnocchi',240],['passata',150],['mozzarella',80],['basilikum',4],['knoblauch',6],['parmesan',20]], s:['Gnocchi (240 g) kurz vorgaren, bis sie schwimmen.','Passata (150 g) mit Knoblauch (6 g), Salz und Pfeffer würzen und mit den Gnocchi mischen.','In eine Form geben und mit Mozzarella (80 g) und Parmesan (20 g) belegen.','Bei 200 Grad 18 Minuten überbacken und mit Basilikum (4 g) bestreuen.'] },
{ n:'Zucchini-Hackfleisch-Auflauf', m:'abend', t:50, mp:1, ing:[['zucchini',180],['hackrind',140],['passata',140],['reibekaese',60],['zwiebel',40],['reis',120]], s:['Reis (120 g) garen. Hackfleisch (140 g) mit Zwiebel (40 g) krümelig anbraten, Passata (140 g) zugeben und 5 Minuten köcheln.','Zucchini (180 g) in Scheiben schneiden.','Reis, Hacksauce und Zucchini in eine Form schichten.','Mit Käse (60 g) bestreuen und bei 190 Grad 25 Minuten backen.'] },
{ n:'Blumenkohl-Hack-Auflauf mit Käsekruste', m:'abend', t:50, mp:1, ing:[['blumenkohl',250],['hackrind',130],['kochsahne',110],['reibekaese',70],['zwiebel',40],['kartoffeln',120]], s:['Blumenkohl (250 g) und Kartoffel (120 g) in Stücke schneiden und 8 Minuten vorgaren.','Hackfleisch (130 g) mit Zwiebel (40 g) anbraten und würzen.','Alles in eine Form schichten und mit Sahne (110 g) übergießen.','Mit Käse (70 g) bestreuen und bei 190 Grad 25 Minuten goldbraun überbacken.'] },
{ n:'Süßkartoffel-Hähnchen-Gratin', m:'abend', t:55, mp:1, ing:[['suesskartoffel',250],['haehnchen',140],['kochsahne',110],['bergkaese',60],['zwiebel',40],['thymian',2]], s:['Süßkartoffel (250 g) in dünne Scheiben schneiden.','Hähnchen (140 g) würfeln und mit Zwiebel (40 g) kurz anbraten.','Süßkartoffelscheiben und Hähnchen in eine Form schichten, mit Sahne (110 g) und Thymian (2 g) übergießen.','Mit Bergkäse (60 g) bestreuen und bei 190 Grad 35 Minuten backen.'] },
{ n:'Tortellini-Auflauf mit Spinat und Tomate', m:'abend', t:40, mp:1, ing:[['tortellini',200],['spinat',80],['passata',140],['kochsahne',80],['reibekaese',60],['knoblauch',5]], s:['Tortellini (200 g) kurz vorgaren.','Spinat (80 g) andünsten. Passata (140 g), Sahne (80 g) und Knoblauch (5 g) verrühren.','Tortellini mit Spinat und Sauce mischen und in eine Form geben.','Mit Käse (60 g) bestreuen und bei 190 Grad 20 Minuten überbacken.'] },
{ n:'Auberginen-Hack-Auflauf griechisch (Moussaka-Art)', m:'abend', t:60, mp:1, ing:[['aubergine',200],['hackrind',140],['passata',160],['kochsahne',80],['reibekaese',60],['kartoffeln',120]], s:['Aubergine (200 g) und Kartoffel (120 g) in Scheiben schneiden und in etwas Öl anbraten.','Hackfleisch (140 g) anbraten, Passata (160 g) zugeben und mit Zimt und Oregano würzen.','Abwechselnd Kartoffel, Aubergine und Hacksauce schichten.','Mit Sahne (80 g) übergießen, Käse (60 g) darüber und bei 190 Grad 35 Minuten backen.'] },
{ n:'Spinat-Feta-Kartoffelauflauf', m:'abend', t:50, mp:1, ing:[['kartoffeln',250],['spinat',120],['feta',70],['kochsahne',100],['ei',50],['knoblauch',5]], s:['Kartoffeln (250 g) in Scheiben schneiden und 10 Minuten vorgaren.','Spinat (120 g) andünsten und mit Knoblauch (5 g) würzen.','Kartoffeln und Spinat in eine Form schichten, Feta (70 g) darüberbröseln.','Sahne (100 g) mit Ei (50 g) verquirlen, übergießen und bei 190 Grad 25 Minuten backen.'] },
{ n:'Makkaroni-Käse-Auflauf', m:'abend', t:40, mp:1, ing:[['nudeln',200],['bergkaese',80],['kochsahne',120],['milch',80],['reibekaese',50],['muskat',1]], s:['Makkaroni (200 g) etwas fester als bissfest kochen.','Sahne (120 g), Milch (80 ml) und geriebenen Bergkäse (80 g) mit Muskat (1 g) zu einer Käsesauce verrühren.','Nudeln mit der Sauce mischen und in eine Form geben.','Mit Käse (50 g) bestreuen und bei 190 Grad 20 Minuten goldbraun überbacken.'] },
{ n:'Kartoffel-Lauch-Auflauf mit Speck', m:'abend', t:50, mp:1, ing:[['kartoffeln',250],['lauch',100],['bacon',50],['kochsahne',110],['reibekaese',60],['zwiebel',30]], s:['Lauch (100 g), Zwiebel (30 g) und Bacon (50 g) in der Pfanne anbraten.','Kartoffeln (250 g) in Scheiben schneiden und mit der Lauch-Speck-Mischung in eine Form schichten.','Mit Sahne (110 g) übergießen, salzen und pfeffern.','Mit Käse (60 g) bestreuen und bei 190 Grad 30 Minuten backen.'] },
{ n:'Gefüllte Zucchini mit Reis und Käse', m:'abend', t:45, mp:1, ing:[['zucchini',220],['reis',120],['passata',100],['reibekaese',60],['zwiebel',40],['petersilie',4]], s:['Zucchini (220 g) längs halbieren und aushöhlen.','Reis (120 g) garen und mit angebratener Zwiebel (40 g) und Passata (100 g) mischen.','Die Zucchinihälften mit der Reismischung füllen.','Mit Käse (60 g) bestreuen und bei 190 Grad 25 Minuten backen, mit Petersilie (4 g) bestreuen.'] },
{ n:'Chicoree-Schinken-Gratin', m:'abend', t:45, mp:1, ing:[['chicoree',200],['kochschinken',80],['kochsahne',110],['bergkaese',60],['muskat',1],['kartoffeln',120]], s:['Chicorée (200 g) halbieren und 8 Minuten dünsten, dann je Hälfte in eine Scheibe Schinken (80 g) wickeln.','In eine Form legen, mit vorgegarten Kartoffelscheiben (120 g) umlegen.','Sahne (110 g) mit Muskat (1 g), Salz und Pfeffer übergießen.','Mit Bergkäse (60 g) bestreuen und bei 190 Grad 25 Minuten überbacken.'] },
{ n:'Ofen-Ratatouille mit Ziegenkäse', m:'abend', t:50, mp:1, ing:[['zucchini',100],['aubergine',100],['paprika',90],['passata',150],['ziegenkaese',60],['olivenoel',12]], s:['Zucchini (100 g), Aubergine (100 g) und Paprika (90 g) in Scheiben schneiden und in eine Form schichten.','Passata (150 g) mit Kräutern würzen, dazwischengeben und mit Olivenöl (12 g) beträufeln.','Ziegenkäse (60 g) darüber verteilen.','Bei 190 Grad 35 Minuten backen, bis das Gemüse weich ist.'] },
];
