// Wraps, Sandwiches & belegte Brote. Von Hand geschrieben.
module.exports = [
{ n:'Hähnchen-Caesar-Wrap mit Bacon', m:'mittag', t:22, mp:1, ing:[['wrap',100],['haehnchen',110],['bacon',25],['salat',40],['parmesan',20],['naturjoghurt',40]], s:['Hähnchen (110 g) würzen und in der Pfanne 6-8 Minuten goldbraun braten, Bacon (25 g) knusprig auslassen.','Joghurt (40 g) mit etwas Parmesan, Zitrone, Salz und Pfeffer zu einem Dressing verrühren.','Wrap (100 g) mit Salat (40 g), Hähnchenstreifen, Bacon und dem restlichen Parmesan (20 g) belegen.','Mit dem Dressing beträufeln und fest einrollen.'] },
{ n:'Falafel-Wrap mit Tahin und Rotkohl', m:'mittag', t:24, mp:1, ing:[['wrap',100],['kichererbsen',130],['tahin',25],['rotkohl',50],['tomaten',50],['gurke',40]], s:['Kichererbsen (130 g) mit Gewürzen zu Falafel formen und in heißem Öl rundum goldbraun braten.','Tahin (25 g) mit Wasser und Zitrone zu einer cremigen Sauce verrühren.','Rotkohl (50 g) fein hobeln, Tomaten (50 g) und Gurke (40 g) in Streifen schneiden.','Wrap (100 g) mit Tahin bestreichen, mit Falafel und Gemüse belegen und einrollen.'] },
{ n:'Thunfisch-Mais-Sandwich mit Frischkäse', m:'mittag', t:15, ing:[['vollkornbrot',100],['thunfisch',90],['mais',40],['frischkaese',30],['salat',20],['rotezwiebel',20]], s:['Thunfisch (90 g) abtropfen lassen und mit Frischkäse (30 g), Mais (40 g) und fein gewürfelter Zwiebel (20 g) verrühren, salzen und pfeffern.','Die Creme auf eine Scheibe Vollkornbrot (100 g) streichen.','Mit Salat (20 g) belegen und die zweite Brothälfte daraufsetzen.'] },
{ n:'Caprese-Ciabatta mit Pesto', m:'mittag', t:12, ing:[['ciabatta',100],['mozzarella',70],['tomaten',70],['pesto',20],['basilikum',4]], s:['Ciabatta (100 g) aufschneiden und mit Pesto (20 g) bestreichen.','Mozzarella (70 g) und Tomaten (70 g) in Scheiben schneiden und abwechselnd belegen.','Mit Salz, Pfeffer und Basilikum (4 g) toppen und zusammenklappen.'] },
{ n:'Wrap mit Räucherlachs und Frischkäse', m:'mittag', t:15, ing:[['wrap',100],['raeucherlachs',70],['frischkaese',50],['gurke',40],['rucola',20],['zitrone',6]], s:['Wrap (100 g) dünn mit Frischkäse (50 g) bestreichen.','Räucherlachs (70 g), Gurkenstreifen (40 g) und Rucola (20 g) darauf verteilen.','Mit Zitronensaft (6 g) und Pfeffer würzen und fest einrollen.'] },
{ n:'Putenbrust-Sandwich mit Avocado', m:'mittag', t:15, mp:1, ing:[['vollkornbrot',100],['pute',80],['avocado',60],['salat',20],['tomaten',40],['senf',8]], s:['Putenbrust (80 g) in der Pfanne 4-5 Minuten braten und in Scheiben schneiden.','Eine Scheibe Vollkornbrot (100 g) mit Senf (8 g) bestreichen.','Avocado (60 g) in Scheiben, Pute, Salat (20 g) und Tomate (40 g) auflegen.','Zweite Brothälfte daraufsetzen und halbieren.'] },
{ n:'Veggie-Wrap mit Hummus und Ofengemüse', m:'mittag', t:28, mp:1, ing:[['wrap',100],['hummus',50],['zucchini',60],['paprika',60],['aubergine',60],['feta',40]], s:['Zucchini (60 g), Paprika (60 g) und Aubergine (60 g) würfeln, mit Öl und Salz mischen und bei 200 Grad 20 Minuten rösten.','Wrap (100 g) mit Hummus (50 g) bestreichen.','Mit dem Ofengemüse und zerbröseltem Feta (40 g) belegen.','Fest einrollen und halbieren.'] },
{ n:'Hähnchen-Bacon-Sandwich (Club-Style)', m:'mittag', t:22, ing:[['toastbrot',90],['haehnchen',100],['bacon',30],['salat',20],['tomaten',40],['mayo',15]], s:['Hähnchen (100 g) würzen und braten, Bacon (30 g) knusprig auslassen.','Toast (90 g) rösten und mit Mayo (15 g) bestreichen.','Schichtweise mit Salat (20 g), Tomate (40 g), Hähnchen und Bacon belegen.','Zusammensetzen und diagonal halbieren.'] },
{ n:'Rührei-Wrap mit Spinat und Feta', m:'fruh', t:15, ing:[['wrap',100],['ei',120],['spinat',50],['feta',40],['tomaten',40]], s:['Spinat (50 g) in etwas Öl zusammenfallen lassen.','Verquirlte Eier (120 g) zugeben und bei mittlerer Hitze cremig stocken lassen, Feta (40 g) unterbröseln.','Wrap (100 g) mit dem Rührei und Tomatenwürfeln (40 g) füllen.','Fest einrollen.'] },
{ n:'Mozzarella-Tomaten-Panini', m:'mittag', t:14, ing:[['ciabatta',100],['mozzarella',70],['tomaten',60],['pesto',18],['rucola',15]], s:['Ciabatta (100 g) aufschneiden und mit Pesto (18 g) bestreichen.','Mit Mozzarella (70 g) und Tomatenscheiben (60 g) füllen.','Im Kontaktgrill oder in der Pfanne mit etwas Druck 4-5 Minuten pressen, bis der Käse schmilzt.','Öffnen, Rucola (15 g) einlegen und servieren.'] },
{ n:'Gyros-Wrap mit Zaziki', m:'mittag', t:24, mp:1, ing:[['wrap',100],['gyrosfleisch',120],['naturjoghurt',50],['gurke',40],['tomaten',40],['rotezwiebel',20]], s:['Gyrosfleisch (120 g) in einer heißen Pfanne 6-8 Minuten kräftig anbraten.','Gurke (40 g) fein raspeln, ausdrücken und mit Joghurt (50 g) und Knoblauch zu Zaziki rühren.','Wrap (100 g) mit Fleisch, Tomaten (40 g), roter Zwiebel (20 g) und Zaziki belegen.','Fest einrollen.'] },
{ n:'Überbackener Schinken-Käse-Toast mit Ananas', m:'fruh', t:14, ing:[['toastbrot',90],['kochschinken',50],['bergkaese',45],['ananas',40],['butter',8]], s:['Toast (90 g) dünn mit Butter (8 g) bestreichen.','Mit Schinken (50 g), Ananas (40 g) und geriebenem Bergkäse (45 g) belegen.','Bei 200 Grad Oberhitze 6-8 Minuten überbacken, bis der Käse goldgelb ist.','Heiß servieren.'] },
{ n:'Bruschetta mit Tomaten und Basilikum', m:'mittag', t:15, ing:[['baguette',90],['tomaten',100],['knoblauch',5],['olivenoel',12],['basilikum',5]], s:['Baguette (90 g) in Scheiben schneiden und im Ofen oder Toaster rösten, dann mit der Knoblauchzehe (5 g) einreiben.','Tomaten (100 g) fein würfeln und mit Olivenöl (12 g), Basilikum (5 g), Salz und Pfeffer mischen.','5 Minuten ziehen lassen und auf die Brote geben.'] },
{ n:'Hähnchen-Wrap mit Mango und Curry', m:'mittag', t:24, mp:1, ing:[['wrap',100],['haehnchen',120],['mango',60],['naturjoghurt',40],['currypul',3],['salat',30]], s:['Hähnchen (120 g) mit Currypulver (3 g) würzen und in der Pfanne 6-8 Minuten braten, in Streifen schneiden.','Joghurt (40 g) mit fein gewürfelter Mango (60 g) zu einer fruchtigen Sauce verrühren.','Wrap (100 g) mit Salat (30 g), Hähnchen und der Mangosauce belegen.','Fest einrollen.'] },
{ n:'Vollkornbrot mit Ei, Avocado und Kresse', m:'fruh', t:12, ing:[['vollkornbrot',100],['ei',100],['avocado',60],['kresse',5],['zitrone',6]], s:['Ei (100 g) 8 Minuten hart kochen, abschrecken, pellen und in Scheiben schneiden.','Avocado (60 g) mit Zitronensaft (6 g), Salz und Pfeffer zerdrücken und auf das Brot (100 g) streichen.','Mit den Eischeiben belegen und mit Kresse (5 g) bestreuen.'] },
{ n:'Pulled-Chicken-Sandwich mit Coleslaw', m:'mittag', t:28, mp:1, ing:[['burgerbun',90],['haehnchen',130],['bbqsauce',25],['weisskohl',60],['moehren',30],['mayo',15]], s:['Hähnchen (130 g) würzen, in der Pfanne braten und dann mit zwei Gabeln zerzupfen, mit BBQ-Sauce (25 g) vermengen.','Weißkohl (60 g) fein hobeln, Möhre (30 g) raspeln und mit Mayo (15 g), Salz und etwas Essig zu Coleslaw mischen.','Bun (90 g) aufschneiden, mit Pulled Chicken und Coleslaw füllen.'] },
];
