// Fischgerichte, Teil 3. Von Hand geschrieben.
module.exports = [
{ n:'Ofenlachs mit Honig-Senf und Brokkoli', m:'abend', t:28, mp:1, ing:[['lachs',160],['brokkoli',150],['honig',10],['senf',10],['kartoffeln',180],['olivenoel',10]], s:['Kartoffeln (180 g) würfeln, mit Olivenöl (10 g) und Salz mischen und bei 200 Grad 15 Minuten vorbacken.','Honig (10 g) und Senf (10 g) verrühren und den Lachs (160 g) damit bestreichen.','Lachs und Brokkoli (150 g) mit auf das Blech geben und weitere 12-14 Minuten backen, bis der Lachs gar ist.','Zusammen servieren.'] },
{ n:'Gebratener Kabeljau mit Erbsenpüree', m:'abend', t:26, mp:1, ing:[['kabeljau',170],['erbsen',120],['kartoffeln',100],['butter',12],['zitrone',8],['dill',3]], s:['Kartoffeln (100 g) und Erbsen (120 g) 12 Minuten weich kochen, abgießen und mit der Hälfte der Butter zu einem groben Püree stampfen.','Kabeljau (170 g) trockentupfen, salzen und in der restlichen Butter (12 g) je Seite 3-4 Minuten braten.','Mit Zitronensaft (8 g) beträufeln.','Mit dem Erbsenpüree und Dill (3 g) servieren.'] },
{ n:'Forelle Müllerin mit Petersilienkartoffeln', m:'abend', t:30, ing:[['forelle',180],['mehl',20],['butter',18],['kartoffeln',200],['petersilie',5],['zitrone',8]], s:['Kartoffeln (200 g) in Salzwasser 18-20 Minuten garen.','Forelle (180 g) salzen, in Mehl (20 g) wenden und in der Butter (18 g) je Seite 4-5 Minuten goldbraun braten.','Die Kartoffeln mit gehackter Petersilie (5 g) schwenken.','Forelle mit Zitrone (8 g) und der Bratbutter servieren.'] },
{ n:'Seelachsfilet mit Senfsauce', m:'abend', t:28, mp:1, ing:[['seelachs',170],['senf',12],['kochsahne',80],['kartoffeln',180],['dill',3],['zwiebel',30]], s:['Kartoffeln (180 g) kochen.','Seelachs (170 g) salzen und in etwas Öl je Seite 3-4 Minuten braten, warm stellen.','Zwiebel (30 g) andünsten, Sahne (80 g) und Senf (12 g) zugeben und zu einer sämigen Sauce köcheln.','Fisch mit der Senfsauce, Dill (3 g) und Kartoffeln servieren.'] },
{ n:'Garnelen in Knoblauch-Öl mit Baguette', m:'abend', t:20, ing:[['garnelen',150],['knoblauch',12],['olivenoel',20],['chili',4],['baguette',90],['petersilie',5]], s:['Knoblauch (12 g) in Scheiben und Chili (4 g) in Olivenöl (20 g) bei mittlerer Hitze langsam erhitzen, bis es duftet.','Garnelen (150 g) zugeben und 2-3 Minuten braten, bis sie rosa sind, mit Salz abschmecken.','Mit Petersilie (5 g) bestreuen und mit dem Baguette (90 g) zum Tunken servieren.'] },
{ n:'Lachsfrikadellen mit Dill-Joghurt-Dip', m:'mittag', t:30, mp:1, ing:[['lachs',160],['kartoffeln',80],['ei',50],['semmelbroesel',30],['naturjoghurt',50],['dill',4]], s:['Kartoffel (80 g) kochen und zerdrücken. Lachs (160 g) fein hacken.','Mit Ei (50 g) und Semmelbröseln (30 g) verkneten, würzen und zu Frikadellen formen.','In etwas Öl je Seite 3-4 Minuten goldbraun braten.','Joghurt (50 g) mit Dill (4 g), Salz und Zitrone verrühren und dazu reichen.'] },
{ n:'Lachs-Spinat-Päckchen aus dem Ofen', m:'abend', t:28, mp:1, ing:[['lachs',160],['spinat',100],['kochsahne',50],['zitrone',8],['kartoffeln',180],['knoblauch',5]], s:['Kartoffeln (180 g) in Salzwasser garen.','Spinat (100 g) mit Knoblauch (5 g) kurz andünsten.','Lachs (160 g) auf ein Stück Backpapier setzen, Spinat und Sahne (50 g) darauf verteilen, mit Zitrone (8 g) beträufeln und zu einem Päckchen einschlagen.','Bei 190 Grad 15 Minuten garen und mit den Kartoffeln servieren.'] },
{ n:'Scholle mit Speck und Bratkartoffeln', m:'abend', t:32, ing:[['scholle',180],['bacon',30],['kartoffeln',200],['zwiebel',40],['butter',12],['petersilie',4]], s:['Gekochte Kartoffeln (200 g) in Scheiben mit Zwiebel (40 g) in etwas Öl zu Bratkartoffeln braten.','Bacon (30 g) knusprig auslassen.','Scholle (180 g) salzen, mehlieren und in der Butter (12 g) je Seite 3-4 Minuten braten.','Mit Speck, Bratkartoffeln und Petersilie (4 g) servieren.'] },
{ n:'Thunfisch-Steak mit Sesamkruste', m:'abend', t:20, ing:[['thunfisch',170],['sesam',15],['sojasauce',12],['reis',150],['brokkoli',90],['limette',6]], s:['Reis (150 g) garen und Brokkoli (90 g) 5 Minuten dämpfen.','Thunfisch (170 g) rundum in Sesam (15 g) wälzen.','In einer sehr heißen Pfanne je Seite nur 1-2 Minuten anbraten, sodass er innen rosa bleibt.','In Scheiben schneiden und mit Sojasauce (12 g), Limette (6 g), Reis und Brokkoli servieren.'] },
{ n:'Zanderfilet mit Zitronenbutter', m:'abend', t:26, mp:1, ing:[['zander',170],['butter',18],['zitrone',10],['kartoffeln',180],['spinat',80],['knoblauch',5]], s:['Kartoffeln (180 g) kochen. Spinat (80 g) mit Knoblauch (5 g) andünsten.','Zander (170 g) salzen und auf der Hautseite in etwas Öl 4 Minuten knusprig braten, wenden und 1 Minute fertig garen.','Butter (18 g) mit Zitronensaft (10 g) aufschäumen.','Fisch mit Zitronenbutter, Spinat und Kartoffeln servieren.'] },
{ n:'Garnelen-Tomaten-Pfanne mit Feta', m:'abend', t:24, mp:1, ing:[['garnelen',150],['passata',150],['feta',60],['zwiebel',40],['knoblauch',6],['reis',150]], s:['Reis (150 g) garen.','Zwiebel (40 g) und Knoblauch (6 g) in etwas Öl andünsten, Passata (150 g) zugeben und 6 Minuten köcheln.','Garnelen (150 g) zugeben und 3 Minuten mitgaren, bis sie rosa sind.','Feta (60 g) darüberbröseln und mit dem Reis servieren.'] },
{ n:'Backfisch mit Kartoffelsalat', m:'abend', t:35, mp:1, ing:[['kabeljau',160],['mehl',30],['ei',40],['semmelbroesel',35],['kartoffeln',200],['naturjoghurt',60]], s:['Kartoffeln (200 g) kochen, würfeln und mit Joghurt (60 g), Salz und Pfeffer zu Kartoffelsalat mischen.','Kabeljau (160 g) nacheinander in Mehl (30 g), verquirltem Ei (40 g) und Semmelbröseln (35 g) panieren.','In etwas Öl je Seite 3-4 Minuten goldbraun braten.','Mit dem Kartoffelsalat servieren.'] },
{ n:'Lachsnudeln in Dilltomatensauce', m:'mittag', t:24, mp:1, ing:[['lachs',130],['nudeln',180],['passata',130],['dill',4],['zwiebel',40],['kochsahne',50]], s:['Nudeln (180 g) bissfest kochen.','Zwiebel (40 g) andünsten, Passata (130 g) und Sahne (50 g) zugeben und 5 Minuten köcheln.','Lachs (130 g) würfeln und 3 Minuten in der Sauce mitgaren.','Mit Dill (4 g) würzen und die Nudeln untermengen.'] },
{ n:'Fisch-Curry mit Kokosmilch', m:'abend', t:30, mp:1, ing:[['seelachs',170],['kokosmilch',120],['passata',80],['currypul',4],['paprika',60],['reis',150]], s:['Reis (150 g) garen.','Paprika (60 g) mit Currypulver (4 g) in etwas Öl anbraten, Kokosmilch (120 g) und Passata (80 g) zugeben.','Seelachs (170 g) würfeln und 6-8 Minuten in der Sauce sanft garen, ohne stark zu kochen.','Mit Reis servieren.'] },
{ n:'Muscheln in Weißweinsud mit Baguette', m:'abend', t:28, ing:[['muscheln',250],['weisswein',60],['knoblauch',8],['zwiebel',40],['petersilie',5],['baguette',90]], s:['Zwiebel (40 g) und Knoblauch (8 g) in etwas Öl andünsten.','Muscheln (250 g) zugeben und mit Weißwein (60 g) ablöschen.','Zugedeckt 5 Minuten dämpfen, bis sich die Schalen öffnen (geschlossene aussortieren).','Mit Petersilie (5 g) bestreuen und mit dem Baguette (90 g) servieren.'] },
{ n:'Ofen-Kabeljau mediterran mit Oliven', m:'abend', t:32, mp:1, ing:[['kabeljau',170],['cherrytomaten',100],['oliven',30],['zucchini',80],['olivenoel',14],['knoblauch',6]], s:['Zucchini (80 g) in Scheiben und Cherrytomaten (100 g) in eine Form geben, mit Oliven (30 g), Knoblauch (6 g) und Olivenöl (14 g) mischen.','Bei 200 Grad 10 Minuten vorbacken.','Kabeljau (170 g) salzen, darauflegen und weitere 12-14 Minuten backen, bis der Fisch gar ist.'] },
];
