// Hähnchengerichte, Teil 4. Von Hand geschrieben.
module.exports = [
{ n:'Hähnchenschenkel aus dem Ofen mit Rosmarinkartoffeln', m:'abend', t:55, mp:1, ing:[['haehnchenkeule',200],['kartoffeln',220],['rosmarin',3],['knoblauch',8],['olivenoel',15],['zitrone',10]], s:['Hähnchenschenkel (200 g) mit Salz, Pfeffer und etwas Öl einreiben.','Kartoffeln (220 g) vierteln, mit Rosmarin (3 g), Knoblauch (8 g) und Olivenöl (15 g) mischen und auf ein Blech geben.','Die Schenkel daraufsetzen und bei 200 Grad 40-45 Minuten backen, bis die Haut knusprig und das Fleisch gar ist.','Mit Zitrone (10 g) beträufeln und servieren.'] },
{ n:'Hähnchen-Piccata mit Zitrone und Kapern', m:'abend', t:26, mp:1, ing:[['haehnchen',150],['mehl',20],['butter',15],['zitrone',12],['kapern',12],['bandnudeln',180]], s:['Bandnudeln (180 g) bissfest kochen.','Hähnchen (150 g) flach klopfen, salzen, in Mehl (20 g) wenden und in der Butter (15 g) je Seite 3 Minuten braten.','Mit Zitronensaft (12 g) und Kapern (12 g) ablöschen und kurz einkochen.','Mit den Nudeln servieren.'] },
{ n:'Honig-Sesam-Hähnchen mit Reis', m:'abend', t:28, mp:1, ing:[['haehnchen',150],['honig',15],['sojasauce',14],['sesam',8],['reis',160],['brokkoli',90]], s:['Reis (160 g) garen und Brokkoli (90 g) 5 Minuten dämpfen.','Hähnchen (150 g) würfeln und in der Pfanne 6-8 Minuten goldbraun braten.','Honig (15 g) und Sojasauce (14 g) angießen und 2 Minuten glasieren, bis es glänzt.','Mit Sesam (8 g) bestreuen und mit Reis und Brokkoli servieren.'] },
{ n:'Cremiges Knoblauch-Parmesan-Hähnchen', m:'abend', t:30, mp:1, ing:[['haehnchen',160],['kochsahne',110],['parmesan',30],['knoblauch',10],['spinat',60],['bandnudeln',180]], s:['Bandnudeln (180 g) bissfest kochen.','Hähnchen (160 g) würfeln und 6-8 Minuten goldbraun braten, Knoblauch (10 g) mitbraten.','Sahne (110 g) angießen, Parmesan (30 g) einrühren und 3 Minuten cremig köcheln.','Spinat (60 g) unterrühren, bis er zusammenfällt, dann die Nudeln untermengen.'] },
{ n:'Hähnchen-Fajitas mit Paprika und Guacamole', m:'abend', t:26, mp:1, ing:[['haehnchen',150],['paprika',100],['zwiebel',60],['fajitagewuerz',6],['wrap',100],['guacamole',40]], s:['Hähnchen (150 g), Paprika (100 g) und Zwiebel (60 g) in Streifen schneiden.','In einer sehr heißen Pfanne scharf 6-7 Minuten anbraten, mit Fajitagewürz (6 g) würzen.','Wraps (100 g) kurz erwärmen.','Mit der Fajita-Mischung und Guacamole (40 g) füllen und einrollen.'] },
{ n:'Zitronen-Thymian-Hähnchen mit Ofengemüse', m:'abend', t:45, mp:1, ing:[['haehnchen',160],['zucchini',80],['paprika',80],['kartoffeln',180],['zitrone',12],['thymian',3]], s:['Hähnchen (160 g) mit Zitronensaft (12 g), Thymian (3 g), Öl, Salz und Pfeffer marinieren.','Kartoffeln (180 g), Zucchini (80 g) und Paprika (80 g) in Stücke schneiden und auf ein Blech geben.','Das Hähnchen darauflegen und bei 200 Grad 30 Minuten backen, bis alles gar ist.'] },
{ n:'Hähnchen-Mango-Curry mit Cashews', m:'abend', t:30, mp:1, ing:[['haehnchen',150],['mango',70],['kokosmilch',110],['paprika',60],['cashews',20],['reis',160]], s:['Reis (160 g) garen.','Hähnchen (150 g) würfeln und 6 Minuten anbraten, Paprika (60 g) mitbraten.','Kokosmilch (110 g) und gewürfelte Mango (70 g) zugeben und 6 Minuten köcheln, mit Curry würzen.','Mit Reis servieren und mit gerösteten Cashews (20 g) bestreuen.'] },
{ n:'Paniertes Hähnchenschnitzel mit Pommes', m:'abend', t:35, ing:[['haehnchen',160],['mehl',20],['ei',50],['semmelbroesel',40],['pommes',200],['zitrone',8]], s:['Pommes (200 g) im Ofen bei 220 Grad 20 Minuten knusprig backen.','Hähnchen (160 g) flach klopfen, salzen und nacheinander in Mehl (20 g), verquirltem Ei (50 g) und Semmelbröseln (40 g) panieren.','In reichlich Öl je Seite 3-4 Minuten goldbraun braten.','Mit Pommes und Zitrone (8 g) servieren.'] },
{ n:'Hähnchen-Gemüse-Wok mit Cashews', m:'mittag', t:24, mp:1, ing:[['haehnchen',150],['brokkoli',80],['paprika',70],['cashews',20],['sojasauce',14],['reis',160]], s:['Reis (160 g) garen.','Hähnchen (150 g) in Streifen schneiden und im heißen Wok 4 Minuten scharf anbraten.','Brokkoli (80 g), Paprika (70 g) und Cashews (20 g) zugeben und 4 Minuten mitbraten.','Mit Sojasauce (14 g) ablöschen und mit Reis servieren.'] },
{ n:'Balsamico-Hähnchen mit Rosmarinkartoffeln', m:'abend', t:35, mp:1, ing:[['haehnchen',160],['cherrytomaten',110],['balsamico',15],['knoblauch',6],['kartoffeln',200],['rosmarin',3]], s:['Kartoffeln (200 g) vierteln, mit Rosmarin (3 g) und Öl mischen und bei 200 Grad 25 Minuten rösten.','Hähnchen (160 g) 6-8 Minuten goldbraun braten, Knoblauch (6 g) mitbraten.','Cherrytomaten (110 g) und Balsamico (15 g) zugeben und 4 Minuten einkochen.','Mit den Rosmarinkartoffeln servieren.'] },
{ n:'Hähnchen-Reispfanne mit Erbsen', m:'mittag', t:28, mp:1, ing:[['haehnchen',150],['reis',160],['erbsen',60],['moehren',50],['zwiebel',40],['sojasauce',12]], s:['Reis (160 g) garen (am besten vom Vortag).','Hähnchen (150 g) würfeln und mit Zwiebel (40 g) 6 Minuten anbraten.','Möhre (50 g) und Erbsen (60 g) zugeben und 4 Minuten mitbraten.','Reis untermengen und mit Sojasauce (12 g) würzen.'] },
{ n:'Hähnchengeschnetzeltes in Pilzrahm', m:'abend', t:30, mp:1, ing:[['haehnchen',160],['champignons',100],['kochsahne',100],['zwiebel',40],['spaetzle',200],['petersilie',4]], s:['Spätzle (200 g) erwärmen.','Hähnchen (160 g) in Streifen schneiden und mit Zwiebel (40 g) und Champignons (100 g) 6 Minuten kräftig anbraten.','Sahne (100 g) angießen und 3 Minuten cremig köcheln, salzen und pfeffern.','Mit Petersilie (4 g) und den Spätzle servieren.'] },
{ n:'Tandoori-Hähnchen mit Reis und Joghurt', m:'abend', t:32, mp:1, ing:[['haehnchen',160],['naturjoghurt',80],['tandoori',8],['reis',160],['gurke',50],['zwiebel',30]], s:['Hähnchen (160 g) mit der Hälfte des Joghurts (80 g) und Tandoori (8 g) mischen und 10 Minuten marinieren.','Reis (160 g) garen.','Das Hähnchen in der Pfanne oder bei 210 Grad im Ofen 15 Minuten garen.','Restlichen Joghurt mit geraspelter Gurke (50 g) und Zwiebel (30 g) verrühren und dazu reichen.'] },
{ n:'Hähnchen-Spieße mit Erdnusssauce', m:'abend', t:30, mp:1, ing:[['haehnchen',160],['erdnussbutter',25],['kokosmilch',60],['sojasauce',12],['reis',160],['gurke',50]], s:['Reis (160 g) garen. Hähnchen (160 g) würfeln und auf Spieße stecken.','Die Spieße in der Grillpfanne rundum 8 Minuten braten.','Erdnussbutter (25 g), Kokosmilch (60 g) und Sojasauce (12 g) zu einer Sauce verrühren und leicht erwärmen.','Mit Reis, Gurkenscheiben (50 g) und der Erdnusssauce servieren.'] },
{ n:'Überbackenes Hähnchen mit Tomate und Mozzarella', m:'abend', t:35, mp:1, ing:[['haehnchen',170],['passata',120],['mozzarella',70],['basilikum',4],['kartoffeln',180],['olivenoel',10]], s:['Kartoffeln (180 g) würfeln, mit Olivenöl (10 g) mischen und bei 200 Grad 15 Minuten vorbacken.','Hähnchen (170 g) kurz anbraten und in eine Form legen.','Mit Passata (120 g) übergießen und Mozzarella (70 g) darauf verteilen.','Mit den Kartoffeln 18 Minuten fertig backen und mit Basilikum (4 g) bestreuen.'] },
{ n:'Hähnchen-Frikassee mit Reis', m:'abend', t:40, mp:1, ing:[['haehnchen',150],['champignons',80],['erbsen',50],['kochsahne',100],['reis',160],['zitrone',8]], s:['Reis (160 g) garen. Hähnchen (150 g) in Brühe 12 Minuten gar ziehen lassen und würfeln.','Champignons (80 g) anbraten, Sahne (100 g) und etwas Brühe zugeben.','Hähnchen und Erbsen (50 g) einrühren und 5 Minuten köcheln.','Mit Zitrone (8 g) abschmecken und mit Reis servieren.'] },
];
