// Kartoffelgerichte. Von Hand geschrieben.
module.exports = [
{ n:'Bratkartoffeln mit Speck und Ei', m:'mittag', t:30, ing:[['kartoffeln',250],['bacon',40],['ei',100],['zwiebel',50],['olivenoel',10],['schnittlauch',4]], s:['Kartoffeln (250 g) am besten vom Vortag in Scheiben schneiden und in Olivenöl (10 g) bei mittlerer Hitze 8-10 Minuten knusprig braten.','Bacon (40 g) und Zwiebel (50 g) zugeben und mitbraten, bis alles goldbraun ist.','Eier (100 g) als Spiegeleier braten.','Bratkartoffeln mit Spiegelei anrichten und mit Schnittlauch (4 g) bestreuen.'] },
{ n:'Ofenkartoffel mit Kräuterquark', m:'mittag', t:55, mp:1, ing:[['kartoffeln',300],['magerquark',120],['schnittlauch',5],['leinoel',8],['salz',1]], s:['Kartoffeln (300 g) waschen, einstechen und bei 200 Grad 45 Minuten weich backen.','Magerquark (120 g) mit Leinöl (8 g), Schnittlauch (5 g) und Salz (1 g) cremig verrühren.','Die heißen Kartoffeln kreuzweise einschneiden, etwas aufdrücken und mit dem Kräuterquark füllen.'] },
{ n:'Zucchini-Kartoffelpuffer mit Kräuterquark', m:'mittag', t:30, ing:[['kartoffeln',220],['zucchini',80],['ei',50],['mehl',20],['magerquark',80],['olivenoel',15]], s:['Kartoffeln (220 g) und Zucchini (80 g) grob raspeln, salzen und gut ausdrücken.','Mit Ei (50 g) und Mehl (20 g) zu einem Teig mischen.','Portionsweise in Olivenöl (15 g) je Seite 3-4 Minuten goldbraun und knusprig braten.','Magerquark (80 g) mit Kräutern verrühren und dazu reichen.'] },
{ n:'Süßkartoffel-Pommes mit Kräuterdip', m:'mittag', t:35, mp:1, ing:[['suesskartoffel',280],['olivenoel',15],['paprikapulver',3],['naturjoghurt',80],['schnittlauch',4]], s:['Süßkartoffel (280 g) in Spalten schneiden und mit Olivenöl (15 g), Paprikapulver (3 g) und Salz mischen.','Auf einem Blech verteilen und bei 210 Grad 25 Minuten backen, nach der Hälfte wenden.','Joghurt (80 g) mit Schnittlauch (4 g), Salz und Pfeffer zu einem Dip verrühren.','Die Pommes mit dem Dip servieren.'] },
{ n:'Gnocchi mit Tomaten und Rucola', m:'mittag', t:22, ing:[['gnocchi',240],['cherrytomaten',100],['rucola',30],['parmesan',25],['knoblauch',6],['olivenoel',12]], s:['Gnocchi (240 g) in Olivenöl (12 g) 6-8 Minuten goldbraun anbraten.','Knoblauch (6 g) und halbierte Cherrytomaten (100 g) zugeben und 3-4 Minuten mitbraten.','Vom Herd nehmen und Rucola (30 g) unterheben, bis er leicht zusammenfällt.','Mit Parmesan (25 g) bestreut servieren.'] },
{ n:'Kartoffel-Gemüse-Pfanne mit Wurst', m:'abend', t:35, mp:1, ing:[['kartoffeln',250],['paprika',70],['zucchini',70],['mettwurst',80],['zwiebel',50],['olivenoel',12]], s:['Gekochte Kartoffeln (250 g) würfeln und in Olivenöl (12 g) 8 Minuten anbraten.','Paprika (70 g), Zucchini (70 g) und Zwiebel (50 g) zugeben und mitbraten.','Mettwurst (80 g) in Scheiben zugeben und alles knusprig braten.','Mit Salz und Pfeffer abschmecken.'] },
{ n:'Rosmarinkartoffeln aus dem Ofen', m:'abend', t:45, mp:1, ing:[['kartoffeln',300],['rosmarin',4],['knoblauch',8],['olivenoel',18],['salz',2]], s:['Kartoffeln (300 g) vierteln.','Mit Rosmarin (4 g), Knoblauch (8 g), Olivenöl (18 g) und Salz (2 g) gründlich mischen.','Auf einem Blech verteilen und bei 200 Grad 35 Minuten backen, bis sie außen knusprig und innen weich sind.'] },
{ n:'Kartoffelgnocchi mit Gorgonzola', m:'abend', t:24, ing:[['gnocchi',240],['bergkaese',50],['kochsahne',90],['walnuesse',15],['petersilie',4]], s:['Gnocchi (240 g) in kochendem Salzwasser garen, bis sie oben schwimmen.','Bergkäse (50 g) mit Sahne (90 g) bei kleiner Hitze cremig schmelzen.','Gnocchi in der Sauce schwenken.','Mit gehackten Walnüssen (15 g) und Petersilie (4 g) servieren.'] },
{ n:'Pellkartoffeln mit Leinöl-Quark und Radieschen', m:'mittag', t:35, mp:1, ing:[['kartoffeln',300],['magerquark',150],['leinoel',10],['radieschen',50],['schnittlauch',5]], s:['Kartoffeln (300 g) als Pellkartoffeln in Salzwasser 20 Minuten garen.','Magerquark (150 g) mit Leinöl (10 g), etwas Wasser, Salz und Pfeffer glatt rühren.','Radieschen (50 g) klein würfeln und mit Schnittlauch (5 g) unterheben.','Die warmen Kartoffeln pellen und mit dem Quark servieren.'] },
{ n:'Kartoffel-Lauch-Pfanne mit Ei', m:'mittag', t:30, ing:[['kartoffeln',250],['lauch',80],['ei',100],['bergkaese',40],['olivenoel',12],['petersilie',4]], s:['Gekochte Kartoffeln (250 g) würfeln und in Olivenöl (12 g) anbraten, Lauch (80 g) in Ringen zugeben.','Wenn alles goldbraun ist, verquirlte Eier (100 g) darübergeben.','Bei mittlerer Hitze stocken lassen und geriebenen Bergkäse (40 g) darüberstreuen.','Mit Petersilie (4 g) servieren.'] },
{ n:'Gefüllte Ofenkartoffel mit Chili con Carne', m:'abend', t:55, mp:1, ing:[['kartoffeln',300],['hackrind',110],['kidneybohnen',70],['passata',80],['reibekaese',40],['zwiebel',40]], s:['Kartoffeln (300 g) bei 200 Grad 45 Minuten weich backen.','Hackfleisch (110 g) mit Zwiebel (40 g) anbraten, Kidneybohnen (70 g) und Passata (80 g) zugeben und mit Kreuzkümmel und Paprika 10 Minuten köcheln.','Die Kartoffeln aufschneiden, aufdrücken und mit dem Chili füllen.','Mit Käse (40 g) bestreuen und kurz überbacken.'] },
{ n:'Kartoffel-Wedges mit Sour Cream', m:'mittag', t:40, mp:1, ing:[['kartoffeln',300],['paprikapulver',4],['olivenoel',15],['schmand',60],['schnittlauch',4]], s:['Kartoffeln (300 g) in Spalten schneiden und mit Olivenöl (15 g), Paprikapulver (4 g) und Salz mischen.','Auf einem Blech bei 210 Grad 30 Minuten knusprig backen, nach der Hälfte wenden.','Schmand (60 g) mit Schnittlauch (4 g), Salz und Pfeffer verrühren.','Die Wedges mit der Sour Cream servieren.'] },
{ n:'Schwenkkartoffeln mit Kräutern und Speck', m:'abend', t:35, mp:1, ing:[['kartoffeln',280],['bacon',40],['butter',15],['petersilie',5],['zwiebel',40]], s:['Kartoffeln (280 g) in Salzwasser garen und etwas abkühlen lassen.','Bacon (40 g) und Zwiebel (40 g) in der Butter (15 g) anbraten.','Die Kartoffeln zugeben und darin schwenken, bis sie glänzen und leicht bräunen.','Mit Petersilie (5 g) bestreuen.'] },
{ n:'Kartoffelgratin mit Spinat und Feta', m:'abend', t:55, mp:1, ing:[['kartoffeln',260],['spinat',100],['feta',60],['kochsahne',110],['knoblauch',6],['muskat',1]], s:['Kartoffeln (260 g) in dünne Scheiben schneiden. Spinat (100 g) mit Knoblauch (6 g) andünsten.','Kartoffeln und Spinat abwechselnd in eine Form schichten.','Sahne (110 g) mit Muskat (1 g), Salz und Pfeffer übergießen und Feta (60 g) darüberbröseln.','Bei 190 Grad 40 Minuten backen, bis die Kartoffeln weich sind.'] },
{ n:'Stampfkartoffeln mit Röstzwiebeln', m:'abend', t:30, ing:[['kartoffeln',300],['milch',80],['butter',15],['roestzwiebel',20],['muskat',1]], s:['Kartoffeln (300 g) schälen und in Salzwasser 20 Minuten weich kochen.','Abgießen und mit warmer Milch (80 ml) und Butter (15 g) zu einem cremigen Stampf zerdrücken.','Mit Muskat (1 g), Salz und Pfeffer abschmecken.','Mit Röstzwiebeln (20 g) toppen.'] },
{ n:'Kartoffelsalat mit Radieschen und Schnittlauch', m:'mittag', t:35, mp:1, ing:[['kartoffeln',280],['radieschen',50],['naturjoghurt',70],['senf',8],['schnittlauch',5],['essig',8]], s:['Kartoffeln (280 g) in Salzwasser garen, etwas abkühlen und in Scheiben schneiden.','Radieschen (50 g) in Scheiben schneiden und untermischen.','Joghurt (70 g) mit Senf (8 g), Essig (8 g), Salz und Pfeffer zu einem Dressing verrühren.','Unter den Salat heben, mit Schnittlauch (5 g) bestreuen und 15 Minuten ziehen lassen.'] },
];
