// Pfannen- & Wok-Gerichte. Von Hand geschrieben.
module.exports = [
{ n:'Rindfleisch-Brokkoli-Wok mit Austernsauce', m:'abend', t:24, mp:1, ing:[['rindersteak',150],['brokkoli',100],['moehren',50],['austernsauce',18],['reis',160],['knoblauch',6]], s:['Reis (160 g) garen.','Rindfleisch (150 g) in feine Streifen schneiden und im sehr heißen Wok 2-3 Minuten scharf anbraten, herausnehmen.','Brokkoli (100 g), Möhre (50 g) und Knoblauch (6 g) 4 Minuten anbraten.','Fleisch zurückgeben, mit Austernsauce (18 g) ablöschen und mit Reis servieren.'] },
{ n:'Hähnchen-Cashew-Wok mit Paprika', m:'abend', t:24, mp:1, ing:[['haehnchen',150],['paprika',80],['cashews',20],['sojasauce',14],['reis',160],['fruehlingszwiebel',20]], s:['Reis (160 g) garen.','Hähnchen (150 g) in Streifen schneiden und im Wok 4 Minuten scharf anbraten.','Paprika (80 g) und Cashews (20 g) zugeben und 3 Minuten mitbraten.','Mit Sojasauce (14 g) ablöschen, Frühlingszwiebeln (20 g) unterheben und mit Reis servieren.'] },
{ n:'Garnelen-Gemüse-Wok mit Mie-Nudeln', m:'mittag', t:22, mp:1, ing:[['garnelen',140],['mienudeln',160],['paprika',60],['moehren',50],['sojasauce',14],['ingwer',6]], s:['Mie-Nudeln (160 g) nach Packung garen.','Garnelen (140 g) im Wok 2 Minuten anbraten, herausnehmen.','Möhre (50 g), Paprika (60 g) und Ingwer (6 g) 4 Minuten braten.','Nudeln und Garnelen zugeben, mit Sojasauce (14 g) abschmecken.'] },
{ n:'Tofu-Brokkoli-Wok mit Sesam', m:'mittag', t:24, mp:1, ing:[['tofu',150],['brokkoli',100],['paprika',60],['sojasauce',14],['sesam',8],['reis',160]], s:['Reis (160 g) garen. Tofu (150 g) würfeln und im Wok rundum knusprig braten, herausnehmen.','Brokkoli (100 g) und Paprika (60 g) 5 Minuten scharf anbraten.','Tofu zurückgeben und mit Sojasauce (14 g) ablöschen.','Mit Sesam (8 g) bestreuen und mit Reis servieren.'] },
{ n:'Bami Goreng mit Hähnchen und Garnelen', m:'abend', t:28, mp:1, ing:[['mienudeln',170],['haehnchen',110],['garnelen',60],['ei',50],['sojasauce',16],['lauch',40]], s:['Mie-Nudeln (170 g) garen.','Hähnchen (110 g) und Garnelen (60 g) im Wok scharf anbraten, herausnehmen.','Ei (50 g) und Lauch (40 g) anbraten, bis das Ei gestockt ist.','Nudeln, Fleisch und Sojasauce (16 g) unterschwenken.'] },
{ n:'Nasi Goreng mit Ei und Erbsen', m:'mittag', t:24, mp:1, ing:[['reis',180],['ei',100],['erbsen',50],['moehren',50],['sojasauce',16],['fruehlingszwiebel',20]], s:['Reis (180 g) am besten vom Vortag verwenden.','Möhre (50 g) und Erbsen (50 g) im Wok 3 Minuten braten, Reis zugeben und heiß braten.','Den Reis zur Seite schieben, Ei (100 g) einschlagen und stocken lassen, dann untermengen.','Mit Sojasauce (16 g) würzen und mit Frühlingszwiebeln (20 g) servieren.'] },
{ n:'Schweinefilet-Wok süß-sauer', m:'abend', t:28, mp:1, ing:[['schweinefilet',150],['paprika',70],['ananas',60],['tomatenmark',15],['reis',160],['essig',10]], s:['Reis (160 g) garen.','Schweinefilet (150 g) in Streifen schneiden und im Wok 4 Minuten scharf anbraten.','Paprika (70 g) und Ananas (60 g) zugeben und kurz mitbraten.','Tomatenmark (15 g), Essig (10 g) und etwas Zucker zu einer süß-sauren Sauce verrühren, angießen und mit Reis servieren.'] },
{ n:'Bunter Gemüse-Wok mit Kokos-Erdnusssauce', m:'mittag', t:26, mp:1, ing:[['brokkoli',80],['paprika',70],['zuckerschoten',60],['erdnussbutter',22],['kokosmilch',60],['mienudeln',150]], s:['Mie-Nudeln (150 g) garen.','Brokkoli (80 g), Paprika (70 g) und Zuckerschoten (60 g) im Wok 5 Minuten scharf anbraten.','Erdnussbutter (22 g) mit Kokosmilch (60 g) zu einer Sauce verrühren und angießen.','Nudeln untermengen und kurz durchschwenken.'] },
{ n:'Hähnchen-Teriyaki-Wok mit Sesam', m:'abend', t:24, mp:1, ing:[['haehnchen',150],['teriyakisauce',22],['brokkoli',90],['moehren',50],['reis',160],['sesam',6]], s:['Reis (160 g) garen.','Hähnchen (150 g) in Streifen schneiden und 4 Minuten scharf anbraten.','Brokkoli (90 g) und Möhre (50 g) zugeben und 4 Minuten mitbraten.','Mit Teriyakisauce (22 g) 1 Minute glasieren und mit Sesam (6 g) bestreuen.'] },
{ n:'Rindfleisch-Wok mit grünen Bohnen', m:'abend', t:26, mp:1, ing:[['rindersteak',150],['gruenebohnen',100],['knoblauch',8],['sojasauce',14],['reis',160],['chili',4]], s:['Reis (160 g) garen. Grüne Bohnen (100 g) 4 Minuten blanchieren.','Rindfleisch (150 g) in Streifen schneiden und im Wok scharf anbraten.','Bohnen, Knoblauch (8 g) und Chili (4 g) zugeben und 3 Minuten mitbraten.','Mit Sojasauce (14 g) ablöschen und mit Reis servieren.'] },
{ n:'Kung-Pao-Hähnchen mit Erdnüssen', m:'abend', t:26, mp:1, ing:[['haehnchen',150],['paprika',70],['erdnuesse',20],['sojasauce',14],['reis',160],['chili',5]], s:['Reis (160 g) garen.','Hähnchen (150 g) würfeln und im Wok 4 Minuten scharf anbraten.','Paprika (70 g), Erdnüsse (20 g) und Chili (5 g) zugeben und 3 Minuten mitbraten.','Mit Sojasauce (14 g) und etwas Essig ablöschen und mit Reis servieren.'] },
{ n:'Glasnudel-Wok mit Gemüse und Ei', m:'mittag', t:22, mp:1, ing:[['glasnudeln',150],['moehren',50],['paprika',60],['ei',100],['sojasauce',14],['fruehlingszwiebel',20]], s:['Glasnudeln (150 g) mit kochendem Wasser übergießen und 5 Minuten ziehen lassen.','Möhre (50 g) und Paprika (60 g) im Wok 4 Minuten anbraten, Ei (100 g) einschlagen und stocken lassen.','Nudeln zugeben und mit Sojasauce (14 g) unterschwenken.','Mit Frühlingszwiebeln (20 g) servieren.'] },
{ n:'Pad Thai mit Garnelen', m:'abend', t:28, mp:1, ing:[['reisnudeln',160],['garnelen',130],['ei',50],['erdnuesse',20],['limette',8],['sojasauce',14]], s:['Reisnudeln (160 g) in warmem Wasser 8 Minuten einweichen.','Garnelen (130 g) im Wok 2 Minuten braten, an den Rand schieben, Ei (50 g) einschlagen und stocken lassen.','Nudeln und Sojasauce (14 g) zugeben und heiß durchschwenken.','Mit gehackten Erdnüssen (20 g) und Limette (8 g) servieren.'] },
{ n:'Hähnchen-Ananas-Wok mit Paprika', m:'mittag', t:24, mp:1, ing:[['haehnchen',150],['ananas',70],['paprika',70],['sojasauce',14],['reis',160],['ingwer',5]], s:['Reis (160 g) garen.','Hähnchen (150 g) in Streifen schneiden und mit Ingwer (5 g) 4 Minuten scharf anbraten.','Ananas (70 g) und Paprika (70 g) zugeben und 3 Minuten mitbraten.','Mit Sojasauce (14 g) ablöschen und mit Reis servieren.'] },
{ n:'Rindfleisch-Wok mit Pak Choi', m:'abend', t:24, mp:1, ing:[['rindersteak',150],['pak_choi',100],['moehren',50],['austernsauce',18],['reis',160],['knoblauch',6]], s:['Reis (160 g) garen.','Rindfleisch (150 g) in Streifen schneiden und im Wok 2-3 Minuten scharf anbraten, herausnehmen.','Pak Choi (100 g), Möhre (50 g) und Knoblauch (6 g) 3 Minuten anbraten.','Fleisch zurückgeben, mit Austernsauce (18 g) ablöschen und mit Reis servieren.'] },
{ n:'Tofu-Erdnuss-Wok mit Mie-Nudeln', m:'mittag', t:24, mp:1, ing:[['tofu',150],['mienudeln',160],['brokkoli',80],['erdnussbutter',22],['sojasauce',12],['limette',6]], s:['Mie-Nudeln (160 g) garen. Tofu (150 g) würfeln und knusprig braten.','Brokkoli (80 g) im Wok 4 Minuten anbraten.','Erdnussbutter (22 g) mit Sojasauce (12 g) und etwas Wasser zu einer Sauce verrühren.','Tofu, Nudeln und Sauce untermengen und mit Limette (6 g) abschmecken.'] },
];
