// Vegetarische Weltküche. Von Hand geschrieben.
module.exports = [
{ n:'Palak Paneer mit Reis', m:'abend', t:32, mp:1, ing:[['paneer',120],['spinat',150],['kokosmilch',80],['zwiebel',40],['garam_masala',4],['reis',160]], s:['Reis (160 g) garen. Spinat (150 g) kurz blanchieren und fein pürieren.','Zwiebel (40 g) mit Garam Masala (4 g) in etwas Öl anrösten, Spinatpüree und Kokosmilch (80 g) zugeben und 5 Minuten köcheln.','Paneer (120 g) würfeln und in etwas Öl goldbraun anbraten.','Paneer in die Spinatsauce geben und mit Reis servieren.'] },
{ n:'Chana Masala mit Naan', m:'abend', t:35, mp:1, ing:[['kichererbsen',170],['passata',120],['zwiebel',50],['garam_masala',4],['ingwer',6],['naanbrot',90]], s:['Zwiebel (50 g), Ingwer (6 g) und Garam Masala (4 g) in etwas Öl 3 Minuten anrösten.','Kichererbsen (170 g) und Passata (120 g) zugeben und mit etwas Wasser 15 Minuten sämig köcheln.','Mit Salz abschmecken.','Naan (90 g) kurz erwärmen und dazu servieren.'] },
{ n:'Gemüse-Biryani mit Joghurt', m:'abend', t:40, mp:1, ing:[['basmatireis',170],['blumenkohl',80],['erbsen',50],['moehren',50],['garam_masala',4],['naturjoghurt',60]], s:['Basmatireis (170 g) fast gar kochen und abgießen.','Blumenkohl (80 g), Möhre (50 g) und Erbsen (50 g) mit Garam Masala (4 g) in etwas Öl anbraten.','Reis und Gemüse in einem Topf schichten und zugedeckt bei kleiner Hitze 12 Minuten dämpfen.','Mit Joghurt (60 g) servieren.'] },
{ n:'Falafel mit Tabouleh', m:'mittag', t:30, mp:1, ing:[['kichererbsen',150],['bulgur',120],['petersilie',15],['tomaten',60],['zitrone',10],['olivenoel',12]], s:['Bulgur (120 g) mit kochendem Wasser übergießen und 12 Minuten quellen lassen.','Kichererbsen (150 g) mit Gewürzen zerkleinern, zu Bällchen formen und in heißem Öl goldbraun braten.','Bulgur mit gehackter Petersilie (15 g), Tomatenwürfeln (60 g), Zitrone (10 g) und Olivenöl (12 g) zu Tabouleh mischen.','Falafel und Tabouleh zusammen anrichten.'] },
{ n:'Halloumi mit Granatapfel und Couscous', m:'mittag', t:24, mp:1, ing:[['halloumi',120],['couscous',150],['granatapfel2',40],['minze',4],['zitrone',8],['olivenoel',10]], s:['Couscous (150 g) mit kochendem Wasser übergießen, 5 Minuten quellen lassen und mit Olivenöl (10 g) und Zitrone (8 g) auflockern.','Halloumi (120 g) in Scheiben je Seite 2-3 Minuten goldbraun braten.','Granatapfelkerne (40 g) und Minze (4 g) unter den Couscous mischen.','Mit dem Halloumi anrichten.'] },
{ n:'Grüne Shakshuka mit Spinat und Feta', m:'mittag', t:28, ing:[['ei',150],['spinat',120],['kichererbsen',80],['zucchini',60],['feta',50],['fladenbrot',60]], s:['Zucchini (60 g) würfeln und in etwas Öl anbraten, Spinat (120 g) zugeben und zusammenfallen lassen.','Kichererbsen (80 g) untermischen und würzen.','Mulden formen, Eier (150 g) hineingleiten lassen und zugedeckt 6-8 Minuten stocken lassen.','Mit Feta (50 g) bestreuen und mit Fladenbrot (60 g) servieren.'] },
{ n:'Gemüse-Enchiladas mit Bohnen', m:'abend', t:45, mp:1, ing:[['wrap',120],['kidneybohnen',100],['mais',60],['passata',150],['reibekaese',70],['paprika',60]], s:['Kidneybohnen (100 g), Mais (60 g) und gewürfelte Paprika (60 g) mischen und würzen.','Die Wraps (120 g) damit füllen und eng gerollt in eine Form legen.','Mit Passata (150 g) übergießen und mit Käse (70 g) bestreuen.','Bei 190 Grad 20 Minuten überbacken.'] },
{ n:'Süßkartoffel-Tacos mit Avocado', m:'mittag', t:30, mp:1, ing:[['tortilla_mais',100],['suesskartoffel',150],['avocado',60],['kidneybohnen',60],['limette',6],['koriandergruen',4]], s:['Süßkartoffel (150 g) würfeln, mit Paprika und Kreuzkümmel würzen und bei 210 Grad 20 Minuten rösten.','Kidneybohnen (60 g) erwärmen und Avocado (60 g) in Spalten schneiden.','Maistortillas (100 g) kurz erwärmen.','Mit Süßkartoffel, Bohnen, Avocado, Limette (6 g) und Koriander (4 g) füllen.'] },
{ n:'Miso-Suppe mit Tofu und Algen', m:'mittag', t:18, ing:[['miso',20],['tofu',100],['nori',3],['fruehlingszwiebel',20],['mienudeln',120],['bruehe',350]], s:['Brühe (350 ml) erhitzen, aber nicht kochen, und Miso (20 g) einrühren.','Tofu (100 g) würfeln und mit den Mie-Nudeln (120 g) 3 Minuten ziehen lassen.','Nori (3 g) in Streifen schneiden.','Mit Nori und Frühlingszwiebeln (20 g) servieren.'] },
{ n:'Gemüse-Gyoza mit Sojadip', m:'abend', t:35, mp:1, ing:[['gyozateig',120],['weisskohl',80],['moehren',50],['ingwer',6],['sojasauce',16],['sesam',5]], s:['Weißkohl (80 g), Möhre (50 g) und Ingwer (6 g) sehr fein hacken, kurz anbraten und würzen.','Die Gyoza-Teigblätter (120 g) mit der Füllung füllen und zu Halbmonden falten.','In der Pfanne mit etwas Öl anbraten, dann einen Schuss Wasser zugeben und zugedeckt 5 Minuten dämpfen.','Sojasauce (16 g) mit Sesam (5 g) als Dip dazu reichen.'] },
{ n:'Feta-Spinat-Börek', m:'abend', t:40, mp:1, ing:[['filoteig',120],['spinat',120],['feta',80],['ei',50],['zwiebel',40],['olivenoel',12]], s:['Spinat (120 g) mit Zwiebel (40 g) andünsten, ausdrücken und mit zerbröseltem Feta (80 g) und Ei (50 g) mischen.','Filoteig (120 g) mit Olivenöl (12 g) bestreichen, die Füllung auftragen und aufrollen.','Auf ein Blech legen und mit etwas Öl bestreichen.','Bei 190 Grad 25 Minuten goldbraun backen.'] },
{ n:'Linsen-Kofta in Tomatensauce', m:'abend', t:40, mp:1, ing:[['rotelinsen',140],['semmelbroesel',30],['passata',150],['zwiebel',40],['garam_masala',4],['reis',150]], s:['Reis (150 g) garen. Rote Linsen (140 g) weich kochen und abtropfen lassen.','Mit Semmelbröseln (30 g) und Gewürzen zu einer Masse verkneten und zu Bällchen formen, dann anbraten.','Zwiebel (40 g) mit Garam Masala (4 g) anrösten und Passata (150 g) zugeben, 8 Minuten köcheln.','Die Kofta in der Sauce erwärmen und mit Reis servieren.'] },
{ n:'Gefüllte Weinblätter mit Reis und Pinienkernen', m:'abend', t:50, mp:1, ing:[['weinblaetter',80],['reis',140],['pinienkerne',15],['zwiebel',40],['dill',4],['zitrone',10]], s:['Reis (140 g) halbgar kochen und mit angebratener Zwiebel (40 g), Pinienkernen (15 g) und Dill (4 g) mischen.','Je einen Löffel Füllung auf ein Weinblatt (80 g) geben und fest einrollen.','Die Röllchen dicht in einen Topf schichten, mit Wasser, Zitrone (10 g) und etwas Öl bedecken.','Zugedeckt bei kleiner Hitze 35 Minuten garen.'] },
{ n:'Aloo Gobi mit Reis', m:'abend', t:35, mp:1, ing:[['kartoffeln',180],['blumenkohl',150],['zwiebel',40],['kurkuma',3],['garam_masala',3],['reis',150]], s:['Reis (150 g) garen.','Zwiebel (40 g) mit Kurkuma (3 g) und Garam Masala (3 g) in etwas Öl anrösten.','Kartoffeln (180 g) und Blumenkohl (150 g) in Stücke schneiden, zugeben und kurz mitbraten.','Mit etwas Wasser zugedeckt 18 Minuten weich schmoren und mit Reis servieren.'] },
{ n:'Gemüse-Tajine mit Couscous', m:'abend', t:45, mp:1, ing:[['suesskartoffel',120],['moehren',70],['kichererbsen',100],['passata',110],['raselhanout',4],['couscous',150]], s:['Süßkartoffel (120 g) und Möhre (70 g) würfeln und in etwas Öl anbraten, Ras el Hanout (4 g) mitrösten.','Kichererbsen (100 g) und Passata (110 g) zugeben und zugedeckt 20 Minuten schmoren.','Couscous (150 g) mit kochendem Wasser übergießen und 5 Minuten quellen lassen.','Die Tajine mit dem Couscous servieren.'] },
{ n:'Lauch-Champignon-Quiche mit Bergkäse', m:'abend', t:50, mp:1, ing:[['blaetterteig',120],['lauch',100],['champignons',80],['ei',100],['kochsahne',80],['bergkaese',50]], s:['Lauch (100 g) und Champignons (80 g) in etwas Öl 5 Minuten andünsten.','Blätterteig (120 g) in eine Form legen und das Gemüse darauf verteilen.','Ei (100 g) mit Sahne (80 g), Salz und Muskat verquirlen und darübergießen.','Mit Bergkäse (50 g) bestreuen und bei 190 Grad 30 Minuten goldbraun backen.'] },
];
