// Fleischgerichte (Schwein & Rind), Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Schweinemedaillons in Pfefferrahm mit Spätzle', m:'abend', t:32, mp:1, ing:[['schweinefilet',160],['kochsahne',100],['pfeffer',3],['champignons',80],['spaetzle',200],['zwiebel',40]], s:['Spätzle (200 g) erwärmen.','Schweinefilet (160 g) in Medaillons schneiden, salzen und in etwas Öl je Seite 3 Minuten anbraten, herausnehmen.','Zwiebel (40 g) und Champignons (80 g) anbraten, Sahne (100 g) angießen und mit Pfeffer (3 g) 4 Minuten zu einer sämigen Sauce köcheln.','Medaillons zurückgeben, kurz ziehen lassen und mit den Spätzle servieren.'] },
{ n:'Ungarisches Rindergulasch mit Semmelknödel', m:'abend', t:95, mp:1, ing:[['rindersteak',160],['zwiebel',60],['paprika',70],['paprikapulver',4],['semmelknoedel',150],['bruehe',220]], s:['Rindfleisch (160 g) würfeln und mit der Zwiebel (60 g) rundum kräftig anbraten.','Vom Herd Paprikapulver (4 g) einrühren, dann Paprika (70 g) und Brühe (220 ml) zugeben.','Zugedeckt bei kleiner Hitze 75 Minuten schmoren, bis das Fleisch zart ist.','Semmelknödel (150 g) nach Packung garen und dazu servieren.'] },
{ n:'Schnitzel Wiener Art mit Kartoffelsalat', m:'abend', t:35, ing:[['schweineschnitzel',160],['mehl',20],['ei',50],['semmelbroesel',40],['kartoffeln',200],['naturjoghurt',60]], s:['Kartoffeln (200 g) kochen, würfeln und mit Joghurt (60 g), Salz und Pfeffer zu Kartoffelsalat mischen.','Schnitzel (160 g) flach klopfen, salzen und nacheinander in Mehl (20 g), verquirltem Ei (50 g) und Semmelbröseln (40 g) panieren.','In reichlich Öl schwimmend je Seite 2-3 Minuten goldbraun braten und dabei die Pfanne schwenken.','Mit Zitrone und dem Kartoffelsalat servieren.'] },
{ n:'Rinderhack-Bällchen in Tomatensauce', m:'abend', t:35, mp:1, ing:[['hackrind',150],['semmelbroesel',25],['ei',40],['passata',180],['spaghetti',180],['parmesan',20]], s:['Hackfleisch (150 g) mit Semmelbröseln (25 g), Ei (40 g), Salz und Pfeffer verkneten und zu Bällchen formen.','In etwas Öl rundum anbraten.','Passata (180 g) angießen und die Bällchen darin 12 Minuten schmoren.','Spaghetti (180 g) bissfest kochen und mit den Bällchen und Parmesan (20 g) servieren.'] },
{ n:'Kalbsgeschnetzeltes Züricher Art mit Rösti', m:'abend', t:35, mp:1, ing:[['kalbsschnitzel',160],['champignons',90],['kochsahne',100],['weisswein',30],['zwiebel',40],['kartoffeln',200]], s:['Kartoffeln (200 g) grob raspeln und als Rösti in etwas Öl je Seite 5-6 Minuten goldbraun braten.','Kalbfleisch (160 g) in feine Streifen schneiden und in einer heißen Pfanne 2 Minuten scharf anbraten, herausnehmen.','Zwiebel (40 g) und Champignons (90 g) anbraten, mit Weißwein (30 g) ablöschen, Sahne (100 g) zugeben und einköcheln.','Fleisch zurückgeben und mit dem Rösti servieren.'] },
{ n:'Rumpsteak mit Pfefferbutter und Süßkartoffel-Wedges', m:'abend', t:32, ing:[['rindersteak',180],['butter',15],['pfeffer',3],['suesskartoffel',180],['paprika',70],['olivenoel',12]], s:['Süßkartoffel (180 g) und Paprika (70 g) in Spalten schneiden, mit Olivenöl (12 g) mischen und bei 210 Grad 25 Minuten backen.','Steak (180 g) salzen und in heißer Pfanne je Seite 2-3 Minuten braten, dann 4 Minuten ruhen lassen.','Butter (15 g) mit Pfeffer (3 g) verkneten.','Steak mit der Pfefferbutter und den Wedges servieren.'] },
{ n:'Krustenbraten mit Biersoße, Rotkohl und Klößen', m:'abend', t:110, mp:1, ing:[['schweinebraten',180],['rotkohl',150],['kloesse',150],['bier',40],['zwiebel',50],['bruehe',180]], s:['Schweinebraten (180 g) mit Zwiebel (50 g) in einen Bräter geben und bei 180 Grad etwa 90 Minuten garen, die Schwarte zum Schluss knusprig aufkrusten.','Den Bratensaft mit Bier (40 g) und Brühe (180 ml) aufgießen und zu einer Soße einkochen.','Rotkohl (150 g) weich schmoren.','Klöße (150 g) garen und mit Braten, Soße und Rotkohl servieren.'] },
{ n:'Frikadellen mit Kartoffelpüree und Erbsen', m:'abend', t:35, mp:1, ing:[['hackrind',150],['semmelbroesel',25],['ei',40],['kartoffeln',200],['erbsen',70],['milch',60]], s:['Hackfleisch (150 g) mit Semmelbröseln (25 g), Ei (40 g), Salz und Pfeffer verkneten und zu Frikadellen formen.','In etwas Öl je Seite 4 Minuten braten.','Kartoffeln (200 g) kochen und mit Milch (60 ml) zu Püree stampfen.','Erbsen (70 g) garen und alles zusammen servieren.'] },
{ n:'Cevapcici mit Ajvar und Reis', m:'abend', t:30, mp:1, ing:[['hackrind',160],['zwiebel',40],['knoblauch',5],['ajvar',30],['reis',160],['paprikapulver',3]], s:['Reis (160 g) garen.','Hackfleisch (160 g) mit fein gehackter Zwiebel (40 g), Knoblauch (5 g), Paprikapulver (3 g) und Salz verkneten und zu kleinen Röllchen formen.','In etwas Öl rundum 8 Minuten braten.','Mit Ajvar (30 g) und Reis servieren.'] },
{ n:'Schweinefilet im Speckmantel mit Rosmarinkartoffeln', m:'abend', t:45, mp:1, ing:[['schweinefilet',170],['bacon',30],['kartoffeln',220],['rosmarin',3],['olivenoel',12],['knoblauch',6]], s:['Kartoffeln (220 g) vierteln, mit Rosmarin (3 g), Knoblauch (6 g) und Olivenöl (12 g) mischen und bei 200 Grad 30 Minuten rösten.','Schweinefilet (170 g) salzen und in Bacon (30 g) einwickeln.','In der Pfanne rundum anbraten.','Zu den Kartoffeln in den Ofen geben und die letzten 15 Minuten fertig garen.'] },
{ n:'Rindfleisch-Rouladen mit Kartoffelpüree', m:'abend', t:90, mp:1, ing:[['rindersteak',170],['gewuerzgurke',30],['bacon',30],['senf',10],['kartoffeln',200],['milch',60]], s:['Rindfleisch (170 g) flach klopfen, mit Senf (10 g) bestreichen, mit Bacon (30 g) und Gewürzgurke (30 g) belegen und aufrollen.','Die Roulade rundum kräftig anbraten.','Mit Brühe ablöschen und zugedeckt 70 Minuten schmoren.','Kartoffeln (200 g) mit Milch (60 ml) zu Püree stampfen und mit der Roulade und Soße servieren.'] },
{ n:'Schweinekotelett mit Bratkartoffeln', m:'abend', t:35, ing:[['schweinekotelett',180],['kartoffeln',220],['zwiebel',50],['olivenoel',14],['petersilie',4]], s:['Gekochte Kartoffeln (220 g) in Scheiben mit Zwiebel (50 g) in Olivenöl (14 g) zu Bratkartoffeln braten.','Kotelett (180 g) salzen und pfeffern und in der Pfanne je Seite 4-5 Minuten braten.','Kurz ruhen lassen.','Mit den Bratkartoffeln und Petersilie (4 g) servieren.'] },
{ n:'Hackbraten mit Ei und Kartoffeln', m:'abend', t:65, mp:1, ing:[['hackrind',170],['ei',100],['semmelbroesel',30],['zwiebel',40],['kartoffeln',200],['passata',60]], s:['Zwei der Eier hart kochen und pellen. Hackfleisch (170 g) mit dem restlichen Ei (100 g gesamt), Semmelbröseln (30 g) und Zwiebel (40 g) verkneten.','Die Hackmasse um die gekochten Eier zu einem Laib formen.','In einer Form bei 190 Grad 40 Minuten backen, mit Passata (60 g) bestreichen.','Kartoffeln (200 g) dazu garen und mit der Soße servieren.'] },
{ n:'Gyros mit Zaziki und Reis', m:'abend', t:30, mp:1, ing:[['gyrosfleisch',170],['naturjoghurt',70],['gurke',50],['knoblauch',5],['reis',160],['rotezwiebel',30]], s:['Reis (160 g) garen.','Gyrosfleisch (170 g) in einer heißen Pfanne 6-8 Minuten kräftig anbraten.','Gurke (50 g) raspeln, ausdrücken und mit Joghurt (70 g) und Knoblauch (5 g) zu Zaziki rühren.','Gyros mit Reis, Zaziki und roten Zwiebelringen (30 g) servieren.'] },
{ n:'Rindfleisch-Chili mit Kidneybohnen', m:'abend', t:45, mp:1, ing:[['hackrind',150],['kidneybohnen',120],['mais',60],['passata',160],['paprika',60],['reis',150]], s:['Reis (150 g) garen.','Hackfleisch (150 g) mit Paprika (60 g) krümelig anbraten.','Kidneybohnen (120 g), Mais (60 g) und Passata (160 g) zugeben, mit Kreuzkümmel und Paprikapulver würzen.','20 Minuten sämig köcheln und mit Reis servieren.'] },
{ n:'Kasseler mit Sauerkraut und Kartoffelpüree', m:'abend', t:40, mp:1, ing:[['kasseler',170],['sauerkraut',150],['kartoffeln',200],['milch',60],['zwiebel',40],['senf',8]], s:['Zwiebel (40 g) andünsten, Sauerkraut (150 g) zugeben und 20 Minuten schmoren.','Kasseler (170 g) in der letzten 10 Minuten auf dem Kraut mitziehen lassen.','Kartoffeln (200 g) mit Milch (60 ml) zu Püree stampfen.','Mit Senf (8 g) servieren.'] },
];
