// Snacks, Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Energy Balls mit Datteln', m:'snack', t:15, mp:1, ing:[['datteln',60],['haferflocken',40],['kakao',8],['mandeln',20]], s:['Datteln, Haferflocken, Kakao und Mandeln fein mixen.','Zu Kugeln rollen.','Kalt stellen.'] },
{ n:'Bananen-Nice-Cream', m:'snack', t:5, mp:1, ing:[['banane',150],['erdnussbutter',10],['kakao',4]], s:['Gefrorene Bananenstücke mit Erdnussbutter cremig mixen.','Mit Kakao verfeinern.','Sofort löffeln.'] },
{ n:'Vollkorn-Cracker mit Käse und Trauben', m:'snack', t:4, ing:[['knaeckebrot',30],['gouda',30],['weintrauben',60]], s:['Knäckebrot mit Käse belegen.','Mit Trauben servieren.'] },
{ n:'Skyr mit Zimt und Apfel', m:'snack', t:4, ing:[['skyr',150],['apfel',100],['zimt',1],['honig',6]], s:['Apfel würfeln.','Unter den Skyr heben.','Mit Zimt und Honig abschmecken.'] },
{ n:'Gemüsechips aus dem Ofen', m:'snack', t:30, ing:[['moehren',100],['rote_beete',80],['olivenoel',6],['salz',1]], s:['Gemüse hauchdünn hobeln.','Mit Öl und Salz mischen.','Bei 150 Grad knusprig backen.'] },
{ n:'Protein-Milchshake Vanille', m:'snack', t:4, ing:[['proteinpulver',30],['milch',250],['banane',60]], s:['Alle Zutaten mixen.','In ein Glas füllen.'] },
{ n:'Mozzarella-Sticks aus dem Ofen', m:'snack', t:25, ing:[['mozzarella',80],['semmelbroesel',30],['ei',25]], s:['Mozzarella in Sticks schneiden.','In Ei und Bröseln panieren.','Bei 200 Grad knusprig backen.'] },
{ n:'Apfel-Nuss-Snack', m:'snack', t:3, ing:[['apfel',120],['walnuesse',20],['zimt',1]], s:['Apfel in Spalten schneiden.','Mit Walnüssen und Zimt anrichten.'] },
{ n:'Hüttenkäse-Dip mit Gemüse', m:'snack', t:6, ing:[['huettenkaese',120],['schnittlauch',5],['paprika',60],['gurke',60]], s:['Hüttenkäse mit Schnittlauch würzen.','Gemüse in Sticks schneiden.','Als Dip servieren.'] },
{ n:'Schoko-Chia-Pudding', m:'snack', t:5, mp:1, ing:[['chiasamen',25],['milch',150],['kakao',6],['honig',10],['banane',50]], s:['Chia mit Milch, Kakao und Honig verrühren.','Quellen lassen.','Mit Banane toppen.'] },
{ n:'Rohkostteller mit Kräuterquark', m:'snack', t:8, ing:[['moehren',80],['gurke',80],['paprika',60],['magerquark',100],['schnittlauch',5]], s:['Gemüse in Sticks schneiden.','Quark mit Schnittlauch verrühren.','Als Dip reichen.'] },
{ n:'Geröstete Kichererbsen würzig', m:'snack', t:25, mp:1, ing:[['kichererbsen',150],['olivenoel',6],['paprikapulver',2],['kreuzkuemmel',1]], s:['Kichererbsen trocknen und mit Öl und Gewürzen mischen.','Im Ofen bei 200 Grad 20 Minuten rösten.'] },
{ n:'Beeren-Joghurt-Parfait', m:'snack', t:6, ing:[['naturjoghurt',150],['heidelbeeren',60],['granola',25],['honig',8]], s:['Joghurt, Beeren und Granola schichten.','Mit Honig abschließen.'] },
{ n:'Erdnussbutter-Toast', m:'snack', t:4, ing:[['toastbrot',50],['erdnussbutter',20],['banane',60]], s:['Toast rösten.','Mit Erdnussbutter bestreichen.','Bananenscheiben auflegen.'] },
{ n:'Käse-Trauben-Spieße', m:'snack', t:5, ing:[['gouda',40],['weintrauben',80]], s:['Käsewürfel und Trauben auf Spieße stecken.'] },
{ n:'Protein-Riegel selbstgemacht', m:'snack', t:15, mp:1, ing:[['haferflocken',50],['proteinpulver',20],['erdnussbutter',20],['honig',15]], s:['Alle Zutaten verkneten.','In eine Form drücken.','Kühl stellen und in Riegel schneiden.'] },
{ n:'Tomate-Mozzarella-Snack', m:'snack', t:5, ing:[['tomaten',100],['mozzarella',50],['basilikum',3],['olivenoel',5]], s:['Tomate und Mozzarella in Scheiben schneiden.','Mit Basilikum und Öl anrichten.'] },
{ n:'Obst-Quark-Becher', m:'snack', t:4, ing:[['magerquark',150],['banane',60],['heidelbeeren',50],['honig',8]], s:['Quark cremig rühren.','Obst unterheben.','Mit Honig süßen.'] },
{ n:'Nuss-Frucht-Riegel', m:'snack', t:2, ing:[['mandeln',15],['datteln',30],['kokosraspel',8]], s:['Mandeln und Datteln mixen.','Mit Kokosraspeln zu Riegeln formen.'] },
{ n:'Avocado-Cracker', m:'snack', t:6, ing:[['knaeckebrot',30],['avocado',60],['zitrone',4],['salz',1]], s:['Avocado mit Zitrone und Salz zerdrücken.','Auf Knäckebrot streichen.'] },
{ n:'Warme Milch mit Honig und Zimt', m:'snack', t:6, ing:[['milch',250],['honig',12],['zimt',1]], s:['Milch erwärmen.','Mit Honig süßen.','Mit Zimt bestreuen.'] },
{ n:'Reiswaffel-Türmchen mit Skyr', m:'snack', t:4, ing:[['reiswaffeln',20],['skyr',80],['erdbeeren',50]], s:['Reiswaffeln mit Skyr bestreichen.','Mit Erdbeeren belegen.'] },
{ n:'Käsewürfel mit Gurke', m:'snack', t:4, ing:[['gouda',50],['gurke',100]], s:['Käse und Gurke in Würfel schneiden.','Zusammen anrichten.'] },
{ n:'Schoko-Bananen-Shake', m:'snack', t:4, ing:[['banane',120],['milch',200],['kakao',6],['honig',8]], s:['Alle Zutaten mixen.','In ein Glas füllen.'] },
{ n:'Frischkäse-Gurken-Röllchen', m:'snack', t:8, ing:[['gurke',120],['frischkaese',40],['dill',3]], s:['Gurke längs in Streifen hobeln.','Mit Frischkäse bestreichen.','Aufrollen.'] },
];
