// Nudelgerichte, Teil 6. Von Hand geschrieben.
module.exports = [
{ n:'Spaghetti Bolognese klassisch', m:'abend', t:45, mp:1, ing:[['spaghetti',180],['hackrind',130],['passata',160],['moehren',50],['zwiebel',40],['parmesan',20]], s:['Möhre (50 g) und Zwiebel (40 g) fein würfeln und mit dem Hackfleisch (130 g) krümelig anbraten.','Passata (160 g) und einen Schuss Wasser zugeben und bei kleiner Hitze 30 Minuten sämig köcheln, mit Salz und Pfeffer würzen.','Spaghetti (180 g) bissfest kochen.','Mit der Bolognese anrichten und mit Parmesan (20 g) servieren.'] },
{ n:'Penne mit Zucchini, Speck und Sahne', m:'mittag', t:24, mp:1, ing:[['penne',180],['zucchini',90],['bacon',40],['kochsahne',90],['parmesan',20],['zwiebel',30]], s:['Penne (180 g) bissfest kochen.','Bacon (40 g) und Zwiebel (30 g) anbraten, Zucchini (90 g) in Würfeln zugeben und 4 Minuten mitbraten.','Sahne (90 g) angießen und 3 Minuten köcheln.','Nudeln untermengen und mit Parmesan (20 g) servieren.'] },
{ n:'Tagliatelle mit Hähnchen und Champignons', m:'abend', t:28, mp:1, ing:[['tagliatelle',180],['haehnchen',130],['champignons',90],['kochsahne',90],['zwiebel',40],['petersilie',4]], s:['Tagliatelle (180 g) bissfest kochen.','Hähnchen (130 g) würfeln und mit Zwiebel (40 g) und Champignons (90 g) 6 Minuten kräftig anbraten.','Sahne (90 g) angießen und 3 Minuten cremig köcheln, salzen und pfeffern.','Nudeln untermengen und mit Petersilie (4 g) servieren.'] },
{ n:'Spaghetti mit Pesto und Cherrytomaten', m:'mittag', t:18, ing:[['spaghetti',180],['pesto',30],['cherrytomaten',80],['parmesan',20],['pinienkerne',12]], s:['Spaghetti (180 g) bissfest kochen und etwas Nudelwasser aufheben.','Pesto (30 g) mit einem Löffel Nudelwasser verrühren.','Spaghetti mit dem Pesto und halbierten Cherrytomaten (80 g) mischen.','Mit Parmesan (20 g) und gerösteten Pinienkernen (12 g) servieren.'] },
{ n:'Cremige Lachs-Nudeln mit Erbsen', m:'mittag', t:24, mp:1, ing:[['fusilli',180],['lachs',120],['erbsen',60],['kochsahne',90],['zitrone',8],['dill',3]], s:['Fusilli (180 g) bissfest kochen.','Lachs (120 g) würfeln und in etwas Öl 3-4 Minuten anbraten.','Erbsen (60 g) und Sahne (90 g) zugeben und 3 Minuten köcheln.','Nudeln, Zitronensaft (8 g) und Dill (3 g) untermengen.'] },
{ n:'Nudeln mit Brokkoli, Knoblauch und Öl', m:'mittag', t:22, ing:[['penne',180],['brokkoli',110],['knoblauch',10],['olivenoel',18],['chili',4],['parmesan',20]], s:['Penne (180 g) bissfest kochen. Brokkoli (110 g) die letzten 4 Minuten mitkochen.','Knoblauch (10 g) in Scheiben und Chili (4 g) in Olivenöl (18 g) goldgelb anbraten.','Nudeln und Brokkoli mit etwas Nudelwasser untermengen.','Mit Parmesan (20 g) servieren.'] },
{ n:'Spaghetti mit Garnelen in Tomatensauce', m:'abend', t:26, mp:1, ing:[['spaghetti',180],['garnelen',130],['passata',150],['knoblauch',8],['chili',4],['petersilie',5]], s:['Spaghetti (180 g) bissfest kochen.','Knoblauch (8 g) und Chili (4 g) anbraten, Passata (150 g) zugeben und 6 Minuten köcheln.','Garnelen (130 g) zugeben und 3 Minuten mitgaren.','Spaghetti untermengen und mit Petersilie (5 g) servieren.'] },
{ n:'Ofen-Nudeln mit Hähnchen und Pesto', m:'abend', t:40, mp:1, ing:[['penne',180],['haehnchen',130],['pesto',30],['cherrytomaten',80],['mozzarella',70],['parmesan',20]], s:['Penne (180 g) etwas fester als bissfest kochen. Hähnchen (130 g) würfeln und anbraten.','Nudeln mit Hähnchen, Pesto (30 g) und halbierten Cherrytomaten (80 g) mischen und in eine Form geben.','Mozzarella (70 g) und Parmesan (20 g) darüber verteilen.','Bei 200 Grad 18 Minuten goldbraun überbacken.'] },
{ n:'Spaghetti mit Spinat-Frischkäse-Sauce', m:'mittag', t:22, ing:[['spaghetti',180],['spinat',90],['frischkaese',60],['knoblauch',6],['parmesan',20],['zwiebel',30]], s:['Spaghetti (180 g) bissfest kochen.','Zwiebel (30 g) und Knoblauch (6 g) andünsten, Spinat (90 g) zugeben und zusammenfallen lassen.','Frischkäse (60 g) und einen Schuss Nudelwasser cremig einrühren.','Spaghetti untermengen und mit Parmesan (20 g) servieren.'] },
{ n:'Nudelpfanne mit Hackfleisch und Paprika', m:'abend', t:28, mp:1, ing:[['fusilli',180],['hackrind',130],['paprika',80],['passata',120],['zwiebel',40],['reibekaese',30]], s:['Fusilli (180 g) bissfest kochen.','Hackfleisch (130 g) mit Zwiebel (40 g) und Paprika (80 g) anbraten.','Passata (120 g) zugeben und 6 Minuten köcheln.','Nudeln untermengen, Käse (30 g) unterrühren und schmelzen lassen.'] },
{ n:'Tortellini in Tomaten-Mascarpone-Sauce', m:'mittag', t:20, ing:[['tortellini',220],['passata',120],['mascarpone',60],['basilikum',4],['parmesan',20],['knoblauch',5]], s:['Tortellini (220 g) nach Packung garen.','Knoblauch (5 g) andünsten, Passata (120 g) zugeben und 5 Minuten köcheln.','Mascarpone (60 g) einrühren, bis die Sauce cremig ist.','Tortellini untermengen und mit Basilikum (4 g) und Parmesan (20 g) servieren.'] },
{ n:'Spaghetti Puttanesca mit Oliven', m:'mittag', t:24, mp:1, ing:[['spaghetti',180],['passata',160],['oliven',30],['kapern',12],['knoblauch',8],['chili',4]], s:['Spaghetti (180 g) bissfest kochen.','Knoblauch (8 g) und Chili (4 g) in Öl anbraten.','Passata (160 g), Oliven (30 g) und Kapern (12 g) zugeben und 8 Minuten würzig einkochen.','Spaghetti untermengen und abschmecken.'] },
{ n:'Penne mit Kürbis, Ziegenkäse und Walnuss', m:'abend', t:30, mp:1, ing:[['penne',180],['kuerbis',150],['ziegenkaese',50],['walnuesse',15],['zwiebel',40],['salbei',2]], s:['Penne (180 g) bissfest kochen.','Kürbis (150 g) mit Zwiebel (40 g) in etwas Öl 8 Minuten weich braten und teils zerdrücken.','Ziegenkäse (50 g), Salbei (2 g) und etwas Nudelwasser zu einer cremigen Sauce verrühren.','Nudeln untermengen und mit gehackten Walnüssen (15 g) servieren.'] },
{ n:'Thunfisch-Lauch-Auflauf mit Sahne', m:'abend', t:42, mp:1, ing:[['penne',180],['thunfisch',100],['lauch',80],['kochsahne',110],['reibekaese',60],['zwiebel',30]], s:['Penne (180 g) etwas fester als bissfest kochen.','Lauch (80 g) und Zwiebel (30 g) andünsten, mit Thunfisch (100 g) und Sahne (110 g) mischen.','Mit den Nudeln in eine Form geben.','Mit Käse (60 g) bestreuen und bei 190 Grad 22 Minuten überbacken.'] },
{ n:'Spaghetti mit Zitrone, Ricotta und Basilikum', m:'mittag', t:20, ing:[['spaghetti',180],['ricotta',80],['zitrone',12],['basilikum',5],['parmesan',20],['olivenoel',10]], s:['Spaghetti (180 g) bissfest kochen und etwas Nudelwasser aufheben.','Ricotta (80 g) mit Zitronensaft (12 g), Olivenöl (10 g) und etwas Nudelwasser cremig rühren.','Die heißen Spaghetti untermengen.','Mit Basilikum (5 g) und Parmesan (20 g) servieren.'] },
{ n:'Rigatoni mit Wurst und Fenchel', m:'abend', t:28, mp:1, ing:[['penne',180],['bratwurst',120],['fenchel',80],['passata',140],['zwiebel',40],['parmesan',20]], s:['Penne bzw. Rigatoni (180 g) bissfest kochen.','Bratwurst (120 g) aus der Pelle drücken und mit Zwiebel (40 g) und fein geschnittenem Fenchel (80 g) krümelig anbraten.','Passata (140 g) zugeben und 8 Minuten köcheln.','Nudeln untermengen und mit Parmesan (20 g) servieren.'] },
];
