// Frühstück, Teil 11. Von Hand geschrieben.
module.exports = [
{ n:'Porridge mit Apfel, Walnuss und Ahornsirup', m:'fruh', t:10, ing:[['haferflocken',60],['milch',240],['apfel',90],['walnuesse',15],['ahornsirup',12]], s:['Haferflocken (60 g) mit Milch (240 ml) aufkochen und bei kleiner Hitze 3-4 Minuten cremig köcheln.','Apfel (90 g) würfeln und die Hälfte unterrühren.','In eine Schale füllen und mit dem restlichen Apfel, gehackten Walnüssen (15 g) und Ahornsirup (12 g) toppen.'] },
{ n:'Shakshuka-Frühstück mit Fladenbrot', m:'fruh', t:22, ing:[['ei',120],['passata',130],['paprika',70],['zwiebel',40],['feta',40],['fladenbrot',60]], s:['Zwiebel (40 g) und Paprika (70 g) in etwas Öl 5 Minuten andünsten.','Passata (130 g) zugeben, würzen und 5 Minuten köcheln.','Mulden formen, Eier (120 g) hineingleiten lassen und zugedeckt 6-8 Minuten stocken lassen.','Mit Feta (40 g) bestreuen und mit Fladenbrot (60 g) servieren.'] },
{ n:'Quark mit Leinsamen, Beeren und Honig', m:'fruh', t:5, ing:[['magerquark',200],['heidelbeeren',70],['leinsamen',10],['honig',10],['haferflocken',20]], s:['Magerquark (200 g) mit etwas Wasser und den Haferflocken (20 g) cremig verrühren.','In eine Schale geben und mit Heidelbeeren (70 g) toppen.','Leinsamen (10 g) und Honig (10 g) darüber geben.'] },
{ n:'French Toast mit Beeren', m:'fruh', t:15, ing:[['toastbrot',90],['ei',100],['milch',60],['heidelbeeren',60],['ahornsirup',12],['butter',8]], s:['Ei (100 g) mit Milch (60 ml) und einer Prise Zimt verquirlen.','Toast (90 g) darin von beiden Seiten tränken.','In der Butter (8 g) je Seite 2-3 Minuten goldbraun braten.','Mit Heidelbeeren (60 g) und Ahornsirup (12 g) servieren.'] },
{ n:'Overnight Oats mit Kakao und Banane', m:'fruh', t:5, mp:1, ing:[['haferflocken',60],['milch',180],['banane',90],['kakao',6],['honig',8]], s:['Haferflocken (60 g), Milch (180 ml), Kakao (6 g) und Honig (8 g) in ein Glas geben und verrühren.','Zugedeckt über Nacht kühlen.','Am Morgen umrühren und mit Bananenscheiben (90 g) toppen.'] },
{ n:'Rührei mit Champignons und Schnittlauch', m:'fruh', t:14, ing:[['ei',150],['champignons',70],['schnittlauch',4],['vollkornbrot',60],['butter',8]], s:['Champignons (70 g) in der Butter (8 g) 4 Minuten anbraten.','Verquirlte Eier (150 g) zugeben und bei mittlerer Hitze cremig stocken lassen.','Mit Schnittlauch (4 g) bestreuen und mit dem Brot (60 g) servieren.'] },
{ n:'Joghurt-Bowl mit Mango und Kokos', m:'fruh', t:5, ing:[['naturjoghurt',200],['mango',80],['kokosraspel',8],['granola',30],['honig',8]], s:['Joghurt (200 g) in eine Schale geben.','Mangowürfel (80 g) und Granola (30 g) daraufgeben.','Mit Kokosraspeln (8 g) und Honig (8 g) toppen.'] },
{ n:'Vollkornbrot mit Avocado-Frischkäse und Tomate', m:'fruh', t:8, ing:[['vollkornbrot',90],['frischkaese',40],['avocado',50],['tomaten',40],['kresse',5]], s:['Avocado (50 g) mit Frischkäse (40 g), Salz und Pfeffer cremig verrühren.','Auf das Vollkornbrot (90 g) streichen.','Mit Tomatenscheiben (40 g) belegen und mit Kresse (5 g) bestreuen.'] },
{ n:'Grießbrei mit Zimt und Apfelkompott', m:'fruh', t:15, ing:[['griess',60],['milch',280],['apfel',90],['zimt',2],['honig',10]], s:['Milch (280 ml) aufkochen, Grieß (60 g) einrühren und unter Rühren 3 Minuten andicken lassen.','Apfel (90 g) würfeln und mit etwas Wasser und Zimt (2 g) zu einem Kompott einkochen.','Grießbrei mit Honig (10 g) süßen und mit dem Apfelkompott servieren.'] },
{ n:'Protein-Waffeln mit Quark und Beeren', m:'fruh', t:20, ing:[['haferflocken',50],['ei',100],['magerquark',80],['proteinpulver',20],['himbeeren',60],['backpulver',3]], s:['Haferflocken (50 g), Ei (100 g), Magerquark (80 g), Proteinpulver (20 g) und Backpulver (3 g) zu einem glatten Teig verrühren.','Im Waffeleisen goldbraun backen.','Mit etwas Quark und Himbeeren (60 g) servieren.'] },
{ n:'Avocado-Brot mit pochiertem Ei', m:'fruh', t:14, ing:[['vollkornbrot',90],['avocado',70],['ei',60],['chiliflocken',1],['zitrone',6]], s:['Avocado (70 g) mit Zitronensaft (6 g), Salz und Pfeffer zerdrücken und auf das Brot (90 g) streichen.','Wasser mit einem Schuss Essig zum Sieden bringen und das Ei (60 g) 3-4 Minuten pochieren.','Das Ei abtropfen, auf das Brot setzen und mit Chiliflocken (1 g) bestreuen.'] },
{ n:'Chia-Pudding mit Himbeeren und Mandeln', m:'fruh', t:5, mp:1, ing:[['chiasamen',30],['milch',200],['himbeeren',70],['mandeln',12],['honig',8]], s:['Chiasamen (30 g) mit Milch (200 ml) und Honig (8 g) verrühren, 10 Minuten warten und erneut rühren.','Zugedeckt über Nacht quellen lassen.','Mit Himbeeren (70 g) und gehackten Mandeln (12 g) toppen.'] },
{ n:'Haferflocken-Pfannkuchen mit Apfel', m:'fruh', t:18, ing:[['haferflocken',50],['ei',100],['milch',60],['apfel',80],['zimt',2],['honig',10]], s:['Haferflocken (50 g), Ei (100 g) und Milch (60 ml) zu einem Teig verrühren und 5 Minuten quellen lassen.','Apfel (80 g) fein raspeln und mit Zimt (2 g) unterheben.','In etwas Öl portionsweise je Seite 2-3 Minuten backen.','Mit Honig (10 g) beträufeln.'] },
{ n:'Skyr mit Pfirsich und Haferknusper', m:'fruh', t:5, ing:[['skyr',200],['pfirsich',80],['granola',30],['honig',8],['mandeln',10]], s:['Skyr (200 g) in eine Schale geben.','Pfirsich (80 g) in Spalten schneiden und mit Granola (30 g) daraufgeben.','Mit gehackten Mandeln (10 g) und Honig (8 g) toppen.'] },
{ n:'Käse-Omelett mit Kräutern', m:'fruh', t:12, ing:[['ei',150],['bergkaese',40],['petersilie',3],['schnittlauch',3],['vollkornbrot',60],['butter',8]], s:['Eier (150 g) verquirlen, salzen und in der Butter (8 g) bei mittlerer Hitze angießen.','Wenn die Unterseite stockt, geriebenen Bergkäse (40 g) und die Kräuter (je 3 g) darauf verteilen.','Das Omelett zusammenklappen und mit dem Brot (60 g) servieren.'] },
{ n:'Beeren-Smoothie-Bowl mit Granola', m:'fruh', t:8, ing:[['heidelbeeren',80],['banane',80],['naturjoghurt',100],['granola',30],['chiasamen',8]], s:['Heidelbeeren (80 g), Banane (80 g) und Joghurt (100 g) zu einer dicken Masse pürieren.','In eine Schale füllen.','Mit Granola (30 g) und Chiasamen (8 g) toppen.'] },
];
