// Orientalische & türkische Küche. Von Hand geschrieben.
module.exports = [
{ n:'Adana-Kebap mit Bulgur und Joghurt', m:'abend', t:32, mp:1, ing:[['hackrind',160],['zwiebel',40],['paprikapulver',3],['bulgur',150],['naturjoghurt',60],['petersilie',5]], s:['Hackfleisch (160 g) mit fein geriebener Zwiebel (40 g), Paprikapulver (3 g), Salz und Pfeffer kräftig verkneten.','Die Masse länglich um Spieße bzw. zu Röllchen formen.','In der Grillpfanne rundum 8-10 Minuten braten.','Bulgur (150 g) 12 Minuten quellen lassen und mit Joghurt (60 g) und Petersilie (5 g) servieren.'] },
{ n:'Köfte mit Reis und Tomatensauce', m:'abend', t:35, mp:1, ing:[['hackrind',160],['semmelbroesel',25],['zwiebel',40],['passata',140],['reis',160],['minze',3]], s:['Reis (160 g) garen.','Hackfleisch (160 g) mit Semmelbröseln (25 g), Zwiebel (40 g) und Gewürzen verkneten und zu kleinen Köfte formen.','In etwas Öl rundum anbraten.','Passata (140 g) angießen, die Köfte darin 10 Minuten schmoren und mit Minze (3 g) und Reis servieren.'] },
{ n:'Linsensuppe türkisch (Mercimek)', m:'mittag', t:35, mp:1, ing:[['rotelinsen',160],['moehren',60],['kartoffeln',80],['zwiebel',40],['bruehe',350],['zitrone',10]], s:['Zwiebel (40 g) und Möhre (60 g) würfeln und andünsten.','Rote Linsen (160 g), gewürfelte Kartoffel (80 g) und Brühe (350 ml) zugeben und 20 Minuten weich kochen.','Fein pürieren und mit Salz und Kreuzkümmel abschmecken.','Mit Zitrone (10 g) beträufelt servieren.'] },
{ n:'Iskender-Teller mit Joghurt und Tomatensauce', m:'abend', t:30, mp:1, ing:[['gyrosfleisch',160],['fladenbrot',80],['naturjoghurt',70],['passata',80],['butter',12],['minze',2]], s:['Fladenbrot (80 g) in Würfel schneiden und auf einen Teller legen.','Gyrosfleisch (160 g) in einer heißen Pfanne 6-8 Minuten kräftig anbraten und auf das Brot geben.','Passata (80 g) kurz erwärmen und mit der geschmolzenen Butter (12 g) darüber verteilen.','Joghurt (70 g) daneben anrichten und mit Minze (2 g) bestreuen.'] },
{ n:'Menemen mit Ei und Paprika', m:'fruh', t:20, ing:[['ei',150],['tomaten',120],['paprika',80],['zwiebel',40],['fladenbrot',60],['olivenoel',12]], s:['Zwiebel (40 g) und Paprika (80 g) in Olivenöl (12 g) 5 Minuten schmoren.','Tomaten (120 g) würfeln, zugeben und 5 Minuten einkochen.','Eier (150 g) verquirlen, hineinrühren und bei kleiner Hitze cremig stocken lassen.','Mit Fladenbrot (60 g) servieren.'] },
{ n:'Falafel-Teller mit Hummus und Salat', m:'mittag', t:30, mp:1, ing:[['kichererbsen',150],['hummus',60],['fladenbrot',80],['tomaten',60],['gurke',50],['tahin',15]], s:['Kichererbsen (150 g) mit Gewürzen zerkleinern, zu Bällchen formen und in heißem Öl goldbraun braten.','Tomaten (60 g) und Gurke (50 g) klein schneiden.','Falafel mit Hummus (60 g) und dem Salat auf einem Teller anrichten.','Mit Tahin (15 g) beträufeln und mit Fladenbrot (80 g) servieren.'] },
{ n:'Lahmacun mit Hackfleisch und Salat', m:'mittag', t:30, mp:1, ing:[['fladenbrot',120],['hackrind',110],['passata',60],['zwiebel',40],['petersilie',6],['zitrone',8]], s:['Hackfleisch (110 g) mit fein gehackter Zwiebel (40 g), Passata (60 g), Petersilie (6 g) und Gewürzen mischen.','Die Masse dünn auf das Fladenbrot (120 g) streichen.','Bei 220 Grad 10-12 Minuten knusprig backen.','Mit Zitrone (8 g) beträufeln, etwas Salat aufstreuen und einrollen.'] },
{ n:'Bulgur-Pilaw mit Kichererbsen', m:'mittag', t:28, mp:1, ing:[['bulgur',170],['kichererbsen',100],['tomaten',60],['zwiebel',40],['tomatenmark',15],['petersilie',5]], s:['Zwiebel (40 g) und Tomatenmark (15 g) in etwas Öl anrösten.','Gewürfelte Tomaten (60 g), Bulgur (170 g) und Kichererbsen (100 g) zugeben.','Mit der doppelten Menge Brühe aufgießen und zugedeckt 15 Minuten quellen lassen.','Mit Petersilie (5 g) auflockern.'] },
{ n:'Hähnchen-Schawarma mit Fladenbrot', m:'abend', t:30, mp:1, ing:[['haehnchen',160],['fladenbrot',90],['naturjoghurt',60],['knoblauch',5],['tomaten',50],['rotkohl',40]], s:['Hähnchen (160 g) mit Kreuzkümmel, Paprika und Öl würzen und in der Pfanne 6-8 Minuten braten, in Streifen schneiden.','Joghurt (60 g) mit Knoblauch (5 g) und Salz verrühren.','Rotkohl (40 g) fein hobeln und Tomaten (50 g) schneiden.','Fladenbrot (90 g) mit Hähnchen, Gemüse und Knoblauchjoghurt füllen.'] },
{ n:'Gefüllte Auberginen (Imam Bayildi)', m:'abend', t:50, mp:1, ing:[['aubergine',220],['tomaten',90],['zwiebel',50],['knoblauch',6],['olivenoel',18],['petersilie',5]], s:['Auberginen (220 g) längs halbieren, das Fruchtfleisch einschneiden und in Olivenöl (18 g) anbraten.','Zwiebel (50 g), Knoblauch (6 g) und Tomaten (90 g) zu einer Füllung schmoren.','Die Auberginen damit belegen und in eine Form legen.','Mit etwas Wasser bei 190 Grad 30 Minuten schmoren und mit Petersilie (5 g) servieren.'] },
{ n:'Sucuk mit Ei und Fladenbrot', m:'fruh', t:15, ing:[['sucuk',80],['ei',120],['fladenbrot',70],['tomaten',40]], s:['Sucuk (80 g) in Scheiben schneiden und in der Pfanne 3 Minuten anbraten, bis das Fett austritt.','Eier (120 g) darübergeben und bei mittlerer Hitze stocken lassen.','Mit Tomatenspalten (40 g) und Fladenbrot (70 g) servieren.'] },
{ n:'Kisir (türkischer Bulgursalat)', m:'mittag', t:22, mp:1, ing:[['bulgur',160],['tomatenmark',15],['petersilie',10],['tomaten',60],['zitrone',10],['olivenoel',10]], s:['Bulgur (160 g) mit kochendem Wasser übergießen und 15 Minuten quellen lassen.','Tomatenmark (15 g), Olivenöl (10 g) und Zitrone (10 g) unterrühren.','Reichlich Petersilie (10 g) und gewürfelte Tomaten (60 g) untermischen.','Mit Salz und etwas Chili abschmecken.'] },
{ n:'Manti mit Joghurt und Butter', m:'abend', t:45, mp:1, ing:[['gyozateig',140],['hackrind',110],['zwiebel',40],['naturjoghurt',80],['butter',15],['paprikapulver',3]], s:['Hackfleisch (110 g) mit fein geriebener Zwiebel (40 g) und Gewürzen mischen.','Die Teigblätter (140 g) mit wenig Füllung füllen und zu kleinen Täschchen verschließen.','In Salzwasser 8-10 Minuten garen.','Mit Knoblauchjoghurt (80 g) übergießen und die in Paprikapulver (3 g) aufgeschäumte Butter (15 g) darüberträufeln.'] },
{ n:'Hähnchen-Tajine mit Oliven und Zitrone', m:'abend', t:50, mp:1, ing:[['haehnchen',170],['oliven',30],['zitrone',12],['zwiebel',50],['couscous',150],['raselhanout',4]], s:['Hähnchen (170 g) mit Zwiebel (50 g) und Ras el Hanout (4 g) in etwas Öl anbraten.','Mit etwas Wasser, Oliven (30 g) und Zitrone (12 g) zugedeckt 25 Minuten schmoren.','Couscous (150 g) mit kochendem Wasser übergießen und 5 Minuten quellen lassen.','Die Tajine mit dem Couscous servieren.'] },
{ n:'Fladenbrot-Pizza mit Hackfleisch und Feta', m:'abend', t:28, mp:1, ing:[['fladenbrot',120],['hackrind',110],['passata',70],['feta',50],['paprika',50],['zwiebel',30]], s:['Fladenbrot (120 g) mit Passata (70 g) bestreichen.','Hackfleisch (110 g) mit Zwiebel (30 g) würzen und roh auf dem Brot verteilen, mit Paprika (50 g) belegen.','Feta (50 g) darüberbröseln.','Bei 220 Grad 12-14 Minuten backen, bis das Hack durch und der Rand knusprig ist.'] },
{ n:'Rote-Linsen-Köfte (Mercimek Köftesi)', m:'mittag', t:30, mp:1, ing:[['rotelinsen',150],['bulgur',80],['tomatenmark',15],['fruehlingszwiebel',20],['zitrone',10],['petersilie',6]], s:['Rote Linsen (150 g) weich kochen, Bulgur (80 g) zugeben und zugedeckt quellen lassen.','Tomatenmark (15 g), Frühlingszwiebeln (20 g) und Petersilie (6 g) unterkneten und würzen.','Mit angefeuchteten Händen zu länglichen Köfte formen.','Mit Zitrone (10 g) beträufelt und auf Salatblättern servieren.'] },
];
