// Sättigende Salate, Teil 5. Von Hand geschrieben.
module.exports = [
{ n:'Bunter Quinoa-Salat mit Avocado und Mais', m:'mittag', t:25, mp:1, ing:[['quinoa',160],['avocado',60],['mais',60],['cherrytomaten',60],['limette',8],['koriandergruen',5]], s:['Quinoa garen und abkühlen.','Mit Avocado, Mais und Tomaten mischen.','Mit Limette und Koriander abschmecken.'] },
{ n:'Gerösteter Kürbis-Salat mit Feta', m:'mittag', t:35, mp:1, ing:[['kuerbis',180],['feta',50],['rucola',40],['kuerbiskerne',15],['balsamico',10],['olivenoel',10]], s:['Kürbis im Ofen rösten.','Mit Rucola und Feta anrichten.','Mit Kürbiskernen und Balsamico toppen.'] },
{ n:'Pasta-Salat mit Pesto und Tomaten', m:'mittag', t:22, mp:1, ing:[['fusilli',170],['pesto',25],['cherrytomaten',80],['mozzarella',60],['rucola',30],['pinienkerne',12]], s:['Nudeln kochen und abkühlen.','Mit Pesto und Tomaten mischen.','Mozzarella und Pinienkerne zugeben.'] },
{ n:'Rindfleischsalat thailändisch (Yam Nua)', m:'mittag', t:25, mp:1, ing:[['rindersteak',140],['gurke',60],['cherrytomaten',60],['rotezwiebel',30],['limette',10],['sojasauce',12]], s:['Rind braten und in Streifen schneiden.','Mit Gurke, Tomaten und Zwiebel mischen.','Mit Limetten-Sojadressing anmachen.'] },
{ n:'Linsensalat mit Ziegenkäse und Walnuss', m:'mittag', t:28, mp:1, ing:[['linsen',160],['ziegenkaese',50],['rote_beete',80],['walnuesse',20],['balsamico',10],['olivenoel',10]], s:['Linsen garen und abkühlen.','Mit Rote Bete mischen.','Ziegenkäse und Walnüsse zugeben.'] },
{ n:'Caprese-Salat mit Avocado', m:'mittag', t:12, ing:[['mozzarella',100],['tomaten',120],['avocado',70],['basilikum',5],['olivenoel',12],['balsamico',8]], s:['Tomate, Mozzarella und Avocado in Scheiben schichten.','Mit Basilikum belegen.','Mit Öl und Balsamico beträufeln.'] },
{ n:'Hähnchen-Mango-Salat mit Curry-Dressing', m:'mittag', t:22, mp:1, ing:[['haehnchen',130],['mango',70],['salat',80],['naturjoghurt',50],['currypul',3],['cashews',15]], s:['Hähnchen braten.','Mit Salat und Mango anrichten.','Mit Curry-Joghurt-Dressing und Cashews servieren.'] },
{ n:'Griechischer Bulgursalat mit Feta', m:'mittag', t:22, mp:1, ing:[['bulgur',160],['feta',50],['tomaten',60],['gurke',60],['oliven',25],['olivenoel',10]], s:['Bulgur quellen lassen.','Mit Tomate, Gurke und Oliven mischen.','Feta und Öl zugeben.'] },
{ n:'Wurstsalat schwäbisch mit Zwiebeln', m:'abend', t:15, ing:[['gyrosfleisch',110],['gewuerzgurke',40],['rotezwiebel',30],['essig',10],['olivenoel',10],['schnittlauch',4]], s:['Wurst in Streifen schneiden.','Mit Gurke und Zwiebel mischen.','Mit Essig-Öl-Dressing anmachen.'] },
{ n:'Couscous-Salat mit Kichererbsen und Minze', m:'mittag', t:22, mp:1, ing:[['couscous',160],['kichererbsen',100],['gurke',60],['tomaten',60],['minze',4],['zitrone',10]], s:['Couscous quellen lassen.','Mit Kichererbsen und Gemüse mischen.','Mit Minze und Zitrone abschmecken.'] },
{ n:'Garnelen-Mango-Salat mit Chili-Limette', m:'mittag', t:18, ing:[['garnelen',130],['mango',70],['salat',80],['gurke',60],['limette',10],['chili',3]], s:['Garnelen braten.','Mit Salat, Mango und Gurke anrichten.','Mit Chili-Limetten-Dressing beträufeln.'] },
{ n:'Rote-Linsen-Salat mit Feta und Granatapfel', m:'mittag', t:25, mp:1, ing:[['rotelinsen',150],['feta',50],['granatapfel2',40],['gurke',50],['minze',4],['olivenoel',10]], s:['Linsen bissfest garen und abkühlen.','Mit Gurke und Granatapfel mischen.','Feta und Minze zugeben.'] },
{ n:'Kichererbsen-Thunfisch-Salat', m:'mittag', t:15, mp:1, ing:[['kichererbsen',130],['thunfisch',100],['rotezwiebel',30],['petersilie',5],['zitrone',10],['olivenoel',10]], s:['Kichererbsen abspülen.','Mit Thunfisch und Zwiebel mischen.','Mit Zitrone und Öl abschmecken.'] },
{ n:'Fenchel-Orangen-Salat mit Oliven', m:'mittag', t:15, ing:[['fenchel',120],['orange',90],['oliven',30],['rotezwiebel',30],['olivenoel',10],['zitrone',8]], s:['Fenchel dünn hobeln.','Mit Orangenfilets und Oliven mischen.','Mit Öl und Zitrone anmachen.'] },
{ n:'Tabouleh mit viel Petersilie', m:'mittag', t:20, mp:1, ing:[['bulgur',120],['petersilie',25],['tomaten',80],['minze',6],['zitrone',12],['olivenoel',12]], s:['Bulgur quellen lassen.','Mit reichlich Petersilie und Minze mischen.','Mit Tomate, Zitrone und Öl abschmecken.'] },
{ n:'Ofengemüse-Salat mit Ziegenkäse und Honig', m:'mittag', t:35, mp:1, ing:[['zucchini',80],['paprika',80],['aubergine',80],['ziegenkaese',60],['rucola',30],['honig',10]], s:['Gemüse rösten.','Ziegenkäse kurz überbacken.','Mit Rucola und Honig anrichten.'] },
];
