// Vegane Hauptgerichte, Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Rote-Linsen-Dal mit Spinat und Naan', m:'abend', t:32, mp:1, ing:[['rotelinsen',160],['kokosmilch',110],['spinat',70],['zwiebel',40],['garam_masala',4],['naanbrot',90]], s:['Zwiebel andünsten.','Linsen, Spinat und Kokosmilch köcheln.','Mit Naan servieren.'] },
{ n:'Kichererbsen-Spinat-Curry vegan', m:'abend', t:30, mp:1, ing:[['kichererbsen',160],['spinat',90],['kokosmilch',110],['passata',80],['garam_masala',4],['reis',160]], s:['Zwiebel und Gewürze anrösten.','Kichererbsen, Spinat und Kokosmilch köcheln.','Mit Reis servieren.'] },
{ n:'Gebratener Tofu mit Brokkoli und Reis', m:'abend', t:26, mp:1, ing:[['tofu',160],['brokkoli',110],['sojasauce',16],['knoblauch',6],['reis',160],['sesam',6]], s:['Tofu knusprig braten.','Brokkoli dämpfen.','Mit Sojasauce, Reis und Sesam servieren.'] },
{ n:'Vegane Bolognese mit Linsen', m:'abend', t:35, mp:1, ing:[['spaghetti',180],['rotelinsen',120],['passata',160],['moehren',50],['zwiebel',40],['olivenoel',10]], s:['Zwiebel und Möhre andünsten.','Linsen und Passata köcheln.','Mit Spaghetti servieren.'] },
{ n:'Süßkartoffel-Bohnen-Chili', m:'abend', t:35, mp:1, ing:[['suesskartoffel',160],['kidneybohnen',120],['mais',60],['passata',150],['paprika',60],['reis',150]], s:['Süßkartoffel anbraten.','Bohnen, Mais und Passata köcheln.','Mit Reis servieren.'] },
{ n:'Gemüse-Curry mit Kokos und Kichererbsen', m:'abend', t:32, mp:1, ing:[['blumenkohl',120],['kichererbsen',100],['kokosmilch',120],['erbsen',50],['currypul',4],['reis',160]], s:['Gemüse anbraten.','Kichererbsen und Kokosmilch zugeben.','Mit Reis servieren.'] },
{ n:'Erdnuss-Tofu-Wok mit Gemüse', m:'mittag', t:26, mp:1, ing:[['tofu',150],['paprika',70],['brokkoli',70],['erdnussbutter',22],['sojasauce',14],['reis',160]], s:['Tofu braten.','Gemüse zugeben.','Mit Erdnusssauce und Reis servieren.'] },
{ n:'Vegane Falafel-Bowl mit Rote Bete und Tahin', m:'mittag', t:32, mp:1, ing:[['kichererbsen',140],['quinoa',140],['rote_beete',90],['rotkohl',50],['tahin',20],['gurke',50]], s:['Falafel braten.','Quinoa garen.','Mit Rote Bete, Rotkohl, Gurke und Tahin anrichten.'] },
{ n:'Linsen-Gemüse-Eintopf vegan', m:'abend', t:40, mp:1, ing:[['linsen',160],['moehren',70],['kartoffeln',120],['lauch',50],['passata',80],['bruehe',350]], s:['Gemüse andünsten.','Linsen, Passata und Brühe zugeben.','Weich köcheln.'] },
{ n:'Falafel mit Hummus und Salat vegan', m:'mittag', t:30, mp:1, ing:[['kichererbsen',160],['hummus',60],['fladenbrot',80],['tomaten',60],['gurke',50],['tahin',15]], s:['Falafel braten.','Mit Hummus und Salat anrichten.','Mit Tahin beträufeln.'] },
{ n:'Gebratene Gnocchi mit Gemüse vegan', m:'abend', t:26, mp:1, ing:[['gnocchi',240],['zucchini',80],['cherrytomaten',90],['knoblauch',6],['olivenoel',12],['basilikum',4]], s:['Gnocchi anbraten.','Zucchini und Tomaten zugeben.','Mit Basilikum servieren.'] },
{ n:'Kürbis-Kokos-Suppe vegan', m:'mittag', t:30, mp:1, ing:[['kuerbis',220],['kokosmilch',110],['zwiebel',40],['ingwer',6],['bruehe',300],['kuerbiskerne',10]], s:['Kürbis und Zwiebel anbraten.','Mit Brühe weich kochen und pürieren.','Kokosmilch und Ingwer unterrühren.'] },
{ n:'Vegane Gemüsepfanne mit Erdnussreis', m:'mittag', t:26, mp:1, ing:[['reis',160],['paprika',70],['zucchini',70],['moehren',50],['erdnussbutter',20],['sojasauce',12]], s:['Gemüse anbraten.','Reis zugeben.','Mit Erdnuss-Sojasauce abschmecken.'] },
{ n:'Ofen-Kichererbsen mit Blumenkohl und Erdnusssauce', m:'abend', t:40, mp:1, ing:[['kichererbsen',150],['blumenkohl',180],['paprika',70],['erdnussbutter',22],['sojasauce',10],['reis',150]], s:['Kichererbsen und Gemüse rösten.','Erdnusssauce anrühren.','Mit Reis anrichten.'] },
{ n:'Vegane Linsen-Frikadellen mit Salat', m:'abend', t:38, mp:1, ing:[['linsen',150],['haferflocken',40],['zwiebel',40],['moehren',50],['salat',60],['olivenoel',12]], s:['Linsen garen und mit Haferflocken zu Frikadellen formen.','Braten.','Mit Salat servieren.'] },
{ n:'Reisnudel-Gemüse-Pfanne mit Tofu', m:'mittag', t:24, mp:1, ing:[['reisnudeln',160],['tofu',130],['paprika',60],['moehren',50],['sojasauce',16],['limette',6]], s:['Tofu braten.','Gemüse und Nudeln zugeben.','Mit Sojasauce und Limette abschmecken.'] },
];
