// Asiatische Küche (China & Japan). Von Hand geschrieben.
module.exports = [
{ n:'Gebratener Reis mit Garnelen und Ananas', m:'mittag', t:24, mp:1, ing:[['reis',180],['garnelen',110],['ananas',60],['erbsen',50],['sojasauce',16],['fruehlingszwiebel',20]], s:['Reis in der Pfanne anbraten.','Garnelen, Ananas und Erbsen zugeben.','Mit Sojasauce würzen.'] },
{ n:'Mapo Tofu mit Reis', m:'abend', t:28, mp:1, ing:[['tofu',180],['hackrind',80],['sojasauce',16],['chili',6],['reis',160],['fruehlingszwiebel',20]], s:['Hack scharf anbraten.','Tofu und würzige Sauce zugeben.','Mit Reis servieren.'] },
{ n:'Chicken Chow Mein mit Mie-Nudeln', m:'abend', t:26, mp:1, ing:[['mienudeln',180],['haehnchen',130],['weisskohl',70],['moehren',50],['sojasauce',16],['sesam',5]], s:['Hähnchen anbraten.','Gemüse und Nudeln zugeben.','Mit Sojasauce und Sesam schwenken.'] },
{ n:'Teriyaki-Lachs mit Reis und Brokkoli', m:'abend', t:26, mp:1, ing:[['lachs',150],['teriyakisauce',22],['reis',160],['brokkoli',90],['sesam',6],['fruehlingszwiebel',15]], s:['Lachs braten und mit Teriyaki glasieren.','Reis und Brokkoli garen.','Mit Sesam servieren.'] },
{ n:'Gyoza mit Hähnchenfüllung', m:'abend', t:35, mp:1, ing:[['gyozateig',140],['haehnchen',110],['weisskohl',70],['ingwer',6],['sojasauce',16],['sesam',5]], s:['Hähnchen und Kohl zu Füllung hacken.','Gyoza füllen und braten.','Mit Sojadip servieren.'] },
{ n:'Ramen mit Ei und Hähnchen', m:'abend', t:35, mp:1, ing:[['mienudeln',160],['haehnchen',120],['ei',50],['fruehlingszwiebel',20],['miso',18],['bruehe',400]], s:['Brühe mit Miso würzen.','Hähnchen und Nudeln garen.','Mit Ei und Frühlingszwiebeln servieren.'] },
{ n:'Süß-saures Hähnchen mit Ananas', m:'abend', t:28, mp:1, ing:[['haehnchen',150],['ananas',70],['paprika',70],['tomatenmark',15],['essig',10],['reis',160]], s:['Hähnchen anbraten.','Ananas und Paprika zugeben.','Süß-saure Sauce anrühren, mit Reis servieren.'] },
{ n:'Rindfleisch mit Broccoli in Austernsauce', m:'abend', t:24, mp:1, ing:[['rindersteak',150],['brokkoli',110],['austernsauce',18],['knoblauch',6],['reis',160],['sesam',5]], s:['Rind scharf anbraten.','Brokkoli zugeben.','Mit Austernsauce und Reis servieren.'] },
{ n:'Yakisoba mit Gemüse und Schwein', m:'abend', t:26, mp:1, ing:[['mienudeln',180],['schweinefilet',120],['weisskohl',70],['moehren',50],['sojasauce',16],['ingwer',5]], s:['Schwein anbraten.','Gemüse und Nudeln zugeben.','Mit Sojasauce schwenken.'] },
{ n:'Miso-Lachs aus dem Ofen mit Reis', m:'abend', t:28, mp:1, ing:[['lachs',150],['miso',20],['honig',10],['reis',160],['pak_choi',80],['sesam',5]], s:['Lachs mit Miso-Honig bestreichen.','Im Ofen garen.','Mit Reis und Pak Choi servieren.'] },
{ n:'Katsu-Curry mit Hähnchen, Reis und Möhre', m:'abend', t:38, mp:1, ing:[['haehnchen',150],['ei',50],['panko',40],['reis',160],['moehren',60],['currypul',4]], s:['Hähnchen in Panko panieren und braten.','Möhren-Currysauce köcheln.','Mit Reis und Sauce servieren.'] },
{ n:'Wan-Tan-Suppe mit Gemüse', m:'mittag', t:30, mp:1, ing:[['gyozateig',120],['haehnchen',90],['pak_choi',70],['ingwer',6],['bruehe',400],['fruehlingszwiebel',15]], s:['Wan-Tan mit Hähnchen füllen.','In Brühe garen.','Mit Pak Choi und Frühlingszwiebeln servieren.'] },
{ n:'Gebratene Nudeln mit Tofu und Erdnuss', m:'mittag', t:24, mp:1, ing:[['mienudeln',180],['tofu',130],['paprika',60],['erdnussbutter',22],['sojasauce',14],['limette',6]], s:['Tofu braten.','Gemüse und Nudeln zugeben.','Mit Erdnuss-Sojasauce schwenken.'] },
{ n:'Pekingente-Style Hähnchen mit Pfannkuchen', m:'abend', t:35, mp:1, ing:[['haehnchen',150],['hoisin',25],['gurke',50],['fruehlingszwiebel',20],['wrap',100],['sesam',4]], s:['Hähnchen braten und mit Hoisin glasieren.','Dünne Pfannkuchen erwärmen.','Mit Gurke und Frühlingszwiebeln füllen.'] },
{ n:'Edamame-Reis-Bowl mit Sesam', m:'mittag', t:22, mp:1, ing:[['reis',170],['edamame',80],['moehren',50],['avocado',50],['sojasauce',12],['sesam',6]], s:['Reis kochen.','Edamame garen.','Mit Möhre, Avocado und Sesam anrichten.'] },
{ n:'Chinesische Gemüsepfanne mit Cashews', m:'mittag', t:24, mp:1, ing:[['brokkoli',80],['paprika',70],['moehren',60],['cashews',25],['sojasauce',14],['reis',160]], s:['Gemüse scharf anbraten.','Cashews zugeben.','Mit Sojasauce und Reis servieren.'] },
];
