// Suppen & Eintöpfe, Teil 5. Von Hand geschrieben.
module.exports = [
{ n:'Afrikanische Erdnuss-Süßkartoffel-Suppe mit Spinat', m:'mittag', t:34, mp:1, ing:[['suesskartoffel',200],['erdnussbutter',22],['spinat',60],['passata',80],['zwiebel',40],['bruehe',320]], s:['Süßkartoffel und Zwiebel anbraten.','Mit Passata und Brühe köcheln.','Erdnussbutter und Spinat unterrühren.'] },
{ n:'Tom Kha Gai mit Hähnchen', m:'mittag', t:30, mp:1, ing:[['haehnchen',130],['kokosmilch',150],['champignons',70],['limette',10],['ingwer',8],['bruehe',280]], s:['Brühe mit Ingwer und Kokosmilch erhitzen.','Hähnchen und Pilze garen.','Mit Limette abschmecken.'] },
{ n:'Weiße-Bohnen-Suppe mit Rosmarin', m:'mittag', t:30, mp:1, ing:[['weissebohnen',180],['moehren',60],['sellerie',50],['rosmarin',2],['bruehe',350],['olivenoel',10]], s:['Gemüse andünsten.','Bohnen und Brühe zugeben, teils pürieren.','Mit Rosmarin und Öl abschmecken.'] },
{ n:'Fenchel-Tomaten-Suppe mit Orange', m:'mittag', t:28, mp:1, ing:[['fenchel',150],['passata',180],['orange',60],['zwiebel',40],['bruehe',280],['olivenoel',10]], s:['Fenchel und Zwiebel andünsten.','Passata und Brühe zugeben, pürieren.','Mit Orange abschmecken.'] },
{ n:'Grüne Erbsensuppe mit Croutons', m:'mittag', t:25, mp:1, ing:[['erbsen',200],['kartoffeln',70],['zwiebel',40],['bruehe',320],['broetchen',40],['minze',3]], s:['Zwiebel andünsten, Erbsen und Kartoffel köcheln.','Pürieren.','Mit Croutons und Minze servieren.'] },
{ n:'Rindfleischsuppe mit Nudeln und Gemüse', m:'mittag', t:60, mp:1, ing:[['rindersteak',120],['nudeln',70],['moehren',70],['lauch',50],['bruehe',420],['petersilie',4]], s:['Rind in Brühe garen und zupfen.','Gemüse zugeben.','Nudeln mitkochen.'] },
{ n:'Cremige Möhren-Kokos-Suppe', m:'mittag', t:28, mp:1, ing:[['moehren',220],['kokosmilch',100],['zwiebel',40],['ingwer',6],['bruehe',320],['currypul',3]], s:['Möhre und Zwiebel andünsten.','Mit Brühe weich kochen und pürieren.','Kokosmilch und Curry unterrühren.'] },
{ n:'Käse-Lauch-Suppe mit Hackfleisch und Champignons', m:'abend', t:38, mp:1, ing:[['lauch',110],['hackrind',130],['schmelzkaese',60],['champignons',70],['zwiebel',40],['bruehe',350]], s:['Hack, Zwiebel und Champignons anbraten.','Lauch und Brühe zugeben.','Schmelzkäse einrühren.'] },
{ n:'Ungarische Bohnensuppe (Bableves)', m:'abend', t:45, mp:1, ing:[['weissebohnen',170],['mettwurst',60],['moehren',60],['paprikapulver',3],['zwiebel',40],['bruehe',320]], s:['Wurst und Zwiebel anbraten.','Bohnen, Möhre und Paprikapulver zugeben.','Weich köcheln.'] },
{ n:'Blumenkohl-Curry-Suppe mit Kichererbsen', m:'mittag', t:30, mp:1, ing:[['blumenkohl',180],['kichererbsen',90],['kokosmilch',90],['zwiebel',40],['currypul',4],['bruehe',300]], s:['Blumenkohl und Zwiebel anbraten.','Kichererbsen, Kokosmilch und Curry zugeben.','Köcheln und leicht pürieren.'] },
{ n:'Spinat-Cremesuppe mit Ei', m:'mittag', t:26, mp:1, ing:[['spinat',180],['kartoffeln',70],['zwiebel',40],['kochsahne',50],['bruehe',320],['ei',50]], s:['Spinat und Kartoffel köcheln.','Pürieren und mit Sahne verfeinern.','Mit pochiertem Ei servieren.'] },
{ n:'Gemüsesuppe mit Backerbsen', m:'mittag', t:30, mp:1, ing:[['moehren',70],['kartoffeln',80],['erbsen',50],['lauch',50],['bruehe',420],['backerbsen',20]], s:['Gemüse würfeln und in Brühe garen.','Abschmecken.','Mit Backerbsen servieren.'] },
{ n:'Rote-Bete-Suppe mit Schmand', m:'mittag', t:35, mp:1, ing:[['rote_beete',200],['kartoffeln',70],['zwiebel',40],['bruehe',320],['schmand',40],['dill',3]], s:['Rote Bete und Zwiebel andünsten.','Mit Brühe köcheln und pürieren.','Mit Schmand und Dill servieren.'] },
{ n:'Griechische Zitronen-Hühnersuppe (Avgolemono)', m:'mittag', t:40, mp:1, ing:[['haehnchen',120],['reis',70],['ei',50],['zitrone',15],['bruehe',420],['petersilie',4]], s:['Hähnchen in Brühe garen und zupfen, Reis mitkochen.','Ei mit Zitrone verquirlen und unterrühren.','Nicht mehr kochen, mit Petersilie servieren.'] },
{ n:'Zwiebelsuppe mit Käsecroutons', m:'abend', t:45, mp:1, ing:[['zwiebel',200],['bruehe',380],['baguette',60],['bergkaese',50],['butter',15],['weisswein',30]], s:['Zwiebeln goldbraun schmoren.','Mit Wein und Brühe köcheln.','Mit Käsecroutons überbacken.'] },
{ n:'Brokkoli-Kartoffel-Suppe mit Cheddar', m:'mittag', t:30, mp:1, ing:[['brokkoli',180],['kartoffeln',90],['zwiebel',40],['reibekaese',50],['bruehe',330],['kochsahne',40]], s:['Brokkoli und Kartoffel köcheln.','Pürieren.','Käse und Sahne einrühren.'] },
];
