// Deutsche Klassiker & Hausmannskost. Von Hand geschrieben.
module.exports = [
{ n:'Königsberger Klopse mit Kapern und Reis', m:'abend', t:45, mp:1, ing:[['hackrind',150],['semmelbroesel',25],['ei',40],['kochsahne',80],['kapern',15],['reis',160]], s:['Klopse formen und in Brühe garen.','Helle Kapernsauce zubereiten.','Mit Reis servieren.'] },
{ n:'Kohlrouladen mit Kartoffelpüree', m:'abend', t:80, mp:1, ing:[['weisskohl',150],['hackrind',140],['reis',60],['passata',100],['kartoffeln',180],['milch',60]], s:['Kohlblätter mit Hack-Reis-Masse füllen.','In Tomatensauce schmoren.','Mit Kartoffelpüree servieren.'] },
{ n:'Grünkohl mit Kasseler und Kartoffeln', m:'abend', t:55, mp:1, ing:[['grünkohl',150],['kasseler',120],['kartoffeln',180],['zwiebel',50],['bruehe',300],['senf',8]], s:['Zwiebel andünsten, Grünkohl schmoren.','Kasseler mitgaren.','Mit Kartoffeln servieren.'] },
{ n:'Rinderroulade mit Rotkohl und Klößen', m:'abend', t:90, mp:1, ing:[['rindersteak',170],['gewuerzgurke',30],['bacon',30],['rotkohl',150],['kloesse',150],['senf',10]], s:['Roulade füllen und anbraten.','In Soße schmoren.','Mit Rotkohl und Klößen servieren.'] },
{ n:'Sauerbraten mit Kartoffelklößen', m:'abend', t:100, mp:1, ing:[['rindersteak',170],['zwiebel',60],['essig',15],['rotkohl',120],['kloesse',150],['bruehe',200]], s:['Fleisch marinieren und schmoren.','Soße einkochen.','Mit Klößen und Rotkohl servieren.'] },
{ n:'Currywurst mit Pommes und Currysauce', m:'mittag', t:25, ing:[['bratwurst',150],['pommes',200],['ketchup',30],['currypul',3],['zwiebel',30]], s:['Wurst braten.','Currysauce aus Ketchup und Curry rühren.','Mit Pommes servieren.'] },
{ n:'Leberkäse mit Spiegelei und Kartoffelsalat', m:'mittag', t:30, ing:[['leberkaese',150],['ei',50],['kartoffeln',200],['naturjoghurt',60],['senf',8],['schnittlauch',4]], s:['Leberkäse braten.','Spiegelei zubereiten.','Mit Kartoffelsalat servieren.'] },
{ n:'Bratwurst mit Sauerkraut und Püree', m:'abend', t:30, mp:1, ing:[['bratwurst',150],['sauerkraut',150],['kartoffeln',200],['milch',60],['zwiebel',40],['senf',8]], s:['Bratwurst braten.','Sauerkraut mit Zwiebel schmoren.','Mit Kartoffelpüree servieren.'] },
{ n:'Maultaschen in Zwiebelschmelze', m:'mittag', t:20, mp:1, ing:[['maultaschen',220],['zwiebel',60],['butter',15],['bruehe',150],['schnittlauch',4]], s:['Maultaschen in Brühe erwärmen.','Zwiebeln in Butter rösten.','Darüber geben.'] },
{ n:'Schweinshaxe mit Sauerkraut und Kartoffeln', m:'abend', t:110, mp:1, ing:[['schweinebraten',200],['sauerkraut',150],['kartoffeln',180],['zwiebel',50],['bruehe',250]], s:['Haxe knusprig im Ofen garen.','Sauerkraut schmoren.','Mit Kartoffeln servieren.'] },
{ n:'Rahmschnitzel mit Spätzle', m:'abend', t:32, mp:1, ing:[['schweineschnitzel',160],['champignons',80],['kochsahne',100],['zwiebel',40],['spaetzle',200],['petersilie',4]], s:['Schnitzel braten.','Champignon-Rahmsauce köcheln.','Mit Spätzle servieren.'] },
{ n:'Schwäbische Linsen mit Spätzle und Speck', m:'abend', t:45, mp:1, ing:[['linsen',160],['spaetzle',180],['bacon',50],['moehren',50],['zwiebel',40],['essig',10]], s:['Speck und Zwiebel anbraten.','Linsen mit Möhre köcheln, mit Essig abschmecken.','Mit Spätzle servieren.'] },
{ n:'Reibekuchen mit Räucherlachs und Meerrettich', m:'mittag', t:30, ing:[['kartoffeln',260],['ei',50],['mehl',20],['raeucherlachs',60],['schmand',40],['meerrettich',8]], s:['Reibekuchen braten.','Schmand mit Meerrettich verrühren.','Mit Lachs belegen.'] },
{ n:'Senfeier mit Kartoffeln', m:'mittag', t:30, mp:1, ing:[['ei',150],['milch',150],['senf',15],['mehl',15],['kartoffeln',220],['schnittlauch',4]], s:['Eier hart kochen.','Senf-Mehlschwitze zubereiten.','Mit Kartoffeln servieren.'] },
{ n:'Kartoffel-Hackfleisch-Auflauf deftig', m:'abend', t:50, mp:1, ing:[['kartoffeln',250],['hackrind',140],['passata',120],['reibekaese',60],['zwiebel',40],['kochsahne',70]], s:['Hack mit Zwiebel und Passata anbraten.','Mit Kartoffelscheiben schichten.','Mit Sahne und Käse überbacken.'] },
{ n:'Bauernfrühstück mit Speck und Kartoffeln', m:'mittag', t:28, ing:[['kartoffeln',220],['ei',120],['bacon',40],['zwiebel',40],['gewuerzgurke',30],['schnittlauch',4]], s:['Kartoffeln und Speck anbraten.','Eier zugeben und stocken lassen.','Mit Gurke und Schnittlauch servieren.'] },
];
