// One-Pot-Gerichte. Von Hand geschrieben.
module.exports = [
{ n:'One-Pot-Pasta mit Tomate und Mozzarella', m:'mittag', t:25, mp:1, ing:[['penne',180],['passata',180],['cherrytomaten',80],['mozzarella',70],['knoblauch',6],['basilikum',4]], s:['Nudeln mit Passata und Wasser in einem Topf garen.','Tomaten mitkochen.','Mozzarella und Basilikum unterheben.'] },
{ n:'One-Pot-Reis mit Hähnchen, Erbsen und Safran', m:'abend', t:38, mp:1, ing:[['reis',170],['haehnchen',140],['erbsen',60],['paprika',70],['safran',1],['bruehe',350]], s:['Hähnchen anbraten.','Reis, Gemüse, Safran und Brühe zugeben.','Zugedeckt garen.'] },
{ n:'One-Pot-Nudeln mit Hackfleisch und Paprika', m:'abend', t:30, mp:1, ing:[['fusilli',180],['hackrind',140],['paprika',80],['passata',160],['zwiebel',40],['reibekaese',30]], s:['Hack und Zwiebel anbraten.','Nudeln, Paprika, Passata und Wasser zugeben.','Garen bis cremig, Käse unterheben.'] },
{ n:'One-Pot-Gnocchi mit Spinat und Sahne', m:'mittag', t:22, ing:[['gnocchi',240],['spinat',80],['kochsahne',100],['cherrytomaten',70],['knoblauch',6],['parmesan',20]], s:['Gnocchi mit Sahne und Wasser garen.','Spinat und Tomaten zugeben.','Mit Parmesan servieren.'] },
{ n:'One-Pot-Curry-Reis mit Kichererbsen', m:'abend', t:32, mp:1, ing:[['reis',160],['kichererbsen',120],['kokosmilch',110],['moehren',60],['currypul',4],['bruehe',250]], s:['Zwiebel und Curry anrösten.','Reis, Kichererbsen, Kokosmilch und Brühe zugeben.','Zugedeckt garen.'] },
{ n:'One-Pot-Spaghetti mit Garnelen', m:'abend', t:26, mp:1, ing:[['spaghetti',180],['garnelen',130],['passata',160],['knoblauch',8],['chili',4],['petersilie',5]], s:['Spaghetti mit Passata und Wasser garen.','Garnelen mitkochen.','Mit Knoblauch, Chili und Petersilie abschmecken.'] },
{ n:'One-Pot-Linsen-Reis (Mujadara)', m:'abend', t:40, mp:1, ing:[['reis',150],['linsen',120],['zwiebel',80],['kreuzkuemmel',3],['olivenoel',15],['bruehe',350]], s:['Zwiebeln goldbraun rösten.','Reis, Linsen und Brühe zugeben.','Zugedeckt garen.'] },
{ n:'One-Pot-Nudeln mit Lachs und Erbsen', m:'mittag', t:24, mp:1, ing:[['penne',180],['lachs',120],['erbsen',60],['kochsahne',90],['zitrone',8],['dill',3]], s:['Nudeln mit Sahne und Wasser garen.','Lachs und Erbsen mitkochen.','Mit Zitrone und Dill abschmecken.'] },
{ n:'One-Pot-Reis mit Chorizo und Paprika', m:'abend', t:32, mp:1, ing:[['reis',170],['chorizo',70],['paprika',80],['passata',100],['zwiebel',40],['bruehe',280]], s:['Chorizo und Zwiebel anbraten.','Reis, Paprika, Passata und Brühe zugeben.','Zugedeckt garen.'] },
{ n:'One-Pot-Tortellini mit Tomate und Spinat', m:'mittag', t:20, ing:[['tortellini',220],['passata',150],['spinat',70],['knoblauch',6],['kochsahne',60],['parmesan',20]], s:['Tortellini mit Passata und Wasser garen.','Spinat und Sahne zugeben.','Mit Parmesan servieren.'] },
{ n:'One-Pot-Couscous mit Gemüse und Kichererbsen', m:'mittag', t:25, mp:1, ing:[['couscous',160],['kichererbsen',100],['zucchini',70],['passata',110],['raselhanout',3],['bruehe',180]], s:['Gemüse andünsten.','Couscous, Kichererbsen und Brühe zugeben.','Quellen lassen.'] },
{ n:'One-Pot-Nudeln mit Brokkoli und Frischkäse', m:'mittag', t:24, ing:[['penne',180],['brokkoli',100],['frischkaese',60],['knoblauch',6],['bruehe',220],['parmesan',20]], s:['Nudeln mit Brühe und Wasser garen.','Brokkoli mitkochen.','Frischkäse und Parmesan unterrühren.'] },
{ n:'One-Pot-Reispfanne mit Thunfisch und Mais', m:'mittag', t:28, mp:1, ing:[['reis',170],['thunfisch',100],['mais',60],['paprika',60],['passata',100],['zwiebel',40]], s:['Zwiebel und Paprika anbraten.','Reis, Passata und Brühe zugeben.','Thunfisch und Mais unterheben.'] },
{ n:'One-Pot-Kartoffel-Wurst-Gulasch', m:'abend', t:35, mp:1, ing:[['kartoffeln',220],['mettwurst',80],['paprika',70],['passata',120],['zwiebel',50],['paprikapulver',3]], s:['Wurst und Zwiebel anbraten.','Kartoffeln, Paprika und Passata zugeben.','Weich schmoren.'] },
{ n:'One-Pot-Mac-and-Cheese mit Brokkoli', m:'abend', t:26, mp:1, ing:[['nudeln',180],['bergkaese',70],['milch',150],['brokkoli',90],['reibekaese',40],['muskat',1]], s:['Nudeln mit Milch und Wasser garen.','Brokkoli mitkochen.','Käse einrühren bis cremig.'] },
{ n:'One-Pot-Hähnchen-Reis mediterran', m:'abend', t:35, mp:1, ing:[['reis',170],['haehnchen',140],['cherrytomaten',80],['oliven',25],['zucchini',60],['bruehe',320]], s:['Hähnchen anbraten.','Reis, Gemüse, Oliven und Brühe zugeben.','Zugedeckt garen.'] },
];
