// Mediterrane Küche. Von Hand geschrieben.
module.exports = [
{ n:'Gambas al Ajillo mit Baguette', m:'abend', t:20, ing:[['garnelen',160],['knoblauch',12],['olivenoel',22],['chili',4],['baguette',90],['petersilie',5]], s:['Knoblauch und Chili in Öl erhitzen.','Garnelen kurz braten.','Mit Baguette servieren.'] },
{ n:'Spanische Tortilla mit Kartoffeln', m:'mittag', t:35, mp:1, ing:[['kartoffeln',220],['ei',150],['zwiebel',60],['olivenoel',18],['petersilie',4]], s:['Kartoffeln und Zwiebel in Öl garen.','Mit Ei vermengen.','Als Tortilla stocken lassen.'] },
{ n:'Pasta alla Norma mit Aubergine', m:'mittag', t:30, mp:1, ing:[['penne',180],['aubergine',120],['passata',160],['ricotta',40],['basilikum',5],['olivenoel',12]], s:['Aubergine anbraten.','Mit Passata köcheln.','Mit Penne, Ricotta und Basilikum servieren.'] },
{ n:'Griechischer Gyros-Auflauf mit Feta', m:'abend', t:45, mp:1, ing:[['gyrosfleisch',150],['kartoffeln',200],['paprika',70],['feta',60],['naturjoghurt',60],['zwiebel',40]], s:['Gyros und Gemüse anbraten.','Mit Kartoffeln in eine Form geben.','Mit Feta überbacken.'] },
{ n:'Caponata siciliana mit Brot', m:'mittag', t:35, mp:1, ing:[['aubergine',160],['sellerie',50],['passata',120],['oliven',30],['kapern',12],['baguette',80]], s:['Aubergine und Sellerie anbraten.','Mit Passata, Oliven und Kapern schmoren.','Mit Brot servieren.'] },
{ n:'Hähnchen-Souvlaki mit Zaziki und Reis', m:'abend', t:30, mp:1, ing:[['haehnchen',160],['naturjoghurt',70],['gurke',50],['knoblauch',5],['reis',160],['zitrone',8]], s:['Hähnchen marinieren und grillen.','Zaziki rühren.','Mit Reis servieren.'] },
{ n:'Pisto mit Spiegelei (spanisches Ratatouille)', m:'mittag', t:30, ing:[['zucchini',90],['paprika',90],['tomaten',100],['zwiebel',50],['ei',60],['olivenoel',14]], s:['Gemüse schmoren.','Zu Pisto einkochen.','Mit Spiegelei servieren.'] },
{ n:'Orzo-Pfanne mit Garnelen und Feta', m:'abend', t:28, mp:1, ing:[['nudeln',170],['garnelen',130],['passata',130],['feta',50],['zwiebel',40],['knoblauch',6]], s:['Zwiebel und Knoblauch andünsten.','Orzo mit Passata garen.','Garnelen und Feta zugeben.'] },
{ n:'Ligurische Nudeln mit Pesto und Bohnen', m:'mittag', t:24, mp:1, ing:[['nudeln',180],['pesto',30],['gruenebohnen',80],['kartoffeln',100],['parmesan',20],['pinienkerne',12]], s:['Nudeln, Bohnen und Kartoffel zusammen garen.','Mit Pesto mischen.','Mit Parmesan und Pinienkernen servieren.'] },
{ n:'Kalamari vom Grill mit Zitrone', m:'abend', t:22, ing:[['tintenfisch',180],['zitrone',12],['knoblauch',6],['olivenoel',15],['petersilie',5],['baguette',80]], s:['Tintenfisch marinieren.','Kurz grillen.','Mit Zitrone und Brot servieren.'] },
{ n:'Zucchini-Parmigiana überbacken', m:'abend', t:50, mp:1, ing:[['zucchini',220],['passata',180],['mozzarella',90],['parmesan',30],['basilikum',5],['olivenoel',12]], s:['Zucchinischeiben anbraten.','Mit Passata und Käse schichten.','Im Ofen überbacken.'] },
{ n:'Spanischer Kichererbsen-Spinat-Topf', m:'abend', t:32, mp:1, ing:[['kichererbsen',170],['spinat',80],['passata',110],['chorizo',50],['knoblauch',6],['baguette',70]], s:['Chorizo und Knoblauch anbraten.','Kichererbsen, Spinat und Passata köcheln.','Mit Brot servieren.'] },
{ n:'Zucchini-Puffer mit Zaziki griechisch', m:'mittag', t:28, mp:1, ing:[['zucchini',180],['ei',50],['mehl',25],['feta',40],['naturjoghurt',60],['minze',3]], s:['Zucchini raspeln und mit Ei, Mehl und Feta mischen.','Puffer braten.','Mit Zaziki servieren.'] },
{ n:'Pasta mit Sardinen und Fenchel', m:'mittag', t:26, mp:1, ing:[['spaghetti',180],['sardinen',90],['fenchel',80],['rosinen2',15],['pinienkerne',12],['olivenoel',12]], s:['Fenchel andünsten.','Sardinen, Rosinen und Pinienkerne zugeben.','Mit Spaghetti mischen.'] },
{ n:'Lammkoteletts mit Rosmarinkartoffeln', m:'abend', t:35, mp:1, ing:[['lammfilet',170],['kartoffeln',220],['rosmarin',3],['knoblauch',8],['olivenoel',14],['zitrone',8]], s:['Lamm mit Rosmarin marinieren.','Kartoffeln im Ofen rösten.','Lamm braten und servieren.'] },
{ n:'Focaccia-Sandwich mit Mozzarella und Pesto', m:'mittag', t:14, ing:[['ciabatta',110],['mozzarella',70],['tomaten',60],['pesto',20],['rucola',20],['olivenoel',8]], s:['Focaccia aufschneiden und mit Pesto bestreichen.','Mit Mozzarella und Tomate belegen.','Mit Rucola servieren.'] },
];
