// Indische Küche, Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Butter Chicken mit Reis', m:'abend', t:38, mp:1, ing:[['haehnchen',160],['passata',140],['kochsahne',80],['garam_masala',5],['ingwer',6],['reis',160]], s:['Hähnchen mit Gewürzen anbraten.','Tomaten-Sahne-Sauce köcheln.','Mit Reis servieren.'] },
{ n:'Chicken Tikka Masala mit Naan', m:'abend', t:40, mp:1, ing:[['haehnchen',160],['naturjoghurt',60],['passata',140],['garam_masala',5],['zwiebel',50],['naanbrot',90]], s:['Hähnchen in Joghurt-Gewürz marinieren und braten.','Masala-Sauce köcheln.','Mit Naan servieren.'] },
{ n:'Dal Makhani mit Reis', m:'abend', t:45, mp:1, ing:[['linsen',150],['kidneybohnen',60],['kochsahne',70],['passata',100],['garam_masala',4],['reis',160]], s:['Linsen und Bohnen weich kochen.','Mit Tomaten, Sahne und Gewürzen köcheln.','Mit Reis servieren.'] },
{ n:'Saag Aloo mit Naan', m:'abend', t:35, mp:1, ing:[['spinat',160],['kartoffeln',180],['zwiebel',40],['kurkuma',3],['garam_masala',3],['naanbrot',80]], s:['Kartoffel mit Gewürzen anbraten.','Spinat zugeben und schmoren.','Mit Naan servieren.'] },
{ n:'Hähnchen-Korma mild mit Reis', m:'abend', t:38, mp:1, ing:[['haehnchen',160],['kokosmilch',110],['mandeln',15],['zwiebel',50],['garam_masala',4],['reis',160]], s:['Hähnchen anbraten.','Mit Kokosmilch, Mandeln und Gewürzen köcheln.','Mit Reis servieren.'] },
{ n:'Kichererbsen-Kartoffel-Curry (Chana Aloo)', m:'abend', t:35, mp:1, ing:[['kichererbsen',150],['kartoffeln',150],['passata',110],['zwiebel',40],['garam_masala',4],['reis',150]], s:['Zwiebel und Gewürze anrösten.','Kichererbsen, Kartoffel und Passata köcheln.','Mit Reis servieren.'] },
{ n:'Gemüse-Korma mit Cashews', m:'abend', t:35, mp:1, ing:[['blumenkohl',120],['erbsen',60],['kokosmilch',110],['cashews',20],['garam_masala',4],['reis',160]], s:['Gemüse anbraten.','Mit Kokosmilch, Cashews und Gewürzen köcheln.','Mit Reis servieren.'] },
{ n:'Tandoori-Hähnchenspieße mit Minzjoghurt', m:'abend', t:35, mp:1, ing:[['haehnchen',160],['naturjoghurt',80],['tandoori',8],['minze',4],['reis',160],['gurke',50]], s:['Hähnchen marinieren und grillen.','Minzjoghurt rühren.','Mit Reis servieren.'] },
{ n:'Linsen-Spinat-Dal mit Reis', m:'abend', t:32, mp:1, ing:[['rotelinsen',160],['spinat',80],['tomaten',70],['zwiebel',40],['kurkuma',3],['reis',160]], s:['Zwiebel und Gewürze anrösten.','Linsen, Spinat und Tomaten köcheln.','Mit Reis servieren.'] },
{ n:'Paneer-Erbsen-Curry (Mattar Paneer)', m:'abend', t:35, mp:1, ing:[['paneer',130],['erbsen',80],['passata',130],['zwiebel',40],['garam_masala',4],['reis',160]], s:['Paneer anbraten.','Erbsen und Tomatensauce köcheln.','Mit Reis servieren.'] },
{ n:'Bombay-Kartoffeln mit Joghurt', m:'mittag', t:30, mp:1, ing:[['kartoffeln',220],['zwiebel',40],['kurkuma',3],['garam_masala',3],['naturjoghurt',60],['koriandergruen',4]], s:['Kartoffeln mit Gewürzen anbraten.','Knusprig schmoren.','Mit Joghurt servieren.'] },
{ n:'Fisch-Curry südindisch mit Reis', m:'abend', t:32, mp:1, ing:[['seelachs',160],['kokosmilch',120],['passata',80],['currypul',4],['zwiebel',40],['reis',160]], s:['Fisch würfeln.','In Kokos-Curry-Sauce garen.','Mit Reis servieren.'] },
{ n:'Hähnchen-Biryani mit Joghurt und Cashews', m:'abend', t:45, mp:1, ing:[['basmatireis',170],['haehnchen',140],['naturjoghurt',60],['zwiebel',50],['cashews',20],['garam_masala',5]], s:['Hähnchen mit Gewürzen und Joghurt anbraten.','Mit Reis schichten und dämpfen.','Mit Cashews servieren.'] },
{ n:'Rotes Linsen-Kokos-Curry mit Naan', m:'abend', t:32, mp:1, ing:[['rotelinsen',160],['kokosmilch',110],['passata',90],['currypul',4],['zwiebel',40],['naanbrot',90]], s:['Zwiebel und Curry anrösten.','Linsen, Kokosmilch und Passata köcheln.','Mit Naan servieren.'] },
{ n:'Hähnchen-Jalfrezi mit Paprika', m:'abend', t:35, mp:1, ing:[['haehnchen',160],['paprika',90],['passata',120],['zwiebel',50],['garam_masala',4],['reis',160]], s:['Hähnchen und Paprika scharf anbraten.','Mit Tomatensauce und Gewürzen köcheln.','Mit Reis servieren.'] },
{ n:'Aloo Matar (Kartoffel-Erbsen-Curry)', m:'abend', t:32, mp:1, ing:[['kartoffeln',180],['erbsen',90],['passata',110],['zwiebel',40],['garam_masala',4],['reis',150]], s:['Zwiebel und Gewürze anrösten.','Kartoffel, Erbsen und Passata köcheln.','Mit Reis servieren.'] },
];
