// Mexikanische Küche, Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Chicken Fajitas mit Paprika und Zwiebel', m:'abend', t:28, mp:1, ing:[['haehnchen',150],['paprika',100],['zwiebel',60],['fajitagewuerz',6],['wrap',100],['guacamole',40]], s:['Hähnchen und Gemüse scharf anbraten.','Mit Fajitagewürz würzen.','In Wraps mit Guacamole füllen.'] },
{ n:'Rindfleisch-Tacos mit Salsa', m:'abend', t:30, mp:1, ing:[['tortilla_mais',110],['hackrind',140],['tomaten',60],['zwiebel',40],['reibekaese',40],['koriandergruen',4]], s:['Hack würzig anbraten.','Salsa aus Tomate und Zwiebel mischen.','Tacos füllen.'] },
{ n:'Enchiladas mit Hähnchen und Käse', m:'abend', t:45, mp:1, ing:[['wrap',120],['haehnchen',140],['passata',150],['reibekaese',70],['zwiebel',40],['mais',50]], s:['Hähnchen und Mais in Wraps füllen.','Mit Passata übergießen.','Mit Käse überbacken.'] },
{ n:'Burrito mit Bohnen, Reis und Käse', m:'abend', t:28, mp:1, ing:[['wrap',120],['kidneybohnen',90],['reis',120],['reibekaese',50],['mais',50],['guacamole',40]], s:['Reis und Bohnen würzen.','In Wrap mit Käse und Mais füllen.','Fest einrollen.'] },
{ n:'Quesadilla mit Pulled Beef und Jalapeño', m:'mittag', t:26, mp:1, ing:[['wrap',110],['rindersteak',120],['reibekaese',60],['jalapeno',15],['zwiebel',30],['schmand',30]], s:['Rind garen und zerzupfen.','Wrap mit Käse, Fleisch und Jalapeño belegen.','Zusammenklappen und braten.'] },
{ n:'Chili con Carne mit Reis', m:'abend', t:40, mp:1, ing:[['hackrind',150],['kidneybohnen',120],['mais',60],['passata',160],['paprika',60],['reis',150]], s:['Hack mit Paprika anbraten.','Bohnen, Mais und Passata köcheln.','Mit Reis servieren.'] },
{ n:'Nachos überbacken mit Hackfleisch', m:'abend', t:25, ing:[['tortillachips',90],['hackrind',120],['reibekaese',70],['kidneybohnen',60],['jalapeno',15],['schmand',40]], s:['Hack würzig anbraten.','Chips mit Hack, Bohnen und Käse belegen.','Überbacken und mit Schmand servieren.'] },
{ n:'Taco-Salat-Bowl mit Rindfleisch', m:'mittag', t:26, mp:1, ing:[['hackrind',140],['salat',80],['kidneybohnen',70],['mais',50],['reibekaese',40],['guacamole',40]], s:['Hack würzen und anbraten.','Mit Salat, Bohnen und Mais anrichten.','Mit Käse und Guacamole toppen.'] },
{ n:'Vegetarische Bohnen-Tacos mit Avocado', m:'mittag', t:24, mp:1, ing:[['tortilla_mais',110],['kidneybohnen',110],['mais',60],['avocado',60],['tomaten',50],['limette',6]], s:['Bohnen und Mais würzen.','Tacos füllen.','Mit Avocado und Limette servieren.'] },
{ n:'Huevos Rancheros mit Avocado und Salsa', m:'fruh', t:25, ing:[['ei',120],['tortilla_mais',80],['avocado',60],['passata',100],['zwiebel',30],['jalapeno',10]], s:['Salsa aus Passata, Zwiebel und Jalapeño erhitzen.','Eier braten.','Auf Tortilla mit Avocado und Salsa servieren.'] },
{ n:'Garnelen-Tacos mit Mango-Salsa', m:'abend', t:26, mp:1, ing:[['garnelen',140],['tortilla_mais',110],['mango',60],['avocado',50],['limette',8],['koriandergruen',4]], s:['Garnelen würzen und braten.','Mango-Salsa mit Avocado mischen.','Tacos füllen.'] },
{ n:'Mexikanische Reispfanne mit Mais und Bohnen', m:'mittag', t:28, mp:1, ing:[['reis',170],['kidneybohnen',100],['mais',60],['paprika',60],['passata',110],['reibekaese',40]], s:['Paprika anbraten.','Reis, Bohnen, Mais und Passata köcheln.','Mit Käse servieren.'] },
{ n:'Chilaquiles mit Ei und Salsa', m:'fruh', t:22, ing:[['tortillachips',80],['ei',100],['passata',110],['reibekaese',50],['zwiebel',30],['koriandergruen',4]], s:['Chips in Salsa schwenken.','Mit Ei und Käse überbacken.','Mit Koriander servieren.'] },
{ n:'Süßkartoffel-Bohnen-Burrito', m:'abend', t:32, mp:1, ing:[['wrap',120],['suesskartoffel',140],['kidneybohnen',90],['mais',50],['reibekaese',50],['guacamole',40]], s:['Süßkartoffel rösten.','Mit Bohnen, Mais und Käse in Wrap füllen.','Mit Guacamole einrollen.'] },
{ n:'Carne-Asada-Bowl mit Reis und Limette', m:'abend', t:30, mp:1, ing:[['rindersteak',150],['reis',150],['kidneybohnen',70],['mais',50],['limette',8],['koriandergruen',4]], s:['Rind marinieren und braten.','Reis und Bohnen erwärmen.','Mit Mais und Limette anrichten.'] },
{ n:'Guacamole mit Nacho-Dip-Teller', m:'snack', t:15, ing:[['avocado',120],['tomaten',50],['zwiebel',30],['limette',8],['tortillachips',80],['koriandergruen',4]], s:['Avocado mit Tomate, Zwiebel und Limette zerdrücken.','Abschmecken.','Mit Nachos servieren.'] },
];
