// Nudelgerichte, Teil 7. Von Hand geschrieben.
module.exports = [
{ n:'Lasagne Bolognese klassisch', m:'abend', t:65, mp:1, ing:[['lasagneplatten',120],['hackrind',150],['passata',180],['bechamel',120],['parmesan',30],['zwiebel',40]], s:['Bolognese köcheln.','Mit Béchamel und Platten schichten.','Mit Parmesan überbacken.'] },
{ n:'Spaghetti mit Hähnchen und Champignonrahm', m:'abend', t:28, mp:1, ing:[['spaghetti',180],['haehnchen',130],['champignons',90],['kochsahne',90],['zwiebel',40],['parmesan',20]], s:['Hähnchen und Pilze anbraten.','Mit Sahne köcheln.','Mit Spaghetti und Parmesan mischen.'] },
{ n:'Penne mit Brokkoli und Gorgonzola', m:'abend', t:24, ing:[['penne',180],['brokkoli',100],['bergkaese',50],['kochsahne',90],['walnuesse',15],['parmesan',15]], s:['Brokkoli garen.','Käse in Sahne schmelzen.','Mit Penne und Walnüssen mischen.'] },
{ n:'Nudeln mit Tomaten-Thunfisch-Sauce', m:'mittag', t:22, mp:1, ing:[['fusilli',180],['thunfisch',100],['passata',150],['knoblauch',6],['kapern',12],['petersilie',4]], s:['Knoblauch anbraten.','Passata, Thunfisch und Kapern köcheln.','Mit Nudeln mischen.'] },
{ n:'Spaghetti Carbonara mit Erbsen', m:'mittag', t:22, ing:[['spaghetti',180],['pancetta',50],['ei',50],['erbsen',50],['pecorino',30],['pfeffer',3]], s:['Pancetta braten.','Ei mit Pecorino verquirlen.','Mit Spaghetti, Erbsen und Pfeffer mischen.'] },
{ n:'Tagliatelle mit Lachs, Erbsen und Zitrone', m:'mittag', t:24, mp:1, ing:[['tagliatelle',180],['lachs',120],['erbsen',60],['frischkaese',50],['zitrone',10],['dill',3]], s:['Lachs braten.','Erbsen und Frischkäse zugeben.','Mit Tagliatelle und Zitrone mischen.'] },
{ n:'Penne mit Paprika-Feta-Sauce aus dem Ofen', m:'mittag', t:32, mp:1, ing:[['penne',180],['paprika',110],['feta',90],['cherrytomaten',80],['knoblauch',6],['olivenoel',12]], s:['Paprika, Tomaten und Feta mit Öl im Ofen backen.','Zu cremiger Sauce zerdrücken.','Mit Penne mischen.'] },
{ n:'Spaghetti mit Zucchini und Garnelen', m:'abend', t:24, mp:1, ing:[['spaghetti',180],['garnelen',120],['zucchini',90],['knoblauch',8],['olivenoel',14],['zitrone',8]], s:['Garnelen und Zucchini anbraten.','Mit Knoblauch und Öl schwenken.','Mit Spaghetti und Zitrone mischen.'] },
{ n:'Nudelauflauf mit Blumenkohl und Hähnchen', m:'abend', t:48, mp:1, ing:[['penne',180],['blumenkohl',110],['haehnchen',120],['kochsahne',110],['reibekaese',60],['ei',50]], s:['Nudeln und Blumenkohl garen.','Mit Hähnchen, Sahne und Ei mischen.','Mit Käse überbacken.'] },
{ n:'Spaghetti mit Rucola-Pesto und Tomaten', m:'mittag', t:20, ing:[['spaghetti',180],['rucola',40],['parmesan',25],['pinienkerne',15],['cherrytomaten',70],['olivenoel',15]], s:['Rucola-Pesto mixen.','Mit heißen Spaghetti mischen.','Mit Tomaten servieren.'] },
{ n:'Cremige Pilznudeln mit Trüffelöl', m:'abend', t:26, ing:[['tagliatelle',180],['champignons',120],['kochsahne',100],['zwiebel',40],['parmesan',25],['olivenoel',6]], s:['Pilze und Zwiebel anbraten.','Mit Sahne köcheln.','Mit Nudeln, Parmesan und etwas Öl servieren.'] },
{ n:'Spaghetti mit Tomaten und Burrata', m:'mittag', t:22, ing:[['spaghetti',180],['passata',150],['mozzarella',80],['basilikum',5],['knoblauch',6],['olivenoel',12]], s:['Tomatensauce köcheln.','Mit Spaghetti mischen.','Mit Burrata und Basilikum toppen.'] },
{ n:'Nudeln mit Hackfleisch und Erbsen', m:'abend', t:28, mp:1, ing:[['fusilli',180],['hackrind',130],['erbsen',60],['passata',140],['zwiebel',40],['parmesan',20]], s:['Hack und Zwiebel anbraten.','Erbsen und Passata zugeben.','Mit Nudeln und Parmesan mischen.'] },
{ n:'Spaghetti mit Sardellen, Tomate und Kapern', m:'mittag', t:22, mp:1, ing:[['spaghetti',180],['sardinen',60],['passata',140],['kapern',12],['knoblauch',8],['petersilie',5]], s:['Knoblauch in Öl anbraten.','Sardellen, Passata und Kapern köcheln.','Mit Spaghetti mischen.'] },
{ n:'Käse-Sahne-Tortellini mit Erbsen', m:'mittag', t:20, ing:[['tortellini',220],['kochsahne',100],['erbsen',50],['parmesan',30],['zwiebel',30],['muskat',1]], s:['Tortellini kochen.','Sahne-Käse-Sauce köcheln.','Mit Erbsen servieren.'] },
{ n:'Gebackene Feta-Nudeln mit Cherrytomaten', m:'abend', t:35, mp:1, ing:[['penne',180],['feta',120],['cherrytomaten',150],['knoblauch',8],['olivenoel',15],['basilikum',4]], s:['Feta mit Tomaten und Öl backen.','Nudeln kochen.','Zu cremiger Sauce vermengen.'] },
];
