// Fischgerichte, Teil 4. Von Hand geschrieben.
module.exports = [
{ n:'Lachs-Teriyaki mit Sesam-Brokkoli', m:'abend', t:26, mp:1, ing:[['lachs',160],['teriyakisauce',22],['brokkoli',110],['reis',160],['sesam',6],['fruehlingszwiebel',15]], s:['Lachs braten und glasieren.','Brokkoli dämpfen.','Mit Reis und Sesam servieren.'] },
{ n:'Kabeljau in Senfsauce mit Kartoffeln', m:'abend', t:30, mp:1, ing:[['kabeljau',170],['senf',12],['kochsahne',90],['kartoffeln',200],['dill',3],['zwiebel',30]], s:['Kabeljau braten.','Senf-Sahne-Sauce köcheln.','Mit Kartoffeln servieren.'] },
{ n:'Garnelen-Curry mit Kokos und Reis', m:'abend', t:28, mp:1, ing:[['garnelen',150],['kokosmilch',120],['paprika',60],['currypul',4],['reis',160],['koriandergruen',4]], s:['Garnelen in Currypaste anbraten.','Kokosmilch und Paprika zugeben.','Mit Reis servieren.'] },
{ n:'Forelle aus dem Ofen mit Zitrone', m:'abend', t:30, ing:[['forelle',190],['zitrone',12],['knoblauch',6],['kartoffeln',200],['olivenoel',12],['petersilie',4]], s:['Forelle mit Zitrone füllen.','Im Ofen garen.','Mit Kartoffeln servieren.'] },
{ n:'Fischstäbchen selbstgemacht mit Kartoffelpüree', m:'abend', t:35, mp:1, ing:[['seelachs',170],['semmelbroesel',40],['ei',50],['kartoffeln',200],['erbsen',70],['milch',60]], s:['Fisch in Stäbchen schneiden und panieren.','Braten.','Mit Püree und Erbsen servieren.'] },
{ n:'Lachs-Nudel-Auflauf mit Spinat', m:'abend', t:45, mp:1, ing:[['penne',180],['lachs',140],['spinat',90],['kochsahne',110],['reibekaese',50],['zwiebel',30]], s:['Nudeln kochen.','Mit Lachs, Spinat und Sahne mischen.','Mit Käse überbacken.'] },
{ n:'Thunfisch-Steak mit Sojaglasur', m:'abend', t:22, ing:[['thunfisch',170],['sojasauce',14],['honig',8],['reis',160],['pak_choi',80],['sesam',5]], s:['Thunfisch kurz anbraten.','Mit Sojaglasur bestreichen.','Mit Reis und Pak Choi servieren.'] },
{ n:'Scholle Finkenwerder Art mit Krabben', m:'abend', t:34, ing:[['scholle',190],['bacon',30],['garnelen',50],['kartoffeln',200],['butter',12],['petersilie',4]], s:['Scholle mit Speck braten.','Krabben in Butter schwenken.','Mit Bratkartoffeln servieren.'] },
{ n:'Garnelen-Spaghetti in Weißweinsauce', m:'abend', t:26, mp:1, ing:[['spaghetti',180],['garnelen',130],['weisswein',40],['knoblauch',8],['kochsahne',60],['petersilie',5]], s:['Garnelen und Knoblauch anbraten.','Mit Wein und Sahne ablöschen.','Mit Spaghetti mischen.'] },
{ n:'Zander mit Speckbohnen und Kartoffeln', m:'abend', t:32, mp:1, ing:[['zander',170],['gruenebohnen',90],['bacon',30],['kartoffeln',200],['butter',12],['zitrone',8]], s:['Zander braten.','Bohnen mit Speck schmoren.','Mit Kartoffeln servieren.'] },
{ n:'Lachsfilet mit Honig-Senf-Kruste', m:'abend', t:28, mp:1, ing:[['lachs',170],['honig',10],['senf',12],['semmelbroesel',20],['brokkoli',100],['kartoffeln',180]], s:['Lachs mit Honig-Senf-Kruste bestreichen.','Im Ofen backen.','Mit Brokkoli und Kartoffeln servieren.'] },
{ n:'Fischpfanne mediterran mit Oliven', m:'abend', t:30, mp:1, ing:[['kabeljau',170],['cherrytomaten',100],['oliven',30],['zucchini',70],['knoblauch',6],['reis',150]], s:['Fisch würfeln und anbraten.','Mit Tomaten, Oliven und Zucchini schmoren.','Mit Reis servieren.'] },
{ n:'Garnelen-Zoodles in Knoblauchbutter', m:'abend', t:22, ing:[['garnelen',150],['zucchini',180],['knoblauch',10],['butter',15],['chili',4],['petersilie',5]], s:['Zucchini in Streifen hobeln.','Garnelen in Knoblauchbutter braten.','Mit Zoodles schwenken.'] },
{ n:'Seelachs in Tomaten-Kapern-Sauce', m:'abend', t:28, mp:1, ing:[['seelachs',170],['passata',150],['kapern',12],['oliven',25],['knoblauch',6],['reis',150]], s:['Seelachs anbraten.','Tomatensauce mit Kapern und Oliven köcheln.','Mit Reis servieren.'] },
{ n:'Räucherlachs-Pasta mit Zitrone', m:'mittag', t:22, ing:[['tagliatelle',180],['raeucherlachs',80],['kochsahne',90],['zitrone',10],['dill',3],['zwiebel',30]], s:['Sahnesauce köcheln.','Lachs und Zitrone unterheben.','Mit Tagliatelle mischen.'] },
{ n:'Ofen-Lachs mit Spargel und Kartoffeln', m:'abend', t:35, mp:1, ing:[['lachs',160],['spargel',120],['kartoffeln',180],['zitrone',10],['olivenoel',12],['dill',3]], s:['Lachs mit Spargel und Kartoffeln in eine Form geben.','Mit Öl und Zitrone beträufeln.','Im Ofen garen.'] },
];
