// Aufläufe & Gratins, Teil 3. Von Hand geschrieben.
module.exports = [
{ n:'Hähnchen-Reis-Auflauf mit Brokkoli und Käse', m:'abend', t:48, mp:1, ing:[['haehnchen',150],['reis',150],['brokkoli',120],['kochsahne',100],['reibekaese',60],['zwiebel',40]], s:['Hähnchen und Brokkoli anbraten.','Mit Reis und Sahne in eine Form geben.','Mit Käse überbacken.'] },
{ n:'Kartoffel-Zucchini-Gratin mit Feta', m:'abend', t:55, mp:1, ing:[['kartoffeln',240],['zucchini',100],['feta',70],['kochsahne',110],['knoblauch',6],['muskat',1]], s:['Kartoffel und Zucchini schichten.','Mit Sahne übergießen.','Mit Feta überbacken.'] },
{ n:'Gnocchi-Auflauf mit Spinat und Gorgonzola', m:'abend', t:35, mp:1, ing:[['gnocchi',240],['spinat',90],['bergkaese',50],['kochsahne',100],['parmesan',25],['zwiebel',30]], s:['Spinat andünsten.','Gnocchi mit Käsesauce mischen.','Im Ofen überbacken.'] },
{ n:'Hackfleisch-Kartoffel-Auflauf mit Mais', m:'abend', t:50, mp:1, ing:[['hackrind',150],['kartoffeln',240],['mais',60],['passata',120],['reibekaese',60],['zwiebel',40]], s:['Hack mit Zwiebel und Passata anbraten.','Mit Kartoffelscheiben und Mais schichten.','Mit Käse überbacken.'] },
{ n:'Brokkoli-Blumenkohl-Gratin mit Mandeln', m:'abend', t:45, mp:1, ing:[['blumenkohl',150],['brokkoli',120],['kochsahne',120],['reibekaese',70],['mandeln',15],['muskat',1]], s:['Blumenkohl und Brokkoli vorgaren.','In eine Form geben, mit Sahne übergießen.','Mit Käse und Mandeln überbacken.'] },
{ n:'Süßkartoffel-Hackfleisch-Auflauf', m:'abend', t:50, mp:1, ing:[['suesskartoffel',240],['hackrind',140],['passata',130],['reibekaese',60],['zwiebel',40],['mais',50]], s:['Hack mit Zwiebel und Passata anbraten.','Mit Süßkartoffelscheiben schichten.','Mit Käse überbacken.'] },
{ n:'Nudel-Auberginen-Auflauf mit Mozzarella', m:'abend', t:48, mp:1, ing:[['penne',180],['aubergine',110],['passata',160],['mozzarella',80],['ricotta',60],['basilikum',4]], s:['Aubergine anbraten.','Mit Nudeln, Passata und Ricotta mischen.','Mit Mozzarella überbacken.'] },
{ n:'Lachs-Kartoffel-Gratin mit Dill', m:'abend', t:50, mp:1, ing:[['lachs',150],['kartoffeln',220],['kochsahne',120],['reibekaese',50],['dill',4],['zwiebel',30]], s:['Kartoffelscheiben vorgaren.','Mit Lachs schichten.','Mit Sahne, Dill und Käse überbacken.'] },
{ n:'Tortellini-Auflauf mit Brokkoli', m:'abend', t:40, mp:1, ing:[['tortellini',200],['brokkoli',100],['kochsahne',110],['reibekaese',60],['kochschinken',50],['muskat',1]], s:['Tortellini und Brokkoli vorgaren.','Mit Schinken und Sahne mischen.','Mit Käse überbacken.'] },
{ n:'Moussaka mit Hackfleisch und Béchamel', m:'abend', t:65, mp:1, ing:[['aubergine',180],['hackrind',150],['kartoffeln',150],['passata',140],['bechamel',120],['reibekaese',50]], s:['Aubergine und Kartoffel anbraten.','Mit Hack-Tomatensauce schichten.','Mit Béchamel und Käse überbacken.'] },
{ n:'Reis-Auflauf mit Thunfisch und Erbsen', m:'abend', t:42, mp:1, ing:[['reis',160],['thunfisch',100],['erbsen',60],['kochsahne',100],['reibekaese',60],['zwiebel',30]], s:['Reis garen.','Mit Thunfisch, Erbsen und Sahne mischen.','Mit Käse überbacken.'] },
{ n:'Kartoffel-Lauch-Käse-Auflauf', m:'abend', t:50, mp:1, ing:[['kartoffeln',250],['lauch',100],['kochsahne',120],['reibekaese',70],['kochschinken',50],['muskat',1]], s:['Lauch andünsten.','Mit Kartoffelscheiben und Schinken schichten.','Mit Sahne und Käse überbacken.'] },
{ n:'Spinat-Ricotta-Nudelauflauf', m:'abend', t:45, mp:1, ing:[['penne',180],['spinat',100],['ricotta',100],['passata',140],['parmesan',30],['knoblauch',6]], s:['Spinat mit Ricotta mischen.','Mit Nudeln und Passata schichten.','Mit Parmesan überbacken.'] },
{ n:'Hähnchen-Gemüse-Gratin mediterran', m:'abend', t:50, mp:1, ing:[['haehnchen',150],['zucchini',90],['paprika',80],['kartoffeln',180],['kochsahne',100],['reibekaese',60]], s:['Hähnchen und Gemüse anbraten.','Mit Kartoffeln in eine Form geben.','Mit Sahne und Käse überbacken.'] },
{ n:'Brokkoli-Nudel-Auflauf mit Hähnchen', m:'abend', t:45, mp:1, ing:[['penne',180],['haehnchen',140],['brokkoli',110],['kochsahne',110],['reibekaese',60],['zwiebel',30]], s:['Hähnchen und Brokkoli anbraten.','Mit Nudeln und Sahne mischen.','Mit Käse überbacken.'] },
{ n:'Kürbis-Süßkartoffel-Gratin mit Ziegenkäse', m:'abend', t:55, mp:1, ing:[['kuerbis',150],['suesskartoffel',180],['kochsahne',120],['ziegenkaese',60],['thymian',2],['knoblauch',6]], s:['Kürbis und Süßkartoffel schichten.','Mit Sahne und Thymian übergießen.','Mit Ziegenkäse überbacken.'] },
];
