// Reis- und Bowl-Gerichte, Teil 4. Von Hand geschrieben.
module.exports = [
{ n:'Poke-Bowl mit Lachs, Edamame und Mango', m:'mittag', t:22, ing:[['lachs',120],['reis',160],['edamame',60],['mango',60],['sojasauce',12],['sesam',5]], s:['Lachs würfeln und marinieren.','Reis in eine Schale geben.','Mit Edamame, Mango und Sesam anrichten.'] },
{ n:'Protein-Bowl mit Hähnchen und Süßkartoffel', m:'mittag', t:30, mp:1, ing:[['haehnchen',140],['suesskartoffel',150],['quinoa',140],['brokkoli',80],['avocado',50],['limette',6]], s:['Hähnchen und Süßkartoffel garen.','Quinoa kochen.','Mit Brokkoli und Avocado anrichten.'] },
{ n:'Vegane Kichererbsen-Bowl mit Tahin', m:'mittag', t:28, mp:1, ing:[['kichererbsen',140],['bulgur',150],['rotkohl',60],['moehren',50],['tahin',20],['petersilie',5]], s:['Kichererbsen rösten.','Bulgur quellen lassen.','Mit Rotkohl, Möhre und Tahin anrichten.'] },
{ n:'Teriyaki-Tofu-Bowl mit Reis', m:'mittag', t:26, mp:1, ing:[['tofu',150],['reis',160],['teriyakisauce',20],['brokkoli',80],['moehren',50],['sesam',5]], s:['Tofu braten und glasieren.','Reis kochen.','Mit Gemüse und Sesam anrichten.'] },
{ n:'Burrito-Bowl mit Rindfleisch und Bohnen', m:'mittag', t:28, mp:1, ing:[['rindersteak',140],['reis',150],['kidneybohnen',70],['mais',50],['guacamole',40],['reibekaese',30]], s:['Rind würzen und braten.','Reis und Bohnen erwärmen.','Mit Mais, Guacamole und Käse anrichten.'] },
{ n:'Falafel-Hummus-Bowl mit Couscous', m:'mittag', t:28, mp:1, ing:[['kichererbsen',140],['couscous',150],['hummus',50],['tomaten',60],['gurke',50],['petersilie',5]], s:['Falafel braten.','Couscous quellen lassen.','Mit Hummus und Gemüse anrichten.'] },
{ n:'Thai-Hähnchen-Bowl mit Erdnuss', m:'mittag', t:26, mp:1, ing:[['haehnchen',140],['reis',150],['moehren',50],['rotkohl',50],['erdnussbutter',20],['limette',6]], s:['Hähnchen braten.','Reis kochen.','Mit Gemüse und Erdnusssauce anrichten.'] },
{ n:'Mediterrane Bowl mit Halloumi und Quinoa', m:'mittag', t:26, mp:1, ing:[['halloumi',110],['quinoa',150],['cherrytomaten',60],['gurke',50],['oliven',25],['olivenoel',10]], s:['Halloumi braten.','Quinoa garen.','Mit Tomaten, Gurke und Oliven anrichten.'] },
{ n:'Sushi-Bowl mit Lachs und Avocado', m:'mittag', t:22, ing:[['lachs',120],['reis',160],['avocado',60],['gurke',50],['sojasauce',12],['nori',3]], s:['Sushireis kochen.','Lachs würfeln.','Mit Avocado, Gurke und Nori anrichten.'] },
{ n:'Chicken-Teriyaki-Bowl mit Edamame', m:'mittag', t:26, mp:1, ing:[['haehnchen',140],['reis',160],['teriyakisauce',20],['edamame',60],['moehren',50],['sesam',5]], s:['Hähnchen in Teriyaki braten.','Reis kochen.','Mit Edamame und Möhre anrichten.'] },
{ n:'Vegane Buddha-Bowl mit Rote Bete', m:'mittag', t:30, mp:1, ing:[['quinoa',150],['kichererbsen',100],['rote_beete',90],['spinat',50],['tahin',18],['kuerbiskerne',10]], s:['Kichererbsen rösten.','Quinoa garen.','Mit Rote Bete, Spinat und Tahin anrichten.'] },
{ n:'Garnelen-Mango-Bowl mit Reis', m:'mittag', t:24, ing:[['garnelen',130],['reis',150],['mango',60],['avocado',50],['limette',8],['koriandergruen',4]], s:['Garnelen braten.','Reis kochen.','Mit Mango und Avocado anrichten.'] },
{ n:'Hähnchen-Reis-Bowl mit Ananas und Curry', m:'mittag', t:26, mp:1, ing:[['haehnchen',140],['reis',160],['ananas',60],['paprika',60],['currypul',3],['koriandergruen',4]], s:['Hähnchen mit Curry braten.','Reis kochen.','Mit Ananas und Paprika anrichten.'] },
{ n:'Linsen-Feta-Bowl mit Ofengemüse', m:'mittag', t:32, mp:1, ing:[['linsen',150],['zucchini',70],['paprika',70],['feta',50],['bulgur',120],['olivenoel',10]], s:['Linsen garen.','Gemüse rösten.','Mit Bulgur und Feta anrichten.'] },
{ n:'Rindfleisch-Bulgogi-Bowl mit Kimchi', m:'abend', t:28, mp:1, ing:[['rindersteak',140],['reis',160],['kimchi',60],['moehren',50],['sojasauce',14],['sesam',5]], s:['Rind mariniert braten.','Reis kochen.','Mit Kimchi, Möhre und Sesam anrichten.'] },
{ n:'Falafel-Bowl mit Quinoa und Granatapfel', m:'mittag', t:28, mp:1, ing:[['kichererbsen',140],['quinoa',150],['granatapfel2',40],['gurke',50],['tahin',18],['minze',3]], s:['Falafel braten.','Quinoa garen.','Mit Granatapfel, Gurke und Tahin anrichten.'] },
];
