// Griechische Küche. Von Hand geschrieben.
module.exports = [
{ n:'Pastitsio', m:'abend', t:60, mp:1, ing:[['nudeln',160],['hackrind',120],['passata',140],['bechamel',120],['bergkaese',40]], s:['Hack mit Passata würzen.','Mit Nudeln in eine Form schichten.','Mit Béchamel und Käse überbacken.'] },
{ n:'Gemista (gefülltes Gemüse)', m:'abend', t:55, mp:1, ing:[['paprika',120],['tomaten',120],['reis',120],['zwiebel',50],['olivenoel',14],['petersilie',5]], s:['Paprika und Tomaten aushöhlen.','Mit gewürztem Reis füllen.','Im Ofen mit Öl schmoren.'] },
{ n:'Spanakopita', m:'abend', t:45, mp:1, ing:[['filoteig',100],['spinat',150],['feta',80],['ei',60],['olivenoel',12]], s:['Spinat andünsten und mit Feta und Ei mischen.','In Filoteig einschlagen.','Goldbraun backen.'] },
{ n:'Keftedes (griechische Frikadellen)', m:'abend', t:30, mp:1, ing:[['hackgemischt',140],['zwiebel',40],['minze',3],['kartoffeln',180],['zitrone',8],['olivenoel',10]], s:['Hack mit Zwiebel und Minze würzen und formen.','In Öl braten.','Mit Kartoffeln und Zitrone servieren.'] },
{ n:'Fasolada (Bohnensuppe)', m:'mittag', t:40, mp:1, ing:[['weissebohnen',180],['moehren',70],['sellerie',50],['passata',90],['zwiebel',40],['olivenoel',12]], s:['Gemüse andünsten.','Bohnen, Passata und Wasser zugeben.','Weich köcheln.'] },
{ n:'Youvetsi (Ofen-Nudeln mit Rind)', m:'abend', t:55, mp:1, ing:[['nudeln',160],['rindersteak',140],['passata',150],['zwiebel',50],['bergkaese',40]], s:['Rind mit Zwiebel anbraten.','Mit Nudeln und Passata in eine Form geben.','Im Ofen garen und mit Käse bestreuen.'] },
{ n:'Kotopoulo Lemonato (Zitronenhähnchen)', m:'abend', t:45, mp:1, ing:[['haehnchen',160],['kartoffeln',200],['zitrone',15],['oregano',3],['olivenoel',14],['knoblauch',6]], s:['Hähnchen und Kartoffeln mit Zitrone, Oregano und Öl mischen.','Im Ofen bei 200 Grad backen.','Zusammen servieren.'] },
{ n:'Gigantes (Riesenbohnen im Ofen)', m:'abend', t:50, mp:1, ing:[['weissebohnen',200],['passata',130],['zwiebel',50],['dill',4],['olivenoel',14],['broetchen',50]], s:['Zwiebel anbraten, Bohnen und Passata zugeben.','In eine Form geben und im Ofen schmoren.','Mit Brot servieren.'] },
{ n:'Soutzoukakia (Hackrollen in Tomatensauce)', m:'abend', t:35, mp:1, ing:[['hackrind',140],['passata',150],['kreuzkuemmel',3],['reis',150],['zwiebel',40]], s:['Hack mit Kreuzkümmel zu Rollen formen und braten.','In Tomatensauce köcheln.','Mit Reis servieren.'] },
{ n:'Kolokithokeftedes (Zucchini-Feta-Puffer)', m:'mittag', t:30, mp:1, ing:[['zucchini',200],['feta',60],['ei',50],['mehl',25],['naturjoghurt',60],['dill',4]], s:['Zucchini raspeln und mit Feta, Ei und Mehl mischen.','Kleine Puffer braten.','Mit Joghurt-Dip servieren.'] },
{ n:'Saganaki mit Salat', m:'mittag', t:15, ing:[['halloumi',120],['mehl',15],['salat',60],['tomaten',60],['zitrone',10],['olivenoel',10]], s:['Käse in Mehl wenden und in Öl braten.','Mit Zitrone beträufeln.','Mit Salat servieren.'] },
{ n:'Briam mit Feta', m:'abend', t:50, mp:1, ing:[['kartoffeln',150],['zucchini',80],['aubergine',80],['passata',100],['feta',50],['olivenoel',14]], s:['Gemüse in Scheiben schneiden.','Mit Passata und Öl im Ofen schmoren.','Mit Feta bestreuen.'] },
{ n:'Griechischer Joghurt mit Honig und Nüssen', m:'fruh', t:6, ing:[['griechjoghurt',200],['honig',15],['walnuesse',20],['feige',40]], s:['Joghurt in eine Schale geben.','Feige und Nüsse zugeben.','Mit Honig beträufeln.'] },
{ n:'Gyros-Pita mit Tzatziki', m:'mittag', t:28, mp:1, ing:[['gyrosfleisch',150],['fladenbrot',80],['naturjoghurt',60],['gurke',50],['tomaten',50]], s:['Gyros braten.','Tzatziki aus Joghurt und Gurke rühren.','In Pita mit Tomaten füllen.'] },
{ n:'Revithada (Kichererbsen aus dem Ofen)', m:'abend', t:60, mp:1, ing:[['kichererbsen',190],['zwiebel',60],['zitrone',12],['rosmarin',2],['olivenoel',16],['broetchen',50]], s:['Kichererbsen mit Zwiebel, Zitrone und Öl mischen.','Langsam im Ofen schmoren.','Mit Brot servieren.'] },
{ n:'Griechische Hähnchen-Bowl mit Feta', m:'mittag', t:28, mp:1, ing:[['haehnchen',150],['reis',150],['gurke',60],['tomaten',60],['feta',50],['oliven',25]], s:['Hähnchen mit Oregano braten.','Reis kochen.','Mit Gurke, Tomate, Feta und Oliven anrichten.'] },
];
