// Balkan & osteuropäische Küche. Von Hand geschrieben.
module.exports = [
{ n:'Ćevapi mit Ajvar', m:'abend', t:30, mp:1, ing:[['hackgemischt',150],['zwiebel',50],['fladenbrot',80],['ajvar2',30],['knoblauch',5]], s:['Hack mit Knoblauch würzen und zu Röllchen formen.','Kräftig anbraten.','Mit Fladenbrot, Zwiebel und Ajvar servieren.'] },
{ n:'Pljeskavica mit Kartoffeln', m:'abend', t:30, mp:1, ing:[['hackrind',160],['zwiebel',50],['kartoffeln',200],['ajvar2',25],['paprikapulver',2]], s:['Hack würzen und zu großer Bulette formen.','Braten.','Mit Kartoffeln und Ajvar servieren.'] },
{ n:'Sarma (gefüllte Krautrouladen)', m:'abend', t:70, mp:1, ing:[['weisskohl',150],['hackgemischt',120],['reis',70],['passata',120],['zwiebel',40]], s:['Kohlblätter blanchieren.','Mit Hack-Reis-Masse füllen und rollen.','In Tomatensauce langsam schmoren.'] },
{ n:'Djuvec mit Paprika und Reis', m:'mittag', t:35, mp:1, ing:[['reis',170],['paprika',80],['zucchini',60],['passata',110],['zwiebel',40],['olivenoel',10]], s:['Zwiebel und Gemüse anbraten.','Reis und Passata zugeben.','Mit Brühe garen.'] },
{ n:'Lecsó mit Ei', m:'mittag', t:25, ing:[['paprika',150],['tomaten',80],['zwiebel',50],['ei',100],['paprikapulver',3],['olivenoel',10]], s:['Zwiebel und Paprika in Öl schmoren.','Tomaten und Paprikapulver zugeben.','Eier unterrühren und stocken lassen.'] },
{ n:'Segediner Gulasch', m:'abend', t:55, mp:1, ing:[['schweinefilet',150],['sauerkraut',150],['schmand',60],['zwiebel',50],['paprikapulver',3],['kartoffeln',150]], s:['Schwein mit Zwiebel anbraten.','Sauerkraut und Paprikapulver zugeben und schmoren.','Mit Schmand verfeinern, mit Kartoffeln servieren.'] },
{ n:'Punjene Paprike (gefüllte Paprika Balkan)', m:'abend', t:50, mp:1, ing:[['paprika',200],['hackrind',120],['reis',110],['passata',120],['zwiebel',40]], s:['Reis mit angebratenem Hack und Zwiebel mischen.','Paprika füllen.','In Tomatensauce schmoren.'] },
{ n:'Pasulj (Bohneneintopf)', m:'mittag', t:45, mp:1, ing:[['weissebohnen',180],['bacon',40],['moehren',60],['zwiebel',50],['paprikapulver',3],['bruehe',300]], s:['Speck und Zwiebel anbraten.','Bohnen, Möhre und Paprikapulver zugeben.','Mit Brühe weich köcheln.'] },
{ n:'Pierogi mit Kartoffel-Käse-Füllung', m:'abend', t:50, mp:1, ing:[['mehl',80],['kartoffeln',150],['bergkaese',50],['zwiebel',50],['butter',15]], s:['Teigtaschen mit Kartoffel-Käse-Masse füllen.','In Salzwasser garen.','Mit Röstzwiebeln in Butter schwenken.'] },
{ n:'Borschtsch', m:'mittag', t:50, mp:1, ing:[['rote_beete',180],['kartoffeln',120],['weisskohl',80],['moehren',60],['bruehe',400],['schmand',40]], s:['Gemüse würfeln und andünsten.','Mit Brühe weich kochen.','Mit einem Klecks Schmand servieren.'] },
{ n:'Paprikahähnchen (Paprikás Csirke)', m:'abend', t:40, mp:1, ing:[['haehnchen',160],['paprika',80],['schmand',70],['zwiebel',50],['paprikapulver',3],['nudeln',160]], s:['Hähnchen mit Zwiebel und Paprikapulver anbraten.','Paprika zugeben, mit Schmand zur Sauce köcheln.','Mit Nudeln servieren.'] },
{ n:'Bogracs (Kesselgulasch)', m:'abend', t:70, mp:1, ing:[['rindersteak',150],['kartoffeln',150],['paprika',70],['passata',90],['zwiebel',60],['paprikapulver',3]], s:['Rind und Zwiebel scharf anbraten.','Paprikapulver, Passata und Wasser zugeben.','Kartoffeln zugeben und weich schmoren.'] },
{ n:'Gebackene Bohnen (Prebranac)', m:'abend', t:55, mp:1, ing:[['weissebohnen',200],['zwiebel',80],['paprikapulver',3],['olivenoel',14],['lorbeer',1],['broetchen',50]], s:['Zwiebeln in Öl schmoren.','Mit Bohnen und Paprikapulver schichten.','Im Ofen langsam backen.'] },
{ n:'Balkan-Ofengemüse mit Feta', m:'abend', t:45, mp:1, ing:[['paprika',90],['zucchini',80],['aubergine',80],['ajvar2',30],['feta',50],['olivenoel',14]], s:['Gemüse mit Ajvar und Öl mischen.','Auf ein Blech geben.','Rösten und mit Feta bestreuen.'] },
{ n:'Kajmak-Brot mit Ei', m:'fruh', t:12, ing:[['fladenbrot',90],['frischkaese',40],['ei',100],['fruehlingszwiebel',15]], s:['Fladenbrot mit Frischkäse (Kajmak) bestreichen.','Rührei zubereiten.','Mit Frühlingszwiebeln belegen.'] },
{ n:'Balkan-Bohnensalat', m:'mittag', t:18, mp:1, ing:[['weissebohnen',180],['rotezwiebel',40],['petersilie',5],['essig',10],['olivenoel',12],['paprika',50]], s:['Bohnen abspülen.','Mit Zwiebel und Paprika mischen.','Mit Essig und Öl marinieren.'] },
];
