// Sättigende Salate, Teil 2. Von Hand geschrieben.
module.exports = [
{ n:'Waldorfsalat mit Hähnchen', m:'mittag', t:20, ing:[['haehnchen',130],['apfel',80],['sellerie',60],['walnuesse',20],['naturjoghurt',60],['salat',60]], s:['Hähnchen braten und würfeln.','Apfel, Sellerie und Walnüsse mischen.','Mit Joghurtdressing auf Salat anrichten.'] },
{ n:'Quinoa-Granatapfel-Salat', m:'mittag', t:25, mp:1, ing:[['quinoa',160],['granatapfel2',40],['gurke',60],['feta',50],['minze',4],['olivenoel',10]], s:['Quinoa garen und abkühlen.','Mit Gurke und Granatapfel mischen.','Feta und Minze zugeben.'] },
{ n:'Süßkartoffel-Linsen-Salat', m:'mittag', t:30, mp:1, ing:[['suesskartoffel',150],['linsen',130],['rucola',40],['feta',40],['walnuesse',15],['balsamico',8]], s:['Süßkartoffel im Ofen rösten.','Linsen garen.','Mit Rucola, Feta und Nüssen anrichten.'] },
{ n:'Ofengemüse-Salat mit Halloumi', m:'mittag', t:35, mp:1, ing:[['zucchini',80],['paprika',80],['aubergine',70],['halloumi',100],['rucola',40],['olivenoel',12]], s:['Gemüse rösten.','Halloumi braten.','Mit Rucola und Dressing anrichten.'] },
{ n:'Hähnchen-Mango-Salat', m:'mittag', t:22, ing:[['haehnchen',140],['mango',80],['salat',80],['avocado',50],['limette',8],['olivenoel',8]], s:['Hähnchen braten und schneiden.','Mit Mango und Avocado auf Salat anrichten.','Mit Limettendressing beträufeln.'] },
{ n:'Feldsalat mit Speck und Ei', m:'mittag', t:18, ing:[['salat',80],['bacon',40],['ei',100],['broetchen',40],['balsamico',8],['olivenoel',10]], s:['Speck und Croutons anbraten.','Eier kochen.','Mit Feldsalat und Dressing anrichten.'] },
{ n:'Rucola-Parmesan-Salat mit Pute', m:'mittag', t:20, ing:[['pute',140],['rucola',60],['parmesan',25],['cherrytomaten',70],['pinienkerne',15],['balsamico',8]], s:['Pute braten und in Streifen schneiden.','Rucola mit Tomaten anrichten.','Mit Parmesan, Pinienkernen und Balsamico toppen.'] },
{ n:'Bunter Quinoa-Bowl-Salat', m:'mittag', t:25, mp:1, ing:[['quinoa',150],['kichererbsen',80],['paprika',60],['mais',50],['avocado',50],['limette',8]], s:['Quinoa garen und abkühlen.','Mit Kichererbsen und Gemüse mischen.','Mit Avocado und Limette abschmecken.'] },
{ n:'Caprese-Bowl mit Rucola', m:'mittag', t:15, ing:[['mozzarella',80],['tomaten',120],['rucola',40],['basilikum',5],['olivenoel',12],['balsamico',8]], s:['Mozzarella und Tomate anrichten.','Mit Rucola und Basilikum belegen.','Mit Öl und Balsamico beträufeln.'] },
{ n:'Reis-Thunfisch-Salat mit Ei', m:'mittag', t:20, mp:1, ing:[['reis',160],['thunfisch',100],['ei',100],['mais',50],['paprika',50],['olivenoel',10]], s:['Reis kochen und abkühlen.','Mit Thunfisch, Mais und Paprika mischen.','Mit Ei anrichten.'] },
{ n:'Kichererbsen-Avocado-Salat', m:'mittag', t:15, mp:1, ing:[['kichererbsen',160],['avocado',70],['tomaten',70],['gurke',60],['zitrone',8],['olivenoel',10]], s:['Kichererbsen abspülen.','Mit Avocado, Tomate und Gurke mischen.','Mit Zitrone und Öl abschmecken.'] },
{ n:'Grüner Kraftsalat mit Ei und Kürbiskernen', m:'mittag', t:18, ing:[['salat',90],['ei',100],['avocado',60],['kuerbiskerne',20],['cherrytomaten',60],['olivenoel',10]], s:['Eier kochen.','Salat mit Avocado und Tomaten anrichten.','Mit Kürbiskernen und Dressing toppen.'] },
{ n:'Bulgur-Kichererbsen-Salat orientalisch', m:'mittag', t:22, mp:1, ing:[['bulgur',150],['kichererbsen',90],['petersilie',6],['tomaten',60],['zitrone',10],['olivenoel',10]], s:['Bulgur quellen lassen.','Mit Kichererbsen und Tomaten mischen.','Mit Kräutern, Zitrone und Öl abschmecken.'] },
{ n:'Lachs-Spinat-Salat mit Avocado', m:'mittag', t:20, ing:[['lachs',130],['spinat',70],['avocado',60],['cherrytomaten',60],['zitrone',8],['olivenoel',10]], s:['Lachs braten.','Spinat mit Avocado und Tomaten anrichten.','Mit Lachs und Dressing servieren.'] },
{ n:'Nudelsalat mit Pesto und Mozzarella', m:'mittag', t:20, mp:1, ing:[['fusilli',160],['pesto',30],['mozzarella',60],['cherrytomaten',80],['rucola',30]], s:['Nudeln kochen und abkühlen.','Mit Pesto, Mozzarella und Tomaten mischen.','Rucola unterheben.'] },
{ n:'Rote-Bete-Ziegenkäse-Salat mit Walnuss', m:'mittag', t:18, ing:[['rote_beete',130],['ziegenkaese',50],['salat',60],['walnuesse',20],['honig',8],['balsamico',8]], s:['Rote Bete würfeln.','Mit Salat und Ziegenkäse anrichten.','Mit Walnüssen, Honig und Balsamico toppen.'] },
];
